// Every value a part's `parts.status` can hold — the ticket page's Part
// Transaction dropdown and Part Receive's Part Status column both read this.
export const PART_STATUS_OPTIONS = [
  "Back Order",
  "Cancelled",
  "Claimed",
  "CX Home",
  "Cx Received",
  "Defective",
  "Dropship",
  "Hold for Estimation",
  "Hold for next vist",
  "In Review",
  "Lost",
  "Need PO",
  "Not Used & Stocked",
  "PAID",
  "Part Ready",
  "PNN",
  "PO Made",
  "RA - Defect",
  "RA- DMG",
  "RA - PNN",
  "RA - Qty Discrepancy",
  "SQT Received",
  "Tech Pickup",
  "Transfer to Another Ticket",
  "Used",
] as const;
