/**
 * Centralized Ticket Data
 * 
 * This file contains all dummy ticket data used across the platform.
 * Import and use these tickets in:
 * - Work Map
 * - Work Planner
 * - Ticket Details
 * - Ticket List
 * - Claims Calendar
 * - Any other ticket-related components
 */

export interface Ticket {
  ticketNo: string;
  ticketSource?: string;
  warranty: string;
  manufacturer: string;
  customer: string;
  city: string;
  location: string;
  model: string;
  internalNote: string;
  diagnosed: string;
  technician: string;
  customerPref: string;
  schedule: string;
  status: string;
  phone: string;
  redo: string;
  aging: number;
  calls: number;
  partOrder: string;
  created: string;
  statusChangedAt?: string;
  statusChangedBy?: string;
  // Additional fields for ticket details
  account?: string;
  irKit?: string;
  type?: string;
  branch?: string;
  contact?: string;
  delay?: number;
  // Customer details
  firstName?: string;
  lastName?: string;
  address?: string;
  address2?: string;
  zip?: string;
  state?: string;
  email?: string;
  secondPhone?: string;
  // Product details
  serial?: string;
  modelVersion?: string;
  productType?: string;
  purchaseDate?: string;
  // Additional tracking fields
  fakeTicket?: boolean;
  originalTicketNo?: string;
  callReceivedDate?: string;
  addressNote?: string;
  claimCompany?: string;
  // Service tracking data - visits and parts integrated into ticket
  visits?: Array<{
    id: string;
    visitNo: string;
    timestamp: string;
    updatedAt?: string;
    updatedBy?: string;
    updateReason?: string;
    by: string;
    scheduleDate: string;
    technician: string;
    timeSlot: string;
    activity: string;
    actionType: string;
    repairStatus: string;
    repairType: string;
    schedNotes: string;
    reclaim: string;
    visited: string;
    notCompleted: string;
    symptomCx: string;
    diagnosis: string;
    symptomTech: string;
    resolution: string;
    nonCompletionReason: string;
    triageNote: string;
    status: string;
    note: string;
  }>;
  parts?: Array<{
    id: string;
    partNo: string;
    partDist: string;
    partDesc: string;
    poNo: string;
    poDate: string;
    invoiceNo: string;
    invoiceDate: string;
    quantity: string;
    partPrice: string;
    coreValue: string;
    shipCost: string;
    markup: string;
    totalMarkup: string;
    claimTo: string;
    status: string;
    note: string;
    visitId: string;
    orderNo: string;
    eta: string;
    inTracking: string;
    raDate: string;
    raNo: string;
    outTracking: string;
    creditNo: string;
    hold: string;
    cxPaid: string;
    createdBy: string;
    lastModifiedBy: string;
  }>;
  alertMessages?: Array<{
    id: string;
    text: string;
    by: string;
    timestamp: string;
  }>;
}

export const TICKET_SOURCES = [
  "LG",
  "Midea-104268",
  "NSA GSLEE",
  "NSA MEMPHIS",
  "SB",
  "SB-1276506820",
  "SB-Miele",
  "SP",
  "SP1",
  "SS",
  "SS-6488757",
  "EarlyRepair",
] as const;

export const REPAIR_STATUS_OPTIONS = [
  "CL-Need",
  "Cancel",
  "CL-Parts Back Ordered",
  "CL-Ready to Complete",
  "CSR-Acknowledged",
  "CSR-Assigned to ASC",
  "CSR-Left Message for Cx",
  "CSR-Needs Scheduling",
  "OP-Ready for Service",
  "OP-Reschedule Follow up",
  "OP-UPDATE HOLD",
  "OP-Waiting for Part",
  "PT-Need PreAuthorization",
  "TR-Need PO",
  "TR-Need Triage",
] as const;

/**
 * Raw ticket data without ticket sources
 */
const RAW_TICKETS: Omit<Ticket, "ticketSource">[] = [
  {
    ticketNo: "SA-3458831",
    warranty: "IW",
    account: "GSL00002",
    manufacturer: "IH",
    customer: "Neal Market",
    city: "GREENSBORO",
    location: "Atlanta",
    model: "GNE27JYMFFS",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "",
    diagnosed: "N",
    technician: "",
    customerPref: "N",
    contact: "",
    schedule: "05/21/26",
    status: "CSR-Assigned to ASC",
    delay: 0,
    phone: "706.817.2900",
    redo: "N",
    aging: 0,
    calls: 0,
    partOrder: "Not Diagnosed",
    created: "05/18/26",
    firstName: "NEAL",
    lastName: "MARKET",
    address: "123 Main St",
    zip: "30642",
  },
  {
    ticketNo: "26000679102DF",
    warranty: "IW",
    account: "GSL00002",
    manufacturer: "IH",
    customer: "Brian Rowe",
    city: "SHADY DALE",
    location: "Atlanta",
    model: "FCRE3083AS",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "",
    diagnosed: "N",
    technician: "",
    customerPref: "N",
    contact: "",
    schedule: "05/19/26",
    status: "CSR-Assigned to ASC",
    delay: 1,
    phone: "706.366.1043",
    redo: "N",
    aging: 1,
    calls: 0,
    partOrder: "Not Diagnosed",
    created: "05/17/26",
    firstName: "BRIAN",
    lastName: "ROWE",
    address: "456 Oak Ave",
    zip: "31085",
  },
  {
    ticketNo: "1007208750-10",
    warranty: "IW",
    account: "GSL00002",
    manufacturer: "IH",
    customer: "Charles Mcdonald",
    city: "GREENSBORO",
    location: "Atlanta",
    model: "FRUF2020AW",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "",
    diagnosed: "N",
    technician: "",
    customerPref: "N",
    contact: "",
    schedule: "05/19/26",
    status: "CSR-Assigned to ASC",
    delay: 1,
    phone: "404.680.4022",
    redo: "N",
    aging: 1,
    calls: 0,
    partOrder: "Not Diagnosed",
    created: "05/17/26",
    firstName: "CHARLES",
    lastName: "MCDONALD",
    address: "789 Elm St",
    zip: "30642",
  },
  {
    ticketNo: "027360174134",
    warranty: "IW",
    account: "GSL00002",
    manufacturer: "IH",
    customer: "Lauren Santori",
    city: "TEMPLE",
    location: "Atlanta",
    model: "NE63A6511SS",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "",
    diagnosed: "N",
    technician: "",
    customerPref: "N",
    contact: "",
    schedule: "05/20/26",
    status: "CSR-Assigned to ASC",
    delay: 1,
    phone: "770.820.1665",
    redo: "N",
    aging: 1,
    calls: 0,
    partOrder: "Not Diagnosed",
    created: "05/17/26",
    firstName: "LAUREN",
    lastName: "SANTORI",
    address: "321 Pine Rd",
    zip: "30179",
  },
  {
    ticketNo: "26000671769DF1",
    warranty: "IW",
    account: "GSL00002",
    manufacturer: "IH",
    customer: "Rose Phillips",
    city: "ELLENWOOD",
    location: "Atlanta",
    model: "DV45K7600EW",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "",
    diagnosed: "Y",
    technician: "Nathan Napora",
    customerPref: "Y",
    contact: "",
    schedule: "05/18/26",
    status: "OP-Waiting for Part",
    delay: 3,
    phone: "404.640.7141",
    redo: "Y",
    aging: 3,
    calls: 0,
    partOrder: "Part Ordered",
    created: "05/15/26",
    firstName: "ROSE",
    lastName: "PHILLIPS",
    address: "555 Maple Dr",
    zip: "30294",
  },
  {
    ticketNo: "7039321404BL-13",
    warranty: "IW",
    account: "ER",
    manufacturer: "IH",
    customer: "Melissa Beaver",
    city: "EATONTON",
    location: "Atlanta",
    model: "GCCE3670AS",
    internalNote: "WF 05/15 waiting for parts tracking",
    irKit: "",
    type: "SMS",
    branch: "",
    diagnosed: "Y",
    technician: "Joshua Silva",
    customerPref: "N",
    contact: "",
    schedule: "05/15/26",
    status: "OP-Waiting for Part",
    delay: 4,
    phone: "703.932.1404",
    redo: "Y",
    aging: 4,
    calls: 0,
    partOrder: "Partially Ordered",
    created: "05/14/26",
    firstName: "MELISSA",
    lastName: "BEAVER",
    address: "888 Cedar Ln",
    zip: "31024",
  },
  {
    ticketNo: "SA-3433383",
    warranty: "IW",
    account: "GSL00002",
    manufacturer: "IH",
    customer: "Accent Overlook",
    city: "CANTON",
    location: "Atlanta",
    model: "GDT535PSRSS",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "",
    diagnosed: "N",
    technician: "",
    customerPref: "Y",
    contact: "",
    schedule: "05/18/26",
    status: "CSR-Left Message for Cx",
    delay: 4,
    phone: "770.766.0064",
    redo: "N",
    aging: 4,
    calls: 2,
    partOrder: "Not Diagnosed",
    created: "05/14/26",
    firstName: "ACCENT",
    lastName: "OVERLOOK",
    address: "999 Hillside Ct",
    zip: "30114",
  },
  {
    ticketNo: "SA-3431358",
    warranty: "IW",
    account: "GSL00002",
    manufacturer: "IH",
    customer: "Evelin Tirado",
    city: "EATONTON",
    location: "Atlanta",
    model: "HDF330PGRBB",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "",
    diagnosed: "N",
    technician: "",
    customerPref: "N",
    contact: "",
    schedule: "05/19/26",
    status: "CSR-Left Message for Cx",
    delay: 4,
    phone: "706.816.6545",
    redo: "N",
    aging: 4,
    calls: 2,
    partOrder: "Not Diagnosed",
    created: "05/14/26",
    firstName: "EVELIN",
    lastName: "TIRADO",
    address: "222 Valley View",
    zip: "31024",
  },
  {
    ticketNo: "3850106E11",
    warranty: "IW",
    account: "GSL00002",
    manufacturer: "IH",
    customer: "Tricon Propertymanager",
    city: "DALLAS",
    location: "Atlanta",
    model: "GTX22EASK1WW",
    internalNote: "WF 05/16 - Sent message to tech",
    irKit: "",
    type: "SMS",
    branch: "",
    diagnosed: "N",
    technician: "Abel Severino",
    customerPref: "N",
    contact: "",
    schedule: "05/15/26",
    status: "OP-UPDATE HOLD",
    delay: 5,
    phone: "678.508.7857",
    redo: "N",
    aging: 5,
    calls: 0,
    partOrder: "Not Diagnosed",
    created: "05/13/26",
    firstName: "TRICON",
    lastName: "PROPERTY",
    address: "111 Property Ln",
    zip: "30132",
  },
  {
    ticketNo: "26000663669DF1",
    warranty: "IW",
    account: "GSL00002",
    manufacturer: "IH",
    customer: "Shirley Gentry",
    city: "TAYLORSVILLE",
    location: "Atlanta",
    model: "MVW7232HW",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "",
    diagnosed: "N",
    technician: "Abel Severino",
    customerPref: "N",
    contact: "",
    schedule: "05/15/26",
    status: "TR-Need Triage",
    delay: 5,
    phone: "770.316.3847",
    redo: "N",
    aging: 5,
    calls: 0,
    partOrder: "Not Diagnosed",
    created: "05/13/26",
    firstName: "SHIRLEY",
    lastName: "GENTRY",
    address: "444 Forest Way",
    zip: "30178",
  },
  {
    ticketNo: "TK-MEMPHIS-001",
    warranty: "IW",
    account: "MEM001",
    manufacturer: "IH",
    customer: "James Anderson",
    city: "MEMPHIS",
    location: "Memphis",
    model: "WM3488HW",
    internalNote: "Priority customer",
    irKit: "",
    type: "Phone",
    branch: "Memphis",
    diagnosed: "Y",
    technician: "Darrin Stewart",
    customerPref: "Y",
    contact: "Y",
    schedule: "06/15/26",
    status: "OP-Ready for Service",
    delay: 0,
    phone: "901.555.0123",
    redo: "N",
    aging: 2,
    calls: 1,
    partOrder: "Part Ordered",
    created: "06/13/26",
    firstName: "JAMES",
    lastName: "ANDERSON",
    address: "100 Beale St",
    zip: "38103",
  },
  {
    ticketNo: "TK-NASHVILLE-001",
    warranty: "OW",
    account: "NASH001",
    manufacturer: "Samsung",
    customer: "Sarah Williams",
    city: "NASHVILLE",
    location: "Nashville",
    model: "RF28R7351SG",
    internalNote: "Out of warranty - quoted $250",
    irKit: "",
    type: "SMS",
    branch: "Nashville",
    diagnosed: "Y",
    technician: "John Godfrey",
    customerPref: "N",
    contact: "Y",
    schedule: "06/16/26",
    status: "CSR-Needs Scheduling",
    delay: 1,
    phone: "615.555.0456",
    redo: "N",
    aging: 3,
    calls: 2,
    partOrder: "Part Ordered",
    created: "06/13/26",
    firstName: "SARAH",
    lastName: "WILLIAMS",
    address: "200 Music Row",
    zip: "37203",
  },
  {
    ticketNo: "TK-BIRMINGHAM-001",
    warranty: "IW",
    account: "BIR001",
    manufacturer: "Whirlpool",
    customer: "Michael Brown",
    city: "BIRMINGHAM",
    location: "Birmingham",
    model: "WED7120HW",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Birmingham",
    diagnosed: "N",
    technician: "David Sims",
    customerPref: "Y",
    contact: "",
    schedule: "06/17/26",
    status: "CSR-Assigned to ASC",
    delay: 0,
    phone: "205.555.0789",
    redo: "N",
    aging: 1,
    calls: 0,
    partOrder: "Not Diagnosed",
    created: "06/14/26",
    firstName: "MICHAEL",
    lastName: "BROWN",
    address: "300 Highland Ave",
    zip: "35205",
  },
  {
    ticketNo: "TK-JACKSONVILLE-001",
    warranty: "IW",
    account: "JAX001",
    manufacturer: "LG",
    customer: "Emily Davis",
    city: "JACKSONVILLE",
    location: "Jacksonville",
    model: "LRFVS3006S",
    internalNote: "",
    irKit: "",
    type: "Phone",
    branch: "Jacksonville",
    diagnosed: "Y",
    technician: "Bradley Hollowell",
    customerPref: "N",
    contact: "Y",
    schedule: "06/18/26",
    status: "OP-Waiting for Part",
    delay: 2,
    phone: "904.555.0321",
    redo: "N",
    aging: 4,
    calls: 1,
    partOrder: "Part Ordered",
    created: "06/12/26",
    firstName: "EMILY",
    lastName: "DAVIS",
    address: "400 Beach Blvd",
    zip: "32250",
  },
  {
    ticketNo: "TK-LAKECHARLES-001",
    warranty: "IW",
    account: "LC001",
    manufacturer: "Frigidaire",
    customer: "Robert Chance",
    city: "LAKE CHARLES",
    location: "Lake Charles",
    model: "FFRE4120SW",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Lake Charles",
    diagnosed: "N",
    technician: "Danny Thornton",
    customerPref: "N",
    contact: "Sched.",
    schedule: "N/A",
    status: "CSR-Needs Scheduling",
    delay: 0,
    phone: "337.555.0654",
    redo: "N",
    aging: 1,
    calls: 1,
    partOrder: "Not Diagnosed",
    created: "06/14/26",
    firstName: "ROBERT",
    lastName: "CHANCE",
    address: "500 Lakeshore Dr",
    zip: "70601",
  },
  {
    ticketNo: "025631219101",
    warranty: "IW",
    account: "ENCOMPASS",
    manufacturer: "LG",
    customer: "James White",
    city: "CHATTANOOGA",
    location: "Knoxville",
    model: "WTW5000DW",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Knoxville",
    diagnosed: "Y",
    technician: "",
    customerPref: "PM",
    contact: "Y",
    schedule: "06/21/26",
    status: "OP-Waiting for Part",
    delay: 4,
    phone: "758.289.7912",
    redo: "Y",
    aging: 6,
    calls: 4,
    partOrder: "PO Made",
    created: "06/16/26",
    firstName: "JAMES",
    lastName: "WHITE",
    address: "9028 Birch Ave",
    zip: "37401",
    state: "TN",
    email: "james.white@email.com",
    serial: "LG8536477",
    productType: "Range",
  },
  {
    ticketNo: "SA-3848749",
    warranty: "IW",
    account: "SQUARE TRADE",
    manufacturer: "FRIGIDAIRE",
    customer: "Ashley Smith",
    city: "ASHEVILLE",
    location: "Charlotte",
    model: "WRS325SDHZ",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Charlotte",
    diagnosed: "Y",
    technician: "Carlos Rivera",
    customerPref: "Any",
    contact: "N",
    schedule: "06/10/26",
    status: "Completed",
    delay: 4,
    phone: "981.544.2674",
    redo: "N",
    aging: 17,
    calls: 6,
    partOrder: "Not Diagnosed",
    created: "06/05/26",
    firstName: "ASHLEY",
    lastName: "SMITH",
    address: "7627 Maple Dr",
    zip: "28801",
    state: "NC",
    email: "ashley.smith@email.com",
    serial: "FR2322047",
    productType: "Range",
  },
  {
    ticketNo: "27995970241DF",
    warranty: "EW",
    account: "GSL00002",
    manufacturer: "LG",
    customer: "Charles Miller",
    city: "NASHVILLE",
    location: "Atlanta",
    model: "LRMVS3006S",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Atlanta",
    diagnosed: "N",
    technician: "James Okafor",
    customerPref: "PM",
    contact: "N",
    schedule: "06/22/26",
    status: "CL-Ready to Complete",
    delay: 2,
    phone: "589.484.8428",
    redo: "N",
    aging: 5,
    calls: 5,
    partOrder: "Part Ready",
    created: "06/17/26",
    firstName: "CHARLES",
    lastName: "MILLER",
    address: "1269 Main Ln",
    zip: "37201",
    state: "TN",
    email: "charles.miller@email.com",
    serial: "LG5107245",
    productType: "Refrigerator",
  },
  {
    ticketNo: "1496348124-58",
    warranty: "IW",
    account: "ASSURANT",
    manufacturer: "MAYTAG",
    customer: "David Robinson",
    city: "MOBILE",
    location: "Knoxville",
    model: "NE63T8511SS",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Knoxville",
    diagnosed: "N",
    technician: "Danny Thornton",
    customerPref: "PM",
    contact: "Sched.",
    schedule: "06/13/26",
    status: "CSR-Assigned to ASC",
    delay: 3,
    phone: "610.474.2084",
    redo: "N",
    aging: 14,
    calls: 5,
    partOrder: "—",
    created: "06/08/26",
    firstName: "DAVID",
    lastName: "ROBINSON",
    address: "2440 Cedar Ave",
    zip: "36601",
    state: "AL",
    email: "david.robinson@email.com",
    serial: "MA5137722",
    productType: "Range",
  },
  {
    ticketNo: "090517811206",
    warranty: "IW",
    account: "GSL00002",
    manufacturer: "LG",
    customer: "Jessica Lewis",
    city: "NEW ORLEANS",
    location: "Raleigh",
    model: "KDTM404KPS",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Raleigh",
    diagnosed: "Y",
    technician: "Jacob Morehouse",
    customerPref: "N",
    contact: "Sched.",
    schedule: "05/26/26",
    status: "OP-Waiting for Part",
    delay: 0,
    phone: "973.248.2796",
    redo: "N",
    aging: 32,
    calls: 3,
    partOrder: "Ordered",
    created: "05/21/26",
    firstName: "JESSICA",
    lastName: "LEWIS",
    address: "7768 Cedar Ln",
    zip: "70112",
    state: "LA",
    email: "jessica.lewis@email.com",
    serial: "LG1192619",
    productType: "Dryer",
  },
  {
    ticketNo: "SA-3714825",
    warranty: "EW",
    account: "SQUARE TRADE",
    manufacturer: "MAYTAG",
    customer: "Donald Moore",
    city: "CHATTANOOGA",
    location: "Dallas",
    model: "PFE28KMKES",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Dallas",
    diagnosed: "Y",
    technician: "Christian Newson",
    customerPref: "AM",
    contact: "Sched.",
    schedule: "06/09/26",
    status: "OP-Ready for Service",
    delay: 2,
    phone: "664.203.5315",
    redo: "N",
    aging: 18,
    calls: 1,
    partOrder: "Part Ready",
    created: "06/04/26",
    firstName: "DONALD",
    lastName: "MOORE",
    address: "2746 Oak Ln",
    zip: "37401",
    state: "TN",
    email: "donald.moore@email.com",
    serial: "MA6438436",
    productType: "Wall Oven",
  },
  {
    ticketNo: "20083651970DF",
    warranty: "EW",
    account: "GSL00002",
    manufacturer: "GE",
    customer: "Kimberly Lopez",
    city: "HUNTSVILLE",
    location: "Knoxville",
    model: "PFE28KMKES",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Knoxville",
    diagnosed: "Y",
    technician: "Marcus Webb",
    customerPref: "PM",
    contact: "Sched.",
    schedule: "05/22/26",
    status: "CL-Parts Back Ordered",
    delay: 3,
    phone: "949.697.2133",
    redo: "N",
    aging: 36,
    calls: 2,
    partOrder: "Ordered",
    created: "05/17/26",
    firstName: "KIMBERLY",
    lastName: "LOPEZ",
    address: "7032 Pine Ln",
    zip: "35801",
    state: "AL",
    email: "kimberly.lopez@email.com",
    serial: "GE4374754",
    productType: "Range",
  },
  {
    ticketNo: "1428414718-95",
    warranty: "EW",
    account: "GSL00002",
    manufacturer: "BOSCH",
    customer: "Daniel Lopez",
    city: "COLUMBUS",
    location: "Huntsville",
    model: "MHW5630HW",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Huntsville",
    diagnosed: "Y",
    technician: "James Okafor",
    customerPref: "AM",
    contact: "Sched.",
    schedule: "06/12/26",
    status: "OP-Ready for Service",
    delay: 5,
    phone: "546.221.4770",
    redo: "Y",
    aging: 15,
    calls: 1,
    partOrder: "Not Diagnosed",
    created: "06/07/26",
    firstName: "DANIEL",
    lastName: "LOPEZ",
    address: "614 Elm St",
    zip: "31901",
    state: "GA",
    email: "daniel.lopez@email.com",
    serial: "BO9626108",
    productType: "Dishwasher",
  },
  {
    ticketNo: "037854643175",
    warranty: "OOW",
    account: "GSL00002",
    manufacturer: "BOSCH",
    customer: "Karen Jones",
    city: "SAN ANTONIO",
    location: "Knoxville",
    model: "WRS325SDHZ",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Knoxville",
    diagnosed: "N",
    technician: "Marcus Webb",
    customerPref: "AM",
    contact: "Sched.",
    schedule: "06/15/26",
    status: "CL-Claimed",
    delay: 5,
    phone: "874.641.6804",
    redo: "Y",
    aging: 12,
    calls: 0,
    partOrder: "—",
    created: "06/10/26",
    firstName: "KAREN",
    lastName: "JONES",
    address: "5659 Maple Ave",
    zip: "78201",
    state: "TX",
    email: "karen.jones@email.com",
    serial: "BO4214348",
    productType: "Dishwasher",
  },
  {
    ticketNo: "SA-3562336",
    warranty: "EW",
    account: "AIG",
    manufacturer: "ELECTROLUX",
    customer: "Joseph Jones",
    city: "JACKSONVILLE",
    location: "Memphis",
    model: "RF28R7351SG",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Memphis",
    diagnosed: "Y",
    technician: "Marcus Webb",
    customerPref: "AM",
    contact: "Y",
    schedule: "06/12/26",
    status: "Data Closed",
    delay: 1,
    phone: "763.300.1828",
    redo: "N",
    aging: 15,
    calls: 3,
    partOrder: "—",
    created: "06/07/26",
    firstName: "JOSEPH",
    lastName: "JONES",
    address: "3602 Birch St",
    zip: "32099",
    state: "FL",
    email: "joseph.jones@email.com",
    serial: "EL3762152",
    productType: "Freezer",
  },
  {
    ticketNo: "25971815972DF",
    warranty: "EW",
    account: "SQUARE TRADE",
    manufacturer: "FRIGIDAIRE",
    customer: "Kimberly Sanchez",
    city: "COLUMBUS",
    location: "Asheville",
    model: "FFSS2615TS",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Asheville",
    diagnosed: "Y",
    technician: "Carlos Rivera",
    customerPref: "Any",
    contact: "Y",
    schedule: "05/27/26",
    status: "OP-Reschedule Follow up",
    delay: 0,
    phone: "503.422.1958",
    redo: "N",
    aging: 31,
    calls: 4,
    partOrder: "Ordered",
    created: "05/22/26",
    firstName: "KIMBERLY",
    lastName: "SANCHEZ",
    address: "2679 Oak Ln",
    zip: "31901",
    state: "GA",
    email: "kimberly.sanchez@email.com",
    serial: "FR2344047",
    productType: "Refrigerator",
  },
  {
    ticketNo: "1073574218-86",
    warranty: "OOW",
    account: "CENTRICITY",
    manufacturer: "WHIRLPOOL",
    customer: "Robert Perez",
    city: "BIRMINGHAM",
    location: "Birmingham",
    model: "KDTM404KPS",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Birmingham",
    diagnosed: "N",
    technician: "Anthony Lewis",
    customerPref: "Any",
    contact: "Y",
    schedule: "06/12/26",
    status: "PT-Need PreAuthorization",
    delay: 5,
    phone: "240.834.2343",
    redo: "N",
    aging: 15,
    calls: 1,
    partOrder: "Part Ready",
    created: "06/07/26",
    firstName: "ROBERT",
    lastName: "PEREZ",
    address: "6584 Main Ct",
    zip: "35201",
    state: "AL",
    email: "robert.perez@email.com",
    serial: "WH6033115",
    productType: "Wall Oven",
  },
  {
    ticketNo: "010311570307",
    warranty: "OOW",
    account: "SQUARE TRADE",
    manufacturer: "KITCHENAID",
    customer: "Joseph Martin",
    city: "MEMPHIS",
    location: "Nashville",
    model: "GDF630PGMWW",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Nashville",
    diagnosed: "Y",
    technician: "David Kim",
    customerPref: "N",
    contact: "Sched.",
    schedule: "05/26/26",
    status: "CL-Parts Back Ordered",
    delay: 5,
    phone: "557.270.5002",
    redo: "N",
    aging: 32,
    calls: 4,
    partOrder: "Ordered",
    created: "05/21/26",
    firstName: "JOSEPH",
    lastName: "MARTIN",
    address: "228 Cedar Ct",
    zip: "38101",
    state: "TN",
    email: "joseph.martin@email.com",
    serial: "KI2737893",
    productType: "Refrigerator",
  },
  {
    ticketNo: "SA-3277312",
    warranty: "IW",
    account: "CENTRICITY",
    manufacturer: "KITCHENAID",
    customer: "Patricia Lewis",
    city: "MEMPHIS",
    location: "Charlotte",
    model: "KDTM404KPS",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Charlotte",
    diagnosed: "N",
    technician: "David Kim",
    customerPref: "N",
    contact: "N",
    schedule: "06/10/26",
    status: "OP-Waiting for Part",
    delay: 0,
    phone: "415.934.6617",
    redo: "Y",
    aging: 17,
    calls: 5,
    partOrder: "—",
    created: "06/05/26",
    firstName: "PATRICIA",
    lastName: "LEWIS",
    address: "4633 Oak St",
    zip: "38101",
    state: "TN",
    email: "patricia.lewis@email.com",
    serial: "KI6596150",
    productType: "Refrigerator",
  },
  {
    ticketNo: "21125089309DF",
    warranty: "IW",
    account: "GSL00002",
    manufacturer: "FRIGIDAIRE",
    customer: "Betty Anderson",
    city: "MOBILE",
    location: "Charlotte",
    model: "LRMVS3006S",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Charlotte",
    diagnosed: "N",
    technician: "Marcus Webb",
    customerPref: "PM",
    contact: "N",
    schedule: "06/25/26",
    status: "OP-Reschedule Follow up",
    delay: 1,
    phone: "907.352.9938",
    redo: "Y",
    aging: 0,
    calls: 2,
    partOrder: "Part Ready",
    created: "06/22/26",
    firstName: "BETTY",
    lastName: "ANDERSON",
    address: "753 Elm Ave",
    zip: "36601",
    state: "AL",
    email: "betty.anderson@email.com",
    serial: "FR5186414",
    productType: "Dryer",
  },
  {
    ticketNo: "1379759538-81",
    warranty: "EW",
    account: "SQUARE TRADE",
    manufacturer: "SAMSUNG",
    customer: "Donald Ramirez",
    city: "JACKSONVILLE",
    location: "Jacksonville",
    model: "NE63T8511SS",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Jacksonville",
    diagnosed: "N",
    technician: "",
    customerPref: "N",
    contact: "Sched.",
    schedule: "06/17/26",
    status: "CL-Parts Back Ordered",
    delay: 5,
    phone: "622.225.3938",
    redo: "N",
    aging: 10,
    calls: 2,
    partOrder: "PO Made",
    created: "06/12/26",
    firstName: "DONALD",
    lastName: "RAMIREZ",
    address: "1871 Birch St",
    zip: "32099",
    state: "FL",
    email: "donald.ramirez@email.com",
    serial: "SA8896868",
    productType: "Dishwasher",
  },
  {
    ticketNo: "074074263026",
    warranty: "EW",
    account: "ASSURANT",
    manufacturer: "GE",
    customer: "Susan Martinez",
    city: "BIRMINGHAM",
    location: "Knoxville",
    model: "RF28R7351SG",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Knoxville",
    diagnosed: "N",
    technician: "Sean Smith",
    customerPref: "Any",
    contact: "Y",
    schedule: "06/02/26",
    status: "CL-Parts Back Ordered",
    delay: 0,
    phone: "271.485.6753",
    redo: "N",
    aging: 25,
    calls: 1,
    partOrder: "Ordered",
    created: "05/28/26",
    firstName: "SUSAN",
    lastName: "MARTINEZ",
    address: "4449 Oak St",
    zip: "35201",
    state: "AL",
    email: "susan.martinez@email.com",
    serial: "GE8290770",
    productType: "Microwave",
  },
  {
    ticketNo: "SA-3763934",
    warranty: "IW",
    account: "SQUARE TRADE",
    manufacturer: "KITCHENAID",
    customer: "Sandra Hernandez",
    city: "JACKSONVILLE",
    location: "Jacksonville",
    model: "RF28R7351SG",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Jacksonville",
    diagnosed: "Y",
    technician: "Anthony Lewis",
    customerPref: "Any",
    contact: "N",
    schedule: "06/03/26",
    status: "OP-Ready for Service",
    delay: 0,
    phone: "460.245.8144",
    redo: "N",
    aging: 24,
    calls: 4,
    partOrder: "Part Ready",
    created: "05/29/26",
    firstName: "SANDRA",
    lastName: "HERNANDEZ",
    address: "2141 Cedar Ln",
    zip: "32099",
    state: "FL",
    email: "sandra.hernandez@email.com",
    serial: "KI6188935",
    productType: "Freezer",
  },
  {
    ticketNo: "25695912196DF",
    warranty: "OOW",
    account: "ENCOMPASS",
    manufacturer: "LG",
    customer: "Matthew Martinez",
    city: "MOBILE",
    location: "Memphis",
    model: "RF28R7351SG",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Memphis",
    diagnosed: "Y",
    technician: "",
    customerPref: "Any",
    contact: "N",
    schedule: "06/03/26",
    status: "CL-Claimed",
    delay: 1,
    phone: "378.830.5930",
    redo: "N",
    aging: 24,
    calls: 6,
    partOrder: "Ordered",
    created: "05/29/26",
    firstName: "MATTHEW",
    lastName: "MARTINEZ",
    address: "5379 Walnut Dr",
    zip: "36601",
    state: "AL",
    email: "matthew.martinez@email.com",
    serial: "LG8418210",
    productType: "Dishwasher",
  },
  {
    ticketNo: "1548868899-70",
    warranty: "IW",
    account: "ENCOMPASS",
    manufacturer: "WHIRLPOOL",
    customer: "Sandra Lewis",
    city: "ASHEVILLE",
    location: "New Orleans",
    model: "KDTM404KPS",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "New Orleans",
    diagnosed: "N",
    technician: "",
    customerPref: "PM",
    contact: "Y",
    schedule: "05/26/26",
    status: "CL-Ready to Complete",
    delay: 1,
    phone: "834.543.2530",
    redo: "Y",
    aging: 32,
    calls: 0,
    partOrder: "PO Made",
    created: "05/21/26",
    firstName: "SANDRA",
    lastName: "LEWIS",
    address: "7884 Maple Dr",
    zip: "28801",
    state: "NC",
    email: "sandra.lewis@email.com",
    serial: "WH7953166",
    productType: "Dishwasher",
  },
  {
    ticketNo: "076073684406",
    warranty: "IW",
    account: "SQUARE TRADE",
    manufacturer: "GE",
    customer: "Richard Davis",
    city: "KNOXVILLE",
    location: "New Orleans",
    model: "RF28R7351SG",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "New Orleans",
    diagnosed: "Y",
    technician: "James Okafor",
    customerPref: "AM",
    contact: "N",
    schedule: "05/31/26",
    status: "OP-Ready for Service",
    delay: 1,
    phone: "912.730.8611",
    redo: "N",
    aging: 27,
    calls: 5,
    partOrder: "Ordered",
    created: "05/26/26",
    firstName: "RICHARD",
    lastName: "DAVIS",
    address: "9257 Elm Dr",
    zip: "37901",
    state: "TN",
    email: "richard.davis@email.com",
    serial: "GE9468772",
    productType: "Freezer",
  },
  {
    ticketNo: "SA-3870914",
    warranty: "OOW",
    account: "SQUARE TRADE",
    manufacturer: "BOSCH",
    customer: "Kimberly Moore",
    city: "COLUMBUS",
    location: "Memphis",
    model: "KDTM404KPS",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Memphis",
    diagnosed: "Y",
    technician: "",
    customerPref: "Any",
    contact: "N",
    schedule: "06/11/26",
    status: "Data Closed",
    delay: 0,
    phone: "852.483.9540",
    redo: "N",
    aging: 16,
    calls: 1,
    partOrder: "Part Ready",
    created: "06/06/26",
    firstName: "KIMBERLY",
    lastName: "MOORE",
    address: "5602 Elm Ln",
    zip: "31901",
    state: "GA",
    email: "kimberly.moore@email.com",
    serial: "BO2351868",
    productType: "Refrigerator",
  },
  {
    ticketNo: "20647812758DF",
    warranty: "IW",
    account: "ASSURANT",
    manufacturer: "LG",
    customer: "Richard Thompson",
    city: "KNOXVILLE",
    location: "Charlotte",
    model: "MHW5630HW",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Charlotte",
    diagnosed: "N",
    technician: "Christian Newson",
    customerPref: "N",
    contact: "Sched.",
    schedule: "06/01/26",
    status: "OP-Ready for Service",
    delay: 5,
    phone: "755.677.7812",
    redo: "Y",
    aging: 26,
    calls: 6,
    partOrder: "Ordered",
    created: "05/27/26",
    firstName: "RICHARD",
    lastName: "THOMPSON",
    address: "6332 Walnut St",
    zip: "37901",
    state: "TN",
    email: "richard.thompson@email.com",
    serial: "LG6901533",
    productType: "Range",
  },
  {
    ticketNo: "1809037759-59",
    warranty: "IW",
    account: "SQUARE TRADE",
    manufacturer: "KITCHENAID",
    customer: "Ashley Lewis",
    city: "JACKSONVILLE",
    location: "Huntsville",
    model: "WRS325SDHZ",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Huntsville",
    diagnosed: "N",
    technician: "Jacob Morehouse",
    customerPref: "N",
    contact: "Sched.",
    schedule: "06/13/26",
    status: "PT-Need PreAuthorization",
    delay: 1,
    phone: "479.646.8956",
    redo: "N",
    aging: 14,
    calls: 1,
    partOrder: "Ordered",
    created: "06/08/26",
    firstName: "ASHLEY",
    lastName: "LEWIS",
    address: "8851 Oak Dr",
    zip: "32099",
    state: "FL",
    email: "ashley.lewis@email.com",
    serial: "KI1454696",
    productType: "Dryer",
  },
  {
    ticketNo: "068595163582",
    warranty: "OOW",
    account: "SQUARE TRADE",
    manufacturer: "GE",
    customer: "John Ramirez",
    city: "COLUMBUS",
    location: "Memphis",
    model: "GDF630PGMWW",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Memphis",
    diagnosed: "N",
    technician: "Sean Smith",
    customerPref: "Any",
    contact: "Y",
    schedule: "06/03/26",
    status: "CL-Ready to Complete",
    delay: 3,
    phone: "665.534.6529",
    redo: "Y",
    aging: 24,
    calls: 5,
    partOrder: "Ordered",
    created: "05/29/26",
    firstName: "JOHN",
    lastName: "RAMIREZ",
    address: "953 Elm Ave",
    zip: "31901",
    state: "GA",
    email: "john.ramirez@email.com",
    serial: "GE2151225",
    productType: "Washer",
  },
  {
    ticketNo: "SA-3790870",
    warranty: "OOW",
    account: "AIG",
    manufacturer: "AMANA",
    customer: "James Davis",
    city: "RALEIGH",
    location: "Atlanta",
    model: "FFSS2615TS",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Atlanta",
    diagnosed: "N",
    technician: "Carlos Rivera",
    customerPref: "Any",
    contact: "Y",
    schedule: "06/12/26",
    status: "OP-Waiting for Part",
    delay: 4,
    phone: "885.317.4571",
    redo: "Y",
    aging: 15,
    calls: 6,
    partOrder: "PO Made",
    created: "06/07/26",
    firstName: "JAMES",
    lastName: "DAVIS",
    address: "5196 Maple Ln",
    zip: "27601",
    state: "NC",
    email: "james.davis@email.com",
    serial: "AM1430812",
    productType: "Range",
  },
  {
    ticketNo: "25906898409DF",
    warranty: "OOW",
    account: "CENTRICITY",
    manufacturer: "LG",
    customer: "Matthew Miller",
    city: "NASHVILLE",
    location: "Jacksonville",
    model: "RF28R7351SG",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Jacksonville",
    diagnosed: "N",
    technician: "",
    customerPref: "Any",
    contact: "Y",
    schedule: "06/08/26",
    status: "OP-Ready for Service",
    delay: 4,
    phone: "323.779.1672",
    redo: "N",
    aging: 19,
    calls: 0,
    partOrder: "—",
    created: "06/03/26",
    firstName: "MATTHEW",
    lastName: "MILLER",
    address: "8131 Maple Dr",
    zip: "37201",
    state: "TN",
    email: "matthew.miller@email.com",
    serial: "LG7076506",
    productType: "Wall Oven",
  },
  {
    ticketNo: "1759466878-29",
    warranty: "OOW",
    account: "AIG",
    manufacturer: "ELECTROLUX",
    customer: "Jessica Garcia",
    city: "ST. LOUIS",
    location: "New Orleans",
    model: "LRMVS3006S",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "New Orleans",
    diagnosed: "Y",
    technician: "",
    customerPref: "AM",
    contact: "N",
    schedule: "05/24/26",
    status: "PT-Need PreAuthorization",
    delay: 3,
    phone: "676.646.5397",
    redo: "N",
    aging: 34,
    calls: 6,
    partOrder: "—",
    created: "05/19/26",
    firstName: "JESSICA",
    lastName: "GARCIA",
    address: "9436 Birch Blvd",
    zip: "63101",
    state: "MO",
    email: "jessica.garcia@email.com",
    serial: "EL1481506",
    productType: "Wall Oven",
  },
  {
    ticketNo: "056604487565",
    warranty: "EW",
    account: "ENCOMPASS",
    manufacturer: "ELECTROLUX",
    customer: "Jennifer Thomas",
    city: "RALEIGH",
    location: "Raleigh",
    model: "MHW5630HW",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Raleigh",
    diagnosed: "Y",
    technician: "Anthony Lewis",
    customerPref: "PM",
    contact: "Sched.",
    schedule: "06/10/26",
    status: "Completed",
    delay: 3,
    phone: "482.769.1166",
    redo: "N",
    aging: 17,
    calls: 4,
    partOrder: "PO Made",
    created: "06/05/26",
    firstName: "JENNIFER",
    lastName: "THOMAS",
    address: "7900 Walnut Dr",
    zip: "27601",
    state: "NC",
    email: "jennifer.thomas@email.com",
    serial: "EL1289293",
    productType: "Dryer",
  },
  {
    ticketNo: "SA-3308528",
    warranty: "OOW",
    account: "CENTRICITY",
    manufacturer: "AMANA",
    customer: "Linda Gonzalez",
    city: "BIRMINGHAM",
    location: "Asheville",
    model: "FFSS2615TS",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Asheville",
    diagnosed: "N",
    technician: "Tyler Brooks",
    customerPref: "Any",
    contact: "N",
    schedule: "05/28/26",
    status: "Completed",
    delay: 2,
    phone: "552.635.6419",
    redo: "N",
    aging: 30,
    calls: 0,
    partOrder: "PO Made",
    created: "05/23/26",
    firstName: "LINDA",
    lastName: "GONZALEZ",
    address: "5269 Maple Ct",
    zip: "35201",
    state: "AL",
    email: "linda.gonzalez@email.com",
    serial: "AM9990305",
    productType: "Refrigerator",
  },
  {
    ticketNo: "20822662216DF",
    warranty: "OOW",
    account: "GSL00002",
    manufacturer: "AMANA",
    customer: "Betty Thomas",
    city: "CHATTANOOGA",
    location: "Charlotte",
    model: "WFW9620HW",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Charlotte",
    diagnosed: "N",
    technician: "David Kim",
    customerPref: "AM",
    contact: "Sched.",
    schedule: "05/20/26",
    status: "OP-Reschedule Follow up",
    delay: 4,
    phone: "398.503.4727",
    redo: "N",
    aging: 38,
    calls: 2,
    partOrder: "Not Diagnosed",
    created: "05/15/26",
    firstName: "BETTY",
    lastName: "THOMAS",
    address: "993 Cedar Ct",
    zip: "37401",
    state: "TN",
    email: "betty.thomas@email.com",
    serial: "AM3118618",
    productType: "Wall Oven",
  },
  {
    ticketNo: "1110152642-11",
    warranty: "OOW",
    account: "ASSURANT",
    manufacturer: "BOSCH",
    customer: "Charles Martinez",
    city: "SAN ANTONIO",
    location: "Chattanooga",
    model: "GSS25GSHSS",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Chattanooga",
    diagnosed: "Y",
    technician: "Danny Thornton",
    customerPref: "AM",
    contact: "Y",
    schedule: "06/16/26",
    status: "Completed",
    delay: 1,
    phone: "689.316.2070",
    redo: "N",
    aging: 11,
    calls: 0,
    partOrder: "PO Made",
    created: "06/11/26",
    firstName: "CHARLES",
    lastName: "MARTINEZ",
    address: "2040 Birch Ln",
    zip: "78201",
    state: "TX",
    email: "charles.martinez@email.com",
    serial: "BO4786401",
    productType: "Freezer",
  },
  {
    ticketNo: "050556177902",
    warranty: "EW",
    account: "ENCOMPASS",
    manufacturer: "AMANA",
    customer: "Ashley Jackson",
    city: "JACKSONVILLE",
    location: "Asheville",
    model: "MHW5630HW",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Asheville",
    diagnosed: "N",
    technician: "Anthony Lewis",
    customerPref: "AM",
    contact: "Y",
    schedule: "06/24/26",
    status: "PT-Need PreAuthorization",
    delay: 1,
    phone: "301.981.4404",
    redo: "N",
    aging: 3,
    calls: 4,
    partOrder: "Not Diagnosed",
    created: "06/19/26",
    firstName: "ASHLEY",
    lastName: "JACKSON",
    address: "2664 Oak Dr",
    zip: "32099",
    state: "FL",
    email: "ashley.jackson@email.com",
    serial: "AM8558197",
    productType: "Wall Oven",
  },
  {
    ticketNo: "SA-3305407",
    warranty: "OOW",
    account: "SQUARE TRADE",
    manufacturer: "ELECTROLUX",
    customer: "Mary Davis",
    city: "HUNTSVILLE",
    location: "Charlotte",
    model: "GTW720BSNWS",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Charlotte",
    diagnosed: "Y",
    technician: "",
    customerPref: "PM",
    contact: "N",
    schedule: "06/23/26",
    status: "Data Closed",
    delay: 1,
    phone: "470.840.4241",
    redo: "Y",
    aging: 4,
    calls: 0,
    partOrder: "PO Made",
    created: "06/18/26",
    firstName: "MARY",
    lastName: "DAVIS",
    address: "5139 Cedar Dr",
    zip: "35801",
    state: "AL",
    email: "mary.davis@email.com",
    serial: "EL3086308",
    productType: "Wall Oven",
  },
  {
    ticketNo: "27252816758DF",
    warranty: "EW",
    account: "CENTRICITY",
    manufacturer: "KITCHENAID",
    customer: "Matthew Gonzalez",
    city: "CHATTANOOGA",
    location: "Huntsville",
    model: "GDF630PGMWW",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Huntsville",
    diagnosed: "Y",
    technician: "Marcus Webb",
    customerPref: "AM",
    contact: "Y",
    schedule: "05/30/26",
    status: "Data Closed",
    delay: 5,
    phone: "240.642.6280",
    redo: "Y",
    aging: 28,
    calls: 6,
    partOrder: "Part Ready",
    created: "05/25/26",
    firstName: "MATTHEW",
    lastName: "GONZALEZ",
    address: "9541 Oak Ave",
    zip: "37401",
    state: "TN",
    email: "matthew.gonzalez@email.com",
    serial: "KI8893693",
    productType: "Wall Oven",
  },
  {
    ticketNo: "1983625664-45",
    warranty: "IW",
    account: "AIG",
    manufacturer: "BOSCH",
    customer: "Jennifer Jackson",
    city: "JACKSONVILLE",
    location: "New Orleans",
    model: "GDT695SSJSS",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "New Orleans",
    diagnosed: "N",
    technician: "Sean Smith",
    customerPref: "N",
    contact: "N",
    schedule: "05/28/26",
    status: "OP-Ready for Service",
    delay: 5,
    phone: "541.528.2713",
    redo: "N",
    aging: 30,
    calls: 6,
    partOrder: "Ordered",
    created: "05/23/26",
    firstName: "JENNIFER",
    lastName: "JACKSON",
    address: "701 Walnut St",
    zip: "32099",
    state: "FL",
    email: "jennifer.jackson@email.com",
    serial: "BO6276722",
    productType: "Range",
  },
  {
    ticketNo: "024273352225",
    warranty: "EW",
    account: "SQUARE TRADE",
    manufacturer: "KITCHENAID",
    customer: "Anthony Gonzalez",
    city: "ST. LOUIS",
    location: "Atlanta",
    model: "GSS25GSHSS",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Atlanta",
    diagnosed: "Y",
    technician: "Danny Thornton",
    customerPref: "PM",
    contact: "N",
    schedule: "06/01/26",
    status: "Data Closed",
    delay: 4,
    phone: "730.570.9167",
    redo: "N",
    aging: 26,
    calls: 2,
    partOrder: "—",
    created: "05/27/26",
    firstName: "ANTHONY",
    lastName: "GONZALEZ",
    address: "8041 Maple St",
    zip: "63101",
    state: "MO",
    email: "anthony.gonzalez@email.com",
    serial: "KI5014745",
    productType: "Refrigerator",
  },
  {
    ticketNo: "SA-3325845",
    warranty: "EW",
    account: "GSL00002",
    manufacturer: "WHIRLPOOL",
    customer: "Karen Smith",
    city: "MOBILE",
    location: "Birmingham",
    model: "GDF630PGMWW",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Birmingham",
    diagnosed: "N",
    technician: "Jacob Morehouse",
    customerPref: "N",
    contact: "N",
    schedule: "06/20/26",
    status: "CL-Parts Back Ordered",
    delay: 3,
    phone: "863.357.9165",
    redo: "N",
    aging: 7,
    calls: 3,
    partOrder: "Ordered",
    created: "06/15/26",
    firstName: "KAREN",
    lastName: "SMITH",
    address: "2469 Birch Ave",
    zip: "36601",
    state: "AL",
    email: "karen.smith@email.com",
    serial: "WH9526867",
    productType: "Refrigerator",
  },
  {
    ticketNo: "23710967433DF",
    warranty: "IW",
    account: "ENCOMPASS",
    manufacturer: "KITCHENAID",
    customer: "David Harris",
    city: "JACKSONVILLE",
    location: "Raleigh",
    model: "GSS25GSHSS",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Raleigh",
    diagnosed: "N",
    technician: "David Kim",
    customerPref: "Any",
    contact: "N",
    schedule: "06/25/26",
    status: "CL-Ready to Complete",
    delay: 4,
    phone: "505.801.9022",
    redo: "N",
    aging: 0,
    calls: 3,
    partOrder: "Part Ready",
    created: "06/22/26",
    firstName: "DAVID",
    lastName: "HARRIS",
    address: "3190 Pine Ln",
    zip: "32099",
    state: "FL",
    email: "david.harris@email.com",
    serial: "KI7425184",
    productType: "Dishwasher",
  },
  {
    ticketNo: "1919136931-62",
    warranty: "IW",
    account: "GSL00002",
    manufacturer: "FRIGIDAIRE",
    customer: "Mary Hernandez",
    city: "SAN ANTONIO",
    location: "Charlotte",
    model: "LRMVS3006S",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Charlotte",
    diagnosed: "N",
    technician: "Jacob Morehouse",
    customerPref: "AM",
    contact: "Sched.",
    schedule: "06/18/26",
    status: "CL-Claimed",
    delay: 3,
    phone: "329.714.6439",
    redo: "Y",
    aging: 9,
    calls: 5,
    partOrder: "PO Made",
    created: "06/13/26",
    firstName: "MARY",
    lastName: "HERNANDEZ",
    address: "6817 Main St",
    zip: "78201",
    state: "TX",
    email: "mary.hernandez@email.com",
    serial: "FR8876745",
    productType: "Range",
  },
  {
    ticketNo: "093058488049",
    warranty: "IW",
    account: "ENCOMPASS",
    manufacturer: "KITCHENAID",
    customer: "Matthew Gonzalez",
    city: "NASHVILLE",
    location: "Raleigh",
    model: "WDT730PAHZ",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Raleigh",
    diagnosed: "Y",
    technician: "",
    customerPref: "PM",
    contact: "Sched.",
    schedule: "06/07/26",
    status: "CL-Claimed",
    delay: 5,
    phone: "977.699.9864",
    redo: "N",
    aging: 20,
    calls: 1,
    partOrder: "Not Diagnosed",
    created: "06/02/26",
    firstName: "MATTHEW",
    lastName: "GONZALEZ",
    address: "7210 Maple Ct",
    zip: "37201",
    state: "TN",
    email: "matthew.gonzalez@email.com",
    serial: "KI2686231",
    productType: "Wall Oven",
  },
  {
    ticketNo: "SA-3174446",
    warranty: "EW",
    account: "ASSURANT",
    manufacturer: "MAYTAG",
    customer: "Matthew Martinez",
    city: "CHARLOTTE",
    location: "Atlanta",
    model: "WRS325SDHZ",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Atlanta",
    diagnosed: "Y",
    technician: "Sean Smith",
    customerPref: "PM",
    contact: "Y",
    schedule: "06/09/26",
    status: "CSR-Assigned to ASC",
    delay: 0,
    phone: "641.349.5000",
    redo: "N",
    aging: 18,
    calls: 4,
    partOrder: "PO Made",
    created: "06/04/26",
    firstName: "MATTHEW",
    lastName: "MARTINEZ",
    address: "8253 Main Ave",
    zip: "28201",
    state: "NC",
    email: "matthew.martinez@email.com",
    serial: "MA8736811",
    productType: "Range",
  },
  {
    ticketNo: "26268807553DF",
    warranty: "EW",
    account: "ASSURANT",
    manufacturer: "KITCHENAID",
    customer: "Lisa Smith",
    city: "COLUMBUS",
    location: "Asheville",
    model: "GDF630PGMWW",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Asheville",
    diagnosed: "N",
    technician: "Jacob Morehouse",
    customerPref: "Any",
    contact: "Y",
    schedule: "06/23/26",
    status: "OP-Waiting for Part",
    delay: 3,
    phone: "801.506.7951",
    redo: "N",
    aging: 4,
    calls: 0,
    partOrder: "PO Made",
    created: "06/18/26",
    firstName: "LISA",
    lastName: "SMITH",
    address: "6348 Elm Ln",
    zip: "31901",
    state: "GA",
    email: "lisa.smith@email.com",
    serial: "KI5963914",
    productType: "Range",
  },
  {
    ticketNo: "1023557463-94",
    warranty: "EW",
    account: "SQUARE TRADE",
    manufacturer: "GE",
    customer: "Richard Rodriguez",
    city: "CHARLOTTE",
    location: "Jacksonville",
    model: "MHW5630HW",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Jacksonville",
    diagnosed: "N",
    technician: "David Kim",
    customerPref: "PM",
    contact: "Sched.",
    schedule: "05/27/26",
    status: "PT-Need PreAuthorization",
    delay: 0,
    phone: "821.560.4588",
    redo: "Y",
    aging: 31,
    calls: 2,
    partOrder: "—",
    created: "05/22/26",
    firstName: "RICHARD",
    lastName: "RODRIGUEZ",
    address: "646 Elm Ct",
    zip: "28201",
    state: "NC",
    email: "richard.rodriguez@email.com",
    serial: "GE3204724",
    productType: "Dryer",
  },
  {
    ticketNo: "052561527386",
    warranty: "OOW",
    account: "CENTRICITY",
    manufacturer: "LG",
    customer: "William White",
    city: "JACKSONVILLE",
    location: "Memphis",
    model: "NE63T8511SS",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Memphis",
    diagnosed: "N",
    technician: "Sean Smith",
    customerPref: "Any",
    contact: "Sched.",
    schedule: "05/24/26",
    status: "OP-Waiting for Part",
    delay: 2,
    phone: "713.479.3695",
    redo: "Y",
    aging: 34,
    calls: 3,
    partOrder: "Not Diagnosed",
    created: "05/19/26",
    firstName: "WILLIAM",
    lastName: "WHITE",
    address: "2406 Pine Ct",
    zip: "32099",
    state: "FL",
    email: "william.white@email.com",
    serial: "LG7667458",
    productType: "Microwave",
  },
  {
    ticketNo: "SA-3094689",
    warranty: "EW",
    account: "ENCOMPASS",
    manufacturer: "KITCHENAID",
    customer: "Sandra Gonzalez",
    city: "CHARLOTTE",
    location: "Asheville",
    model: "WRS325SDHZ",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Asheville",
    diagnosed: "N",
    technician: "Sean Smith",
    customerPref: "AM",
    contact: "Sched.",
    schedule: "05/29/26",
    status: "OP-Ready for Service",
    delay: 1,
    phone: "966.888.5295",
    redo: "N",
    aging: 29,
    calls: 0,
    partOrder: "Ordered",
    created: "05/24/26",
    firstName: "SANDRA",
    lastName: "GONZALEZ",
    address: "9298 Elm Ln",
    zip: "28201",
    state: "NC",
    email: "sandra.gonzalez@email.com",
    serial: "KI4713925",
    productType: "Dryer",
  },
  {
    ticketNo: "27306070814DF",
    warranty: "IW",
    account: "GSL00002",
    manufacturer: "GE",
    customer: "Daniel Wilson",
    city: "MEMPHIS",
    location: "Memphis",
    model: "WRS325SDHZ",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Memphis",
    diagnosed: "N",
    technician: "Jacob Morehouse",
    customerPref: "Any",
    contact: "Sched.",
    schedule: "06/08/26",
    status: "CSR-Assigned to ASC",
    delay: 5,
    phone: "299.440.9807",
    redo: "N",
    aging: 19,
    calls: 4,
    partOrder: "PO Made",
    created: "06/03/26",
    firstName: "DANIEL",
    lastName: "WILSON",
    address: "6897 Maple Dr",
    zip: "38101",
    state: "TN",
    email: "daniel.wilson@email.com",
    serial: "GE7847048",
    productType: "Range",
  },
  {
    ticketNo: "1035128844-98",
    warranty: "IW",
    account: "ASSURANT",
    manufacturer: "LG",
    customer: "Susan Miller",
    city: "COLUMBUS",
    location: "Chattanooga",
    model: "WRS325SDHZ",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Chattanooga",
    diagnosed: "N",
    technician: "",
    customerPref: "PM",
    contact: "Y",
    schedule: "06/21/26",
    status: "Completed",
    delay: 3,
    phone: "757.860.6876",
    redo: "Y",
    aging: 6,
    calls: 5,
    partOrder: "PO Made",
    created: "06/16/26",
    firstName: "SUSAN",
    lastName: "MILLER",
    address: "9883 Oak St",
    zip: "31901",
    state: "GA",
    email: "susan.miller@email.com",
    serial: "LG6595355",
    productType: "Dishwasher",
  },
  {
    ticketNo: "031426822639",
    warranty: "OOW",
    account: "SQUARE TRADE",
    manufacturer: "KITCHENAID",
    customer: "Sandra Jackson",
    city: "RALEIGH",
    location: "Nashville",
    model: "LRMVS3006S",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Nashville",
    diagnosed: "Y",
    technician: "James Okafor",
    customerPref: "PM",
    contact: "Sched.",
    schedule: "05/21/26",
    status: "CL-Parts Back Ordered",
    delay: 2,
    phone: "536.351.1046",
    redo: "N",
    aging: 37,
    calls: 0,
    partOrder: "Not Diagnosed",
    created: "05/16/26",
    firstName: "SANDRA",
    lastName: "JACKSON",
    address: "2259 Oak Blvd",
    zip: "27601",
    state: "NC",
    email: "sandra.jackson@email.com",
    serial: "KI4991829",
    productType: "Microwave",
  },
  {
    ticketNo: "SA-3016547",
    warranty: "EW",
    account: "GSL00002",
    manufacturer: "FRIGIDAIRE",
    customer: "Jennifer Rodriguez",
    city: "ATLANTA",
    location: "Memphis",
    model: "WDT730PAHZ",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Memphis",
    diagnosed: "Y",
    technician: "",
    customerPref: "N",
    contact: "Sched.",
    schedule: "06/20/26",
    status: "OP-Reschedule Follow up",
    delay: 1,
    phone: "687.659.6931",
    redo: "Y",
    aging: 7,
    calls: 5,
    partOrder: "Ordered",
    created: "06/15/26",
    firstName: "JENNIFER",
    lastName: "RODRIGUEZ",
    address: "5041 Walnut Ct",
    zip: "30301",
    state: "GA",
    email: "jennifer.rodriguez@email.com",
    serial: "FR1522621",
    productType: "Washer",
  },
  {
    ticketNo: "28583864766DF",
    warranty: "IW",
    account: "GSL00002",
    manufacturer: "WHIRLPOOL",
    customer: "Ashley Gonzalez",
    city: "JACKSONVILLE",
    location: "New Orleans",
    model: "WFW9620HW",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "New Orleans",
    diagnosed: "N",
    technician: "Marcus Webb",
    customerPref: "Any",
    contact: "N",
    schedule: "05/30/26",
    status: "Data Closed",
    delay: 4,
    phone: "529.822.3430",
    redo: "N",
    aging: 28,
    calls: 3,
    partOrder: "Ordered",
    created: "05/25/26",
    firstName: "ASHLEY",
    lastName: "GONZALEZ",
    address: "7148 Maple Ct",
    zip: "32099",
    state: "FL",
    email: "ashley.gonzalez@email.com",
    serial: "WH2919549",
    productType: "Dishwasher",
  },
  {
    ticketNo: "1461784080-67",
    warranty: "EW",
    account: "GSL00002",
    manufacturer: "BOSCH",
    customer: "Donald Davis",
    city: "JACKSONVILLE",
    location: "Raleigh",
    model: "GDF630PGMWW",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Raleigh",
    diagnosed: "N",
    technician: "",
    customerPref: "PM",
    contact: "Sched.",
    schedule: "06/01/26",
    status: "CL-Claimed",
    delay: 3,
    phone: "520.637.6120",
    redo: "Y",
    aging: 26,
    calls: 0,
    partOrder: "Not Diagnosed",
    created: "05/27/26",
    firstName: "DONALD",
    lastName: "DAVIS",
    address: "1627 Birch St",
    zip: "32099",
    state: "FL",
    email: "donald.davis@email.com",
    serial: "BO7251976",
    productType: "Refrigerator",
  },
  {
    ticketNo: "016684561411",
    warranty: "EW",
    account: "AIG",
    manufacturer: "WHIRLPOOL",
    customer: "Charles Moore",
    city: "MOBILE",
    location: "Raleigh",
    model: "GDF630PGMWW",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Raleigh",
    diagnosed: "N",
    technician: "",
    customerPref: "AM",
    contact: "Sched.",
    schedule: "06/05/26",
    status: "CL-Claimed",
    delay: 4,
    phone: "938.252.5712",
    redo: "N",
    aging: 22,
    calls: 1,
    partOrder: "—",
    created: "05/31/26",
    firstName: "CHARLES",
    lastName: "MOORE",
    address: "3774 Maple Blvd",
    zip: "36601",
    state: "AL",
    email: "charles.moore@email.com",
    serial: "WH7166651",
    productType: "Dryer",
  },
  {
    ticketNo: "SA-3799649",
    warranty: "EW",
    account: "ENCOMPASS",
    manufacturer: "FRIGIDAIRE",
    customer: "David Jackson",
    city: "BIRMINGHAM",
    location: "Dallas",
    model: "NE63T8511SS",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Dallas",
    diagnosed: "N",
    technician: "Anthony Lewis",
    customerPref: "AM",
    contact: "Y",
    schedule: "05/19/26",
    status: "OP-Reschedule Follow up",
    delay: 2,
    phone: "858.770.1430",
    redo: "N",
    aging: 39,
    calls: 2,
    partOrder: "Part Ready",
    created: "05/14/26",
    firstName: "DAVID",
    lastName: "JACKSON",
    address: "200 Main Ave",
    zip: "35201",
    state: "AL",
    email: "david.jackson@email.com",
    serial: "FR7724045",
    productType: "Dryer",
  },
  {
    ticketNo: "29199281572DF",
    warranty: "OOW",
    account: "AIG",
    manufacturer: "KITCHENAID",
    customer: "Daniel Smith",
    city: "NASHVILLE",
    location: "Charlotte",
    model: "FFSS2615TS",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Charlotte",
    diagnosed: "N",
    technician: "Christian Newson",
    customerPref: "AM",
    contact: "Y",
    schedule: "06/03/26",
    status: "CL-Parts Back Ordered",
    delay: 1,
    phone: "549.361.7062",
    redo: "N",
    aging: 24,
    calls: 6,
    partOrder: "Ordered",
    created: "05/29/26",
    firstName: "DANIEL",
    lastName: "SMITH",
    address: "915 Maple Blvd",
    zip: "37201",
    state: "TN",
    email: "daniel.smith@email.com",
    serial: "KI8434202",
    productType: "Freezer",
  },
  {
    ticketNo: "1521475287-87",
    warranty: "EW",
    account: "GSL00002",
    manufacturer: "KITCHENAID",
    customer: "Joseph Wilson",
    city: "CHATTANOOGA",
    location: "Knoxville",
    model: "KDTM404KPS",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Knoxville",
    diagnosed: "N",
    technician: "Christian Newson",
    customerPref: "AM",
    contact: "Y",
    schedule: "06/05/26",
    status: "OP-Ready for Service",
    delay: 3,
    phone: "490.894.8972",
    redo: "Y",
    aging: 22,
    calls: 0,
    partOrder: "PO Made",
    created: "05/31/26",
    firstName: "JOSEPH",
    lastName: "WILSON",
    address: "5038 Pine Ave",
    zip: "37401",
    state: "TN",
    email: "joseph.wilson@email.com",
    serial: "KI5286905",
    productType: "Range",
  },
  {
    ticketNo: "024294176674",
    warranty: "IW",
    account: "SQUARE TRADE",
    manufacturer: "SAMSUNG",
    customer: "James Thomas",
    city: "JACKSONVILLE",
    location: "Memphis",
    model: "WRS325SDHZ",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Memphis",
    diagnosed: "Y",
    technician: "",
    customerPref: "N",
    contact: "Y",
    schedule: "05/24/26",
    status: "CL-Claimed",
    delay: 3,
    phone: "712.772.6802",
    redo: "Y",
    aging: 34,
    calls: 6,
    partOrder: "Part Ready",
    created: "05/19/26",
    firstName: "JAMES",
    lastName: "THOMAS",
    address: "9533 Birch Ln",
    zip: "32099",
    state: "FL",
    email: "james.thomas@email.com",
    serial: "SA7785090",
    productType: "Freezer",
  },
  {
    ticketNo: "SA-3303578",
    warranty: "IW",
    account: "ASSURANT",
    manufacturer: "SAMSUNG",
    customer: "Patricia Gonzalez",
    city: "CHARLOTTE",
    location: "Raleigh",
    model: "WRS325SDHZ",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Raleigh",
    diagnosed: "N",
    technician: "",
    customerPref: "AM",
    contact: "N",
    schedule: "05/29/26",
    status: "PT-Need PreAuthorization",
    delay: 2,
    phone: "290.647.2734",
    redo: "N",
    aging: 29,
    calls: 1,
    partOrder: "Part Ready",
    created: "05/24/26",
    firstName: "PATRICIA",
    lastName: "GONZALEZ",
    address: "2854 Maple Ln",
    zip: "28201",
    state: "NC",
    email: "patricia.gonzalez@email.com",
    serial: "SA2913049",
    productType: "Dishwasher",
  },
  {
    ticketNo: "25795522649DF",
    warranty: "IW",
    account: "SQUARE TRADE",
    manufacturer: "WHIRLPOOL",
    customer: "Betty Clark",
    city: "KNOXVILLE",
    location: "Knoxville",
    model: "PFE28KMKES",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Knoxville",
    diagnosed: "N",
    technician: "James Okafor",
    customerPref: "N",
    contact: "Sched.",
    schedule: "06/11/26",
    status: "OP-Waiting for Part",
    delay: 4,
    phone: "816.356.2234",
    redo: "N",
    aging: 16,
    calls: 5,
    partOrder: "Ordered",
    created: "06/06/26",
    firstName: "BETTY",
    lastName: "CLARK",
    address: "5395 Elm Ave",
    zip: "37901",
    state: "TN",
    email: "betty.clark@email.com",
    serial: "WH8377995",
    productType: "Dryer",
  },
  {
    ticketNo: "1503500181-66",
    warranty: "IW",
    account: "ASSURANT",
    manufacturer: "GE",
    customer: "Daniel Martinez",
    city: "CHATTANOOGA",
    location: "Jacksonville",
    model: "GDT695SSJSS",
    internalNote: "",
    irKit: "",
    type: "SMS",
    branch: "Jacksonville",
    diagnosed: "N",
    technician: "Marcus Webb",
    customerPref: "AM",
    contact: "Sched.",
    schedule: "05/26/26",
    status: "Completed",
    delay: 0,
    phone: "672.662.1616",
    redo: "N",
    aging: 32,
    calls: 3,
    partOrder: "Ordered",
    created: "05/21/26",
    firstName: "DANIEL",
    lastName: "MARTINEZ",
    address: "9181 Oak Dr",
    zip: "37401",
    state: "TN",
    email: "daniel.martinez@email.com",
    serial: "GE4158134",
    productType: "Microwave",
  },
];

/**
 * CENTRALIZED TICKET DATA
 * Use this export in all components that need ticket data
 */
export const TICKETS: Ticket[] = RAW_TICKETS.map((ticket, index) => ({
  ...ticket,
  ticketSource: TICKET_SOURCES[index % TICKET_SOURCES.length],
}));

/**
 * Helper function to get a ticket by ticket number
 */
export function getTicketByNumber(ticketNo: string): Ticket | undefined {
  const allTickets = loadTickets();
  return allTickets.find(t => t.ticketNo === ticketNo);
}

/**
 * Helper function to get tickets by location
 */
export function getTicketsByLocation(location: string): Ticket[] {
  const allTickets = loadTickets();
  return allTickets.filter(t => t.location === location);
}

/**
 * Helper function to get tickets by status
 */
export function getTicketsByStatus(status: string): Ticket[] {
  const allTickets = loadTickets();
  return allTickets.filter(t => t.status === status);
}

/**
 * Helper function to get tickets by technician
 */
export function getTicketsByTechnician(technician: string): Ticket[] {
  const allTickets = loadTickets();
  return allTickets.filter(t => t.technician === technician);
}

/**
 * Helper function to filter tickets
 */
export function filterTickets(filters: {
  search?: string;
  status?: string;
  location?: string;
  technician?: string;
  diagnosed?: string;
}): Ticket[] {
  let filtered = loadTickets();

  if (filters.search) {
    const query = filters.search.toLowerCase();
    filtered = filtered.filter(ticket =>
      ticket.ticketNo.toLowerCase().includes(query) ||
      ticket.customer.toLowerCase().includes(query) ||
      ticket.city.toLowerCase().includes(query) ||
      ticket.phone.includes(query) ||
      ticket.model.toLowerCase().includes(query)
    );
  }

  if (filters.status) {
    filtered = filtered.filter(ticket => ticket.status === filters.status);
  }

  if (filters.location) {
    filtered = filtered.filter(ticket => ticket.location === filters.location);
  }

  if (filters.technician) {
    filtered = filtered.filter(ticket => ticket.technician === filters.technician);
  }

  if (filters.diagnosed) {
    filtered = filtered.filter(ticket => ticket.diagnosed === filters.diagnosed);
  }

  return filtered;
}

/**
 * Storage key for persisted tickets
 */
const TICKETS_STORAGE_KEY = "ahs:tickets:data";

/**
 * Load tickets from localStorage
 * Returns centralized tickets merged with any custom/modified tickets
 */
export function loadTickets(): Ticket[] {
  // Guard against SSR - return default tickets if window is not defined
  if (typeof window === "undefined" || typeof localStorage === "undefined") {
    return TICKETS;
  }
  
  try {
    const stored = localStorage.getItem(TICKETS_STORAGE_KEY);
    if (stored) {
      const savedTickets = JSON.parse(stored) as Ticket[];
      
      // Create a map of saved tickets by ticketNo for quick lookup
      const savedTicketsMap = new Map(savedTickets.map(t => [t.ticketNo, t]));
      
      // Merge: Use saved version if exists, otherwise use original
      const mergedTickets = TICKETS.map(originalTicket => {
        const savedVersion = savedTicketsMap.get(originalTicket.ticketNo);
        if (savedVersion) {
          // Remove from map so we don't add it twice
          savedTicketsMap.delete(originalTicket.ticketNo);
          return savedVersion; // Use modified version
        }
        return originalTicket; // Use original version
      });
      
      // Add any remaining custom tickets (not in original TICKETS array)
      const customTickets = Array.from(savedTicketsMap.values());
      
      // Combine: custom tickets first, then merged tickets
      const allTickets = [...customTickets, ...mergedTickets];
      
      // IMPORTANT: Deduplicate by ticketNo to prevent any duplicates
      const deduplicatedMap = new Map<string, Ticket>();
      allTickets.forEach(ticket => {
        // Keep the first occurrence (custom/modified versions come first)
        if (!deduplicatedMap.has(ticket.ticketNo)) {
          deduplicatedMap.set(ticket.ticketNo, ticket);
        }
      });
      
      return Array.from(deduplicatedMap.values());
    }
  } catch (error) {
    console.error("Error loading tickets from localStorage:", error);
  }
  return TICKETS;
}

/**
 * Save custom tickets to localStorage
 * Saves ALL tickets that have been modified from their original state
 */
export function saveCustomTickets(tickets: Ticket[]): void {
  // Guard against SSR
  if (typeof window === "undefined" || typeof localStorage === "undefined") {
    return;
  }
  
  try {
    // Get original ticket numbers for comparison
    const originalTicketNos = new Set(TICKETS.map(t => t.ticketNo));
    
    // Save tickets that are either:
    // 1. Custom tickets (not in original TICKETS array)
    // 2. Original tickets that have been modified
    const ticketsToSave = tickets.filter(t => {
      // If it's a custom ticket (not in original array), save it
      if (!originalTicketNos.has(t.ticketNo)) {
        return true;
      }
      
      // If it's an original ticket, check if it has been modified
      // We check for statusChangedAt or statusChangedBy fields which indicate modifications
      if (t.statusChangedAt || t.statusChangedBy) {
        return true;
      }
      
      return false;
    });
    
    console.log(`Saving ${ticketsToSave.length} tickets to localStorage (${tickets.length} total tickets)`, ticketsToSave.map(t => t.ticketNo));
    
    localStorage.setItem(TICKETS_STORAGE_KEY, JSON.stringify(ticketsToSave));
    
    // Trigger storage event for same-tab updates
    window.dispatchEvent(new StorageEvent("storage", {
      key: TICKETS_STORAGE_KEY,
      newValue: JSON.stringify(ticketsToSave),
      storageArea: localStorage
    }));
    
    console.log(`Tickets saved successfully to ${TICKETS_STORAGE_KEY}`);
  } catch (error) {
    console.error("Error saving tickets to localStorage:", error);
  }
}

/**
 * Generate a unique ticket number
 */
export function generateTicketNumber(): string {
  const prefix = "TK";
  const timestamp = Date.now().toString(36).toUpperCase();
  const random = Math.random().toString(36).substring(2, 5).toUpperCase();
  return `${prefix}-${timestamp}-${random}`;
}

/**
 * Create a new ticket
 * Returns the created ticket with defaults applied
 */
export function createTicket(ticketData: Partial<Ticket>): Ticket {
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-US', { month: '2-digit', day: '2-digit', year: '2-digit' }).replace(/\//g, '/');
  
  const newTicket: Ticket = {
    ticketNo: ticketData.ticketNo || generateTicketNumber(),
    ticketSource: ticketData.ticketSource || TICKET_SOURCES[0],
    warranty: ticketData.warranty || "IW",
    manufacturer: ticketData.manufacturer || "IH",
    customer: ticketData.customer || "",
    firstName: ticketData.firstName || "",
    lastName: ticketData.lastName || "",
    city: ticketData.city || "",
    location: ticketData.location || "",
    address: ticketData.address || "",
    zip: ticketData.zip || "",
    state: ticketData.state || "",
    phone: ticketData.phone || "",
    secondPhone: ticketData.secondPhone || "",
    email: ticketData.email || "",
    model: ticketData.model || "",
    serial: ticketData.serial || "",
    modelVersion: ticketData.modelVersion || "",
    productType: ticketData.productType || "",
    purchaseDate: ticketData.purchaseDate || "",
    technician: ticketData.technician || "",
    diagnosed: ticketData.diagnosed || "N",
    status: ticketData.status || "CSR-Assigned to ASC",
    schedule: ticketData.schedule || dateStr,
    internalNote: ticketData.internalNote || "",
    aging: ticketData.aging || 0,
    calls: ticketData.calls || 0,
    created: dateStr,
    redo: ticketData.redo || "N",
    partOrder: ticketData.partOrder || "Not Diagnosed",
    customerPref: ticketData.customerPref || "N",
    account: ticketData.account,
    irKit: ticketData.irKit,
    type: ticketData.type,
    branch: ticketData.branch,
    contact: ticketData.contact,
    delay: ticketData.delay,
    addressNote: ticketData.addressNote,
    fakeTicket: ticketData.fakeTicket,
    originalTicketNo: ticketData.originalTicketNo,
    callReceivedDate: ticketData.callReceivedDate,
    statusChangedAt: now.toISOString(),
    statusChangedBy: ticketData.statusChangedBy,
  };

  console.log("Created ticket object:", newTicket);
  console.log("Product Type value:", newTicket.productType);

  return newTicket;
}

/**
 * Add a new ticket to the system
 * Saves to localStorage and returns all tickets including the new one
 */
export function addTicket(ticketData: Partial<Ticket>): Ticket[] {
  const newTicket = createTicket(ticketData);
  console.log("Adding new ticket:", newTicket.ticketNo, newTicket);
  
  const currentTickets = loadTickets();
  console.log("Current tickets before adding:", currentTickets.length);
  
  const updatedTickets = [newTicket, ...currentTickets];
  console.log("Updated tickets after adding:", updatedTickets.length);
  
  saveCustomTickets(updatedTickets);
  
  return updatedTickets;
}

/**
 * Update an existing ticket
 * Returns updated tickets array
 */
export function updateTicket(ticketNo: string, updates: Partial<Ticket>): Ticket[] {
  const currentTickets = loadTickets();
  const updatedTickets = currentTickets.map(ticket => {
    if (ticket.ticketNo === ticketNo) {
      return {
        ...ticket,
        ...updates,
        statusChangedAt: new Date().toISOString(),
      };
    }
    return ticket;
  });
  
  saveCustomTickets(updatedTickets);
  
  return updatedTickets;
}

/**
 * Delete a ticket
 * Returns updated tickets array
 */
export function deleteTicket(ticketNo: string): Ticket[] {
  const currentTickets = loadTickets();
  const updatedTickets = currentTickets.filter(ticket => ticket.ticketNo !== ticketNo);
  
  saveCustomTickets(updatedTickets);
  
  return updatedTickets;
}

/**
 * Clear all custom tickets (reset to original data)
 */
export function clearCustomTickets(): void {
  // Guard against SSR
  if (typeof window === "undefined" || typeof localStorage === "undefined") {
    return;
  }
  
  try {
    localStorage.removeItem(TICKETS_STORAGE_KEY);
  } catch (error) {
    console.error("Error clearing custom tickets:", error);
  }
}


/**
 * Update ticket visits
 * Saves visits array to the ticket in centralized system
 */
export function updateTicketVisits(ticketNo: string, visits: Ticket['visits']): Ticket[] {
  const currentTickets = loadTickets();
  const updatedTickets = currentTickets.map(ticket => {
    if (ticket.ticketNo === ticketNo) {
      return {
        ...ticket,
        visits: visits || [],
        statusChangedAt: new Date().toISOString(),
      };
    }
    return ticket;
  });
  
  saveCustomTickets(updatedTickets);
  console.log(`Updated visits for ticket ${ticketNo}:`, visits);
  
  return updatedTickets;
}

/**
 * Update ticket parts
 * Saves parts array to the ticket in centralized system
 */
export function updateTicketParts(ticketNo: string, parts: Ticket['parts']): Ticket[] {
  const currentTickets = loadTickets();
  const updatedTickets = currentTickets.map(ticket => {
    if (ticket.ticketNo === ticketNo) {
      return {
        ...ticket,
        parts: parts || [],
        statusChangedAt: new Date().toISOString(),
      };
    }
    return ticket;
  });
  
  saveCustomTickets(updatedTickets);
  console.log(`Updated parts for ticket ${ticketNo}:`, parts);
  
  return updatedTickets;
}

/**
 * Get ticket visits
 */
export function getTicketVisits(ticketNo: string): Ticket['visits'] {
  const ticket = getTicketByNumber(ticketNo);
  return ticket?.visits || [];
}

/**
 * Get ticket parts
 */
export function getTicketParts(ticketNo: string): Ticket['parts'] {
  const ticket = getTicketByNumber(ticketNo);
  return ticket?.parts || [];
}
