/**
 * Technician mileage log (migration 0138) — a manual entry log, PLUS
 * (migration 0141) an optional auto-sync path that derives entries from
 * every ticket assigned to a technician, regardless of status. Manual
 * entries are typed in directly;
 * auto-synced ones (source: "auto") are generated by syncMileageFromTickets
 * below, reusing the same office-to-customer distance calculator already
 * used on the ticket detail page (mapEngine.ts's computeOfficeDistanceMiles)
 * rather than any new mileage math. Edited on Accounting Dashboard's
 * Mileage tab.
 */

import { supabase } from "./client";
import { getCompanyMapProvider } from "./companySettings";
import { computeDailyRouteMiles, getOfficeCoordinates, getElectroluxHuntsvilleMileageOrigin, type MileageTicketInput, type DailyRouteMilesResult } from "@/lib/mapEngine";

export interface MileageEntry {
  id: string;
  /** Null when this entry was auto-synced for a technician name that
   *  matched no real profile — see technicianName and migration 0142. */
  profileId: string | null;
  /** Raw ticket technician text, set only when profileId is null — the
   *  display fallback for an unmatched auto-synced entry. Manual entries
   *  (which always require picking a real profile) never set this. */
  technicianName: string | null;
  branch: string;
  workDate: string;
  address: string;
  contactNumber: string | null;
  email: string | null;
  totalMileage: number;
  googleMapLink: string | null;
  createdByName: string | null;
  createdAt: string;
  ticketId: string | null;
  /** Human-readable ticket number, set only on auto-synced entries — see migration 0143. */
  ticketNo: string | null;
  /** The ticket's status AT SYNC TIME — a snapshot, not live; see migration 0147. */
  ticketStatus: string | null;
  source: "manual" | "auto";
  /** Payroll override set via the On Hold action — see migration 0148 and
   *  setMileageEntryPayrollExcluded. While true, this ticket never counts
   *  toward the technician's "Completed Tickets" pay, even if its status
   *  later becomes completed. Reversible — toggling it back off restores
   *  normal pay counting. */
  payrollExcluded: boolean;
  payrollExcludedAt: string | null;
  payrollExcludedByName: string | null;
  /** "manual" (Mileage tab's On Hold button) or "no_photos" (automatic — see
   *  reconcileMileageNoPhotoHolds). Null when not excluded. Lets the
   *  automatic rule know never to touch a human's manual hold, and lets a
   *  human's "take it off hold" always win even with no photo. Migration 0177. */
  payrollHoldReason: "manual" | "no_photos" | null;
  /** This day's manually-set stop sequence (0-based, shared meaning across
   *  every entry in the same technician+work_date group) — see
   *  recalculateMileageDayRoute. Null means "use the automatic time-slot/
   *  created-at heuristic in syncMileageFromTickets" — including after a
   *  fresh ticket joins an already-manually-ordered day, which resets the
   *  whole group back to null/heuristic rather than guessing where the new
   *  stop belongs. Migration 0182. */
  routeOrder: number | null;
  /** Whether this day's route ends at the technician's home address or
   *  loops back to the branch — see recalculateMileageDayRoute. Null means
   *  "automatic default" (home if one's on file, branch otherwise — the
   *  same fallback computeDailyRouteMiles already applied before this
   *  field existed). Resets to null under the same new-ticket-joins-the-day
   *  rule as routeOrder. Migration 0183. */
  routeReturnTo: "home" | "branch" | null;
  /** Full replacement for this day's total, if Finance has set one — see
   *  mileageEffectiveTotal and setMileageDayAdjustment. Takes precedence
   *  over mileageAdjustment when both are set. Migration 0182. */
  mileageOverride: number | null;
  /** A +/- delta added to totalMileage (ignored when mileageOverride is
   *  set) — see mileageEffectiveTotal. Migration 0182. */
  mileageAdjustment: number | null;
  adjustmentNote: string | null;
  adjustedByName: string | null;
  adjustedAt: string | null;
  /** When payrollExcluded last flipped true -> false — the opposite of
   *  payrollExcludedAt, which release always nulls out. Lets the mobile "On
   *  Hold Tickets" screen's Updated sub-tab show what recently cleared,
   *  since payrollExcludedAt/payrollHoldReason no longer carry that once a
   *  hold is released. Cleared again if the entry is ever re-held.
   *  Migration 0186. */
  payrollReleasedAt: string | null;
  /** Soft-delete (migration 0210) — for a stop the technician never
   *  actually made (customer cancelled, couldn't get there, etc.), so it
   *  needs to come OUT of the day's route and mileage total entirely.
   *  Different from payrollExcluded ("On Hold"), which is for a stop the
   *  technician DID drive to but that shouldn't count for payroll yet —
   *  On Hold stays in the route; deletedAt removes it. The row itself
   *  stays in place either way (still visible in the Mileage tab table,
   *  its Payroll status reads "Deleted"). See softDeleteMileageEntry.
   *  Reversible via restoreMileageEntry. */
  deletedAt: string | null;
  deletedByName: string | null;
  deleteReason: string | null;
  /** This ticket's OWN leg of the day's route — distance from the previous
   *  stop (or the branch, for the day's first stop) to this one, and ONLY
   *  that leg (see homeLegMileage below, migration 0237, for the day's final
   *  drive home — never folded in here). Purely a display breakdown of
   *  totalMileage/mileageEffectiveTotal (which stays the shared day total
   *  payroll reads, unaffected by this) — summing every entry's legMileage
   *  PLUS homeLegMileage for one day reconstructs that same day total. Null
   *  for manual entries (no route/stop-order concept), a stop that failed
   *  to geocode, or a row not yet recalculated since migration 0211.
   *  Computed in syncMileageFromTickets/recalculateMileageDayRoute via
   *  computeDailyRouteMiles's legMiles (mapEngine.ts). */
  legMileage: number | null;
  /** The day's final "drive home" (or back-to-branch) distance — set ONLY
   *  on the day's actual last stop's row, null on every earlier stop.
   *  Migration 0237: previously this was silently folded into that last
   *  stop's own legMileage, which made a ticket that just happened to be
   *  scheduled last read as an inflated/wrong leg (confirmed live: a real
   *  7.5 mi leg showing as 43.6 mi with a 36.1 mi commute home baked in).
   *  Kept separate so a ticket's own Mileage column always means just its
   *  own drive there. */
  homeLegMileage: number | null;
  /** Free-text, admin-editable, no formula/source feeds it — Ticket
   *  Attendance's "Estimate Time" column (migration 0213). Not derived
   *  from anything else in the app; set via setMileageEstimateTime. */
  estimateTime: string | null;
}

/**
 * The number that actually counts for display and payroll — a manual
 * override replaces the calculated total_mileage outright; a manual
 * adjustment adds/subtracts from it; with neither set, it's just the
 * calculated total. EVERY read of a day's mileage figure (the Mileage
 * table, the technician detail modal, getTechAutoMileageTotals) must go
 * through this rather than entry.totalMileage directly, or a Finance
 * correction silently won't take effect.
 */
export function mileageEffectiveTotal(entry: Pick<MileageEntry, "totalMileage" | "mileageOverride" | "mileageAdjustment">): number {
  if (entry.mileageOverride != null) return entry.mileageOverride;
  return entry.totalMileage + (entry.mileageAdjustment ?? 0);
}

function mapRow(r: any): MileageEntry {
  return {
    id: r.id,
    profileId: r.profile_id ?? null,
    technicianName: r.technician_name ?? null,
    branch: r.branch,
    workDate: r.work_date,
    address: r.address,
    contactNumber: r.contact_number ?? null,
    email: r.email ?? null,
    totalMileage: Number(r.total_mileage) || 0,
    googleMapLink: r.google_map_link ?? null,
    createdByName: r.created_by_name ?? null,
    createdAt: r.created_at,
    ticketId: r.ticket_id ?? null,
    ticketNo: r.ticket_no ?? null,
    ticketStatus: r.ticket_status ?? null,
    source: r.source === "auto" ? "auto" : "manual",
    payrollExcluded: !!r.payroll_excluded,
    payrollExcludedAt: r.payroll_excluded_at ?? null,
    payrollExcludedByName: r.payroll_excluded_by_name ?? null,
    payrollHoldReason: r.payroll_hold_reason === "manual" || r.payroll_hold_reason === "no_photos" ? r.payroll_hold_reason : null,
    routeOrder: r.route_order ?? null,
    routeReturnTo: r.route_return_to === "home" || r.route_return_to === "branch" ? r.route_return_to : null,
    mileageOverride: r.mileage_override != null ? Number(r.mileage_override) : null,
    mileageAdjustment: r.mileage_adjustment != null ? Number(r.mileage_adjustment) : null,
    adjustmentNote: r.adjustment_note ?? null,
    adjustedByName: r.adjusted_by_name ?? null,
    adjustedAt: r.adjusted_at ?? null,
    payrollReleasedAt: r.payroll_released_at ?? null,
    deletedAt: r.deleted_at ?? null,
    deletedByName: r.deleted_by_name ?? null,
    deleteReason: r.delete_reason ?? null,
    legMileage: r.leg_mileage != null ? Number(r.leg_mileage) : null,
    homeLegMileage: r.home_leg_mileage != null ? Number(r.home_leg_mileage) : null,
    estimateTime: r.estimate_time ?? null,
  };
}

const ENTRY_COLUMNS =
  "id, profile_id, technician_name, branch, work_date, address, contact_number, email, total_mileage, google_map_link, created_by_name, created_at, ticket_id, ticket_no, ticket_status, source, payroll_excluded, payroll_excluded_at, payroll_excluded_by_name, payroll_hold_reason, route_order, route_return_to, mileage_override, mileage_adjustment, adjustment_note, adjusted_by_name, adjusted_at, payroll_released_at, deleted_at, deleted_by_name, delete_reason, leg_mileage, home_leg_mileage, estimate_time";

// Supabase caps an unbounded select at 1000 rows — mileage_entries is
// queried all-time, no date range. Page through in chunks of 1000 instead.
const PAGE_SIZE = 1000;

/**
 * All mileage entries for the caller's company (RLS-scoped), newest first.
 *
 * work_date alone isn't a unique sort key — plenty of rows share the same
 * date — so range()-based paging on it alone lets Postgres resolve ties
 * differently across the two separate page queries, silently duplicating
 * some rows and dropping others across the page boundary (confirmed live:
 * 52 duplicated + 52 different rows missing out of 2,603 real rows once the
 * table grew past PAGE_SIZE). id as a secondary sort key makes the order
 * — and therefore the paging — deterministic. Same fix already applied to
 * getCompanyTickets() in tickets.ts for the identical reason.
 */
/**
 * @param branch When given, filters server-side to just that branch (an
 *  `.eq("branch", branch)` on the query below) — used by AccountingDashboard's
 *  Mileage tab so opening it doesn't have to pull every branch's entries just
 *  to display one. Omit for the full company (still used by the background
 *  no-photos payroll-hold reconciliation and the mileage report/CSV export,
 *  which both need every branch regardless of what's on screen).
 */
export async function getMileageEntries(branch?: string): Promise<MileageEntry[]> {
  const all: MileageEntry[] = [];
  for (let from = 0; ; from += PAGE_SIZE) {
    let query = supabase
      .from("mileage_entries")
      .select(ENTRY_COLUMNS)
      .order("work_date", { ascending: false })
      .order("id", { ascending: true });
    if (branch) query = query.eq("branch", branch);
    const { data, error } = await query.range(from, from + PAGE_SIZE - 1);
    if (error) {
      console.error("getMileageEntries error:", error.message);
      return all;
    }
    all.push(...(data ?? []).map(mapRow));
    if (!data || data.length < PAGE_SIZE) break;
  }
  return all;
}

/**
 * Toggles the "don't pay for this ticket while on hold" override — see
 * MileageEntry.payrollExcluded. Reversible: un-excluding just clears the
 * flag; it doesn't need to restore anything else, since the exclusion is
 * checked live by getTechCompletedRepairCounts, not baked into a stored pay
 * amount anywhere.
 */
export async function setMileageEntryPayrollExcluded(
  id: string,
  excluded: boolean,
  excludedByProfileId: string | null,
  excludedByName: string | null
): Promise<void> {
  const { error } = await supabase
    .from("mileage_entries")
    .update({
      payroll_excluded: excluded,
      payroll_excluded_at: excluded ? new Date().toISOString() : null,
      payroll_excluded_by: excluded ? excludedByProfileId : null,
      payroll_excluded_by_name: excluded ? excludedByName : null,
      // Manual always wins — a human explicitly deciding "off" should never
      // get silently re-held by the automatic no-photos rule afterward.
      payroll_hold_reason: excluded ? "manual" : null,
      // Opposite of payroll_excluded_at — stamped on release, cleared on
      // re-hold (see MileageEntry.payrollReleasedAt).
      payroll_released_at: excluded ? null : new Date().toISOString(),
    })
    .eq("id", id);
  if (error) throw new Error(error.message);
  await reassignHomeLegForDay(id).catch((err) => console.error("reassignHomeLegForDay failed:", err));
}

/**
 * Keeps a day's drive-home leg (migration 0221's home_leg_mileage) attributed
 * to whichever ticket is currently the LAST non-excluded stop, called after
 * every manual On Hold toggle (setMileageEntryPayrollExcluded above — NOT
 * the automatic no-photos hold, which means "not yet verified," not "this
 * wasn't really a stop"). A technician physically checking in/out on a
 * ticket that Finance then decides not to pay for (e.g. it turned out to be
 * a reschedule) shouldn't also get credited with driving home FROM there if
 * a real, still-counted ticket comes right before it — the drive home
 * belongs on whichever ticket Finance still recognizes as the actual last
 * stop. Moves ONLY the home_leg_mileage value between rows — every ticket's
 * own leg_mileage (including the excluded one's) stays exactly as computed,
 * since the exclusion doesn't erase the drive itself, only Finance's
 * willingness to pay for that one ticket. Self-correcting either direction:
 * excluding the current holder moves the leg backward to the next real
 * stop; releasing a hold can move it forward again if that ticket is once
 * more the last non-excluded one. No-ops if this day's stop order was never
 * confirmed (route_order still null) — nothing to reassign against without
 * a real sequence.
 */
async function reassignHomeLegForDay(toggledEntryId: string): Promise<void> {
  const { data: toggled, error: toggledErr } = await supabase
    .from("mileage_entries")
    .select("work_date, profile_id, technician_name")
    .eq("id", toggledEntryId)
    .maybeSingle();
  if (toggledErr || !toggled?.work_date) return;

  let query = supabase
    .from("mileage_entries")
    .select("id, route_order, home_leg_mileage, payroll_excluded")
    .eq("source", "auto")
    .eq("work_date", toggled.work_date)
    .is("deleted_at", null);
  query = toggled.profile_id ? query.eq("profile_id", toggled.profile_id) : query.eq("technician_name", toggled.technician_name);
  const { data: dayRows, error: dayErr } = await query;
  if (dayErr || !dayRows || dayRows.length === 0) return;

  const ordered = dayRows.filter((r) => r.route_order != null).sort((a, b) => (a.route_order as number) - (b.route_order as number));
  if (ordered.length === 0) return;

  const currentHolder = dayRows.find((r) => r.home_leg_mileage != null);
  const homeLegValue = currentHolder?.home_leg_mileage;
  if (homeLegValue == null) return;

  const newHolder = [...ordered].reverse().find((r) => !r.payroll_excluded);
  if (!newHolder || newHolder.id === currentHolder?.id) return;

  await supabase.from("mileage_entries").update({ home_leg_mileage: null }).eq("id", currentHolder!.id);
  await supabase.from("mileage_entries").update({ home_leg_mileage: homeLegValue }).eq("id", newHolder.id);
}

/**
 * Applies the "no photos uploaded yet → hold this ticket's pay" rule —
 * called from Accounting Dashboard's Mileage tab once its batch photo
 * check (hasTicketPhotos, storage.ts) resolves for a set of entries.
 * Never touches a row whose payroll_hold_reason is "manual" — that's a
 * human's call, not this rule's to make or unmake. Silent (no
 * notifications) since this can fire many times as photos trickle in;
 * the manual toggle's own notification flow stays exactly as it was.
 * Returns how many rows actually changed, for a status message.
 */
export async function reconcileMileageNoPhotoHolds(
  entries: { id: string; payrollExcluded: boolean; payrollHoldReason: "manual" | "no_photos" | null }[],
  hasPhotosByEntryId: Map<string, boolean>
): Promise<number> {
  let changed = 0;
  for (const entry of entries) {
    if (entry.payrollHoldReason === "manual") continue;
    const hasPhotos = hasPhotosByEntryId.get(entry.id);
    if (hasPhotos === undefined) continue;
    const shouldHold = !hasPhotos;
    const isCurrentlyAutoHeld = entry.payrollExcluded && entry.payrollHoldReason === "no_photos";
    if (shouldHold === isCurrentlyAutoHeld) continue;
    const { error } = await supabase
      .from("mileage_entries")
      .update({
        payroll_excluded: shouldHold,
        payroll_excluded_at: shouldHold ? new Date().toISOString() : null,
        payroll_excluded_by: null,
        payroll_excluded_by_name: shouldHold ? "Auto (no photos)" : null,
        payroll_hold_reason: shouldHold ? "no_photos" : null,
        payroll_released_at: shouldHold ? null : new Date().toISOString(),
      })
      .eq("id", entry.id);
    if (error) console.error(`reconcileMileageNoPhotoHolds (${entry.id}):`, error.message);
    else changed++;
  }
  return changed;
}

/**
 * Soft-deletes a mileage entry — see MileageEntry.deletedAt. The row stays
 * in place; getMileageEntries still returns it (so the Mileage tab can
 * keep showing it with a "Deleted" badge and a way to restore it), but
 * mileageDayRoute-style consumers should filter deletedAt out before
 * summing totals or building a route. Requires a reason, shown in the
 * audit trail the same way an adjustment note already is.
 */
export async function softDeleteMileageEntry(
  id: string,
  reason: string,
  deletedByProfileId: string | null,
  deletedByName: string | null
): Promise<void> {
  const { error } = await supabase
    .from("mileage_entries")
    .update({
      deleted_at: new Date().toISOString(),
      deleted_by: deletedByProfileId,
      deleted_by_name: deletedByName,
      delete_reason: reason.trim() || null,
    })
    .eq("id", id);
  if (error) throw new Error(error.message);
}

/** Reverses softDeleteMileageEntry — clears every deletion field, restoring the row to normal. */
export async function restoreMileageEntry(id: string): Promise<void> {
  const { error } = await supabase
    .from("mileage_entries")
    .update({ deleted_at: null, deleted_by: null, deleted_by_name: null, delete_reason: null })
    .eq("id", id);
  if (error) throw new Error(error.message);
}

/** Sets (or clears, on an empty string) a mileage entry's Estimate Time — see MileageEntry.estimateTime. Plain free text, no validation. */
export async function setMileageEstimateTime(id: string, value: string): Promise<void> {
  const { error } = await supabase
    .from("mileage_entries")
    .update({ estimate_time: value.trim() || null })
    .eq("id", id);
  if (error) throw new Error(error.message);
}

/**
 * Overrides one ticket's own leg mileage (the per-stop breakdown figure —
 * see MileageEntry.legMileage), used by the Office Payroll review modal's
 * per-ticket mileage cell. `null` on an empty string restores the
 * auto-computed value on the next sync. Purely the display breakdown: the
 * day route total (total_mileage / mileageEffectiveTotal) that tech
 * mileage-pay reads is untouched.
 */
export async function setMileageLegMileage(id: string, value: number | null): Promise<void> {
  const { error } = await supabase
    .from("mileage_entries")
    .update({ leg_mileage: value == null || Number.isNaN(value) ? null : Math.round(value * 10) / 10 })
    .eq("id", id);
  if (error) throw new Error(error.message);
}

/**
 * Invalidates this one ticket's route-order confirmation so the NEXT mileage
 * sync re-examines its whole day, instead of skipping it as already settled.
 * Call this whenever a ticket's onsite_arrived_at/onsite_done_at changes
 * through a path other than the mobile check-in buttons themselves (which
 * feed syncMileageFromTickets/getTechCompletedRepairCounts fine on their
 * own) — right now that's exactly one caller: approving a Ticket Time
 * Dispute (AccountingDashboard.tsx's handleTicketTimeDisputeAction), which
 * writes a corrected arrived/done time straight onto the ticket without
 * anything else telling the mileage side its day changed.
 *
 * Without this, hasUnconfirmedArrivalOrder (syncMileageFromTickets) never
 * re-fires for that day once route_order is already set from an earlier
 * sync — the dispute's corrected time would sit there forever with the
 * day's stop order/drive-home leg still chained against the OLD (wrong or
 * missing) timestamp. Nulling route_order here is exactly what makes that
 * check pick the day back up.
 *
 * A no-op if this ticket has no auto-synced mileage_entries row yet (its
 * very first sync will compute a fresh, already-correct order anyway).
 */
export async function resetMileageRouteConfirmation(ticketNo: string): Promise<void> {
  const { error } = await supabase
    .from("mileage_entries")
    .update({ route_order: null, home_leg_mileage: null })
    .eq("ticket_no", ticketNo)
    .eq("source", "auto");
  if (error) throw new Error(error.message);
}

/**
 * Coarse visit-order heuristic, shared by syncMileageFromTickets (below)
 * and the Day Route view: a time_slot's own leading number as its start
 * hour (e.g. "8-12" -> 8, "1-5" -> 1) — AM/PM isn't recorded, but this is
 * only used for RELATIVE ordering within one technician's one day, not an
 * absolute time, so the ambiguity doesn't matter here. A bare "AM"/"PM"
 * slot (no digits at all — seen in real ticket data alongside the numeric
 * ranges) sorts before/after every numeric range rather than at a specific
 * hour that could tie with (and then get arbitrarily reordered against) a
 * real numeric slot like "12-4". Missing/unparsable slots sort last of all.
 */
export function timeSlotStartHour(slot: unknown): number {
  const raw = String(slot || "").trim().toUpperCase();
  if (!raw) return Number.MAX_SAFE_INTEGER;
  if (raw === "AM") return -1;
  if (raw === "PM") return 13;
  const m = raw.match(/(\d{1,2})/);
  return m ? Number(m[1]) : Number.MAX_SAFE_INTEGER;
}

/**
 * Orders a day's stops by the technician's REAL visit order when it's known
 * — the on-site check-in "Arrived" timestamp (mobile app, migration 0202),
 * the same signal EmployeePayrollDetailModal's per-day ticket breakdown
 * sorts by. Falls back to timeSlotStartHour + created_at (the original
 * heuristic — ticket row creation order, NOT visit order) for any stop with
 * no arrival stamp yet, e.g. a day synced before the technician actually
 * drove it. Without this, a cluster of same-time-slot stops (very common —
 * most tickets just say "AM"/"PM" or a broad "12-5" window) fell back
 * entirely to created_at, an order with no relationship to the technician's
 * actual route; leg_mileage then chained stop N to whichever stop happened
 * to sync into the database first, not whichever stop N-1 actually was —
 * confirmed live on a Columbus, GA day where stop 5's leg came out ~2.5x the
 * real Google Maps distance from its true previous stop.
 *
 * An arrived stop sorts by its real clock time; an unarrived one sorts by
 * its nominal slot start hour on its own schedule_date, so the two scales
 * line up sensibly side by side instead of every heuristic-only stop
 * collapsing to before/after every real arrival regardless of time of day.
 */
export function sortStopsByHeuristic<
  T extends { time_slot?: unknown; created_at: string; onsite_arrived_at?: string | null; schedule_date?: string | null }
>(tickets: T[]): T[] {
  const sortKey = (t: T): number => {
    const arrived = t.onsite_arrived_at ? new Date(t.onsite_arrived_at).getTime() : NaN;
    if (Number.isFinite(arrived)) return arrived;
    const dayMs = t.schedule_date ? new Date(`${t.schedule_date}T00:00:00`).getTime() : NaN;
    const hour = timeSlotStartHour(t.time_slot);
    if (Number.isFinite(dayMs) && hour !== Number.MAX_SAFE_INTEGER) return dayMs + hour * 3600_000;
    return Number.MAX_SAFE_INTEGER; // no day/slot to anchor on either — push to the end, tie-broken by created_at below.
  };
  return [...tickets].sort((a, b) => {
    const diff = sortKey(a) - sortKey(b);
    if (diff !== 0) return diff;
    return String(a.created_at).localeCompare(String(b.created_at));
  });
}

/** One stop in a technician's day route — Day Route view's stop list/map. */
export interface MileageDayStop {
  ticketId: string;
  ticketNo: string;
  status: string | null;
  timeSlot: string | null;
  address: string;
  city: string | null;
  state: string | null;
  zip: string | null;
}

/**
 * Fetches this day's stops in visit order — the saved route_order if every
 * entry has one (a human has already sequenced this day), else the same
 * time-slot heuristic syncMileageFromTickets uses. Used to seed the Day
 * Route view's map/list before any reordering happens.
 */
export async function getMileageDayRouteStops(
  entries: { ticketId: string | null; routeOrder: number | null }[]
): Promise<MileageDayStop[]> {
  const ticketIds = entries.map((e) => e.ticketId).filter((id): id is string => !!id);
  if (ticketIds.length === 0) return [];
  const { data, error } = await supabase
    .from("tickets")
    .select("id, ticket_no, status, time_slot, created_at, schedule_date, onsite_arrived_at, customer:customers ( address, city, state, zip )")
    .in("id", ticketIds);
  if (error) throw new Error(error.message);
  const rows = (data ?? []) as any[];
  const allHaveOrder = entries.every((e) => e.routeOrder != null);
  const orderIndex = new Map(entries.map((e) => [e.ticketId, e.routeOrder]));
  const ordered = allHaveOrder
    ? [...rows].sort((a, b) => (orderIndex.get(a.id) ?? 0) - (orderIndex.get(b.id) ?? 0))
    : sortStopsByHeuristic(rows);
  return ordered.map((t: any) => {
    const customer = t.customer ?? {};
    return {
      ticketId: t.id,
      ticketNo: t.ticket_no,
      status: t.status ?? null,
      timeSlot: t.time_slot ?? null,
      address: customer.address ?? "",
      city: customer.city ?? null,
      state: customer.state ?? null,
      zip: customer.zip ?? null,
    };
  });
}

export interface MileageSyncResult {
  created: number;
  skipped: number;
  errors: string[];
  /** Tickets whose technician text didn't match ANY technician passed in —
   *  even after trim/lowercase. These still get synced (as profile_id:
   *  null, technician_name: the raw ticket text — see migration 0142),
   *  just surfaced separately so a real name mismatch is visible and
   *  fixable (e.g. fix that person's Display Name, or their role, so a
   *  future sync links their tickets to a real profile) instead of
   *  looking identical to any other synced entry. */
  unmatchedTechnicians: { name: string; count: number }[];
  /** How many technician-days actually got (re)processed this run — new
   *  tickets, moved tickets, and days recalculated purely to backfill
   *  leg_mileage or fix a stale (no-origin) Map Link (see the
   *  hasMissingLegMileage/hasStaleMapLink checks above). A run that only
   *  backfills existing days has `created === 0` but this is still
   *  > 0 — callers should refetch/refresh on this, not just on `created`. */
  recalculatedDays: number;
  /** True if `signal` was aborted before every day finished — everything
   *  counted above still genuinely happened/saved, this just means the run
   *  didn't reach the end of groupsToProcess. Re-running later (or clicking
   *  Sync again) picks up exactly where it left off — an unprocessed day
   *  still looks unprocessed, nothing was left half-written. */
  stopped: boolean;
}

/**
 * Auto-generates mileage entries from EVERY ticket assigned to a
 * technician — not just completed ones, since a drive happened regardless
 * of whether the job finished, is still open, or got cancelled after the
 * tech arrived. Still one row per ticket (so each ticket keeps its own
 * Photos/Hold/Send-message/link), but the total_mileage VALUE on every
 * ticket a technician had on a given day is the SAME number: that day's
 * full driving route — branch -> stop 1 -> stop 2 -> ... -> stop N -> home
 * address (or back to the branch if none on file) — not each ticket's own
 * independent distance from the branch. Stops within a day are ordered by
 * time_slot (then ticket creation time as a tiebreaker) since there's no
 * exact visit-sequence data to do better than that. See
 * computeDailyRouteMiles (mapEngine.ts) for the actual route math.
 *
 * Always all-time, no date range — every ticket this company has ever
 * logged. Safe to re-run: a day whose every ticket already has a row is
 * skipped entirely (no new API calls). A day where a NEW ticket joins
 * an already-partially-synced day gets its whole route recomputed and
 * EVERY ticket that day (new and pre-existing) is updated to the fresh
 * total — the route changed, so the old number on the earlier tickets is
 * now stale. Tickets with no schedule_date are skipped too
 * (mileage_entries.work_date is required — there's no date to log the
 * drive under).
 *
 * Matches tickets to technicians by NAME, case/whitespace-insensitive — same
 * convention as every other free-text technician match in this app (e.g.
 * AccountingDashboard.tsx's own Tech Payroll employeeByName resolution,
 * resolveTeamLeadOrManager's manager_name match). A ticket whose technician
 * text matches no known technician (wrong/legacy Display Name, or no User
 * Management account at all) still gets synced — profile_id: null,
 * technician_name: the raw ticket text (migration 0142) — rather than
 * silently dropped, so mileage isn't lost just because nobody's fixed that
 * person's profile yet. It's surfaced via unmatchedTechnicians either way.
 * Each unmatched name's tickets are still grouped/routed by day the same
 * way a matched technician's are — just keyed by their raw ticket text
 * instead of a profileId.
 */
// Module-level (not per-caller) in-flight guard. Two overlapping runs used
// to both snapshot "which tickets already have a mileage_entries row"
// before either had written anything, then both attempt the same INSERT —
// the DB's unique index (idx_mileage_entries_ticket_dedup) correctly
// rejects the second with a 409/23505 (already caught below as a no-op
// skip), but the raw failed request still shows up in the browser console/
// network panel, which is what actually prompted this guard. The most
// common trigger isn't two genuinely different sync requests — it's
// AccountingDashboard.tsx's "auto-sync when the Mileage tab opens" effect
// firing twice for the same page load (e.g. React StrictMode's deliberate
// dev-only double-effect-invoke, or the component remounting while an
// earlier run's async work is still in flight and un-cancellable). A
// second call while one is already running just returns immediately
// instead of starting a competing pass.
let syncInFlight = false;

type MapLinkTicket = {
  location?: string | null;
  account?: string | null;
  customer?: { address?: string | null; address2?: string | null; city?: string | null; state?: string | null; zip?: string | null } | null;
};

/** Full "street, city, state zip" string for a ticket's customer job site; "" when nothing usable is on file. */
function ticketSiteAddress(ticket: MapLinkTicket): string {
  const customer = ticket.customer ?? {};
  return [customer.address, customer.address2, [customer.city, customer.state].filter(Boolean).join(", "), customer.zip]
    .filter((part: unknown) => typeof part === "string" && (part as string).trim())
    .join(", ");
}

/**
 * Directions link for one ticket's Map Link. The route is stop-to-stop,
 * matching how the day's leg mileage is actually computed: every stop after
 * the first routes FROM the previous stop's job-site address (passed in as
 * prevStopAddress). Only the first stop of the day starts from the branch/
 * dispatch point — via getOfficeCoordinates, or the Electrolux/Huntsville
 * state-based override that computeDailyRouteMiles also uses (an Electrolux
 * ticket dispatches from a different real office depending on the customer's
 * state, not the generic Huntsville pin). Without an explicit origin Google
 * Maps falls back to "Your location" — the viewer's own desk, never the
 * technician's route.
 */
function buildGoogleMapLink(
  branch: string,
  ticket: MapLinkTicket,
  prevStopAddress?: string | null
): string {
  const fullAddress = ticketSiteAddress(ticket);
  if (!fullAddress) return "";
  const dest = encodeURIComponent(fullAddress);
  if (prevStopAddress && prevStopAddress.trim()) {
    return `https://www.google.com/maps/dir/?api=1&travelmode=driving&origin=${encodeURIComponent(prevStopAddress.trim())}&destination=${dest}`;
  }
  const customer = ticket.customer ?? {};
  const overrideOrigin = getElectroluxHuntsvilleMileageOrigin({ location: ticket.location ?? undefined, account: ticket.account ?? undefined, state: customer.state ?? undefined });
  const originPt = overrideOrigin ? null : getOfficeCoordinates(branch);
  const originParam = overrideOrigin
    ? `&origin=${encodeURIComponent(overrideOrigin)}`
    : originPt
    ? `&origin=${originPt.lat},${originPt.lng}`
    : "";
  return `https://www.google.com/maps/dir/?api=1&travelmode=driving${originParam}&destination=${dest}`;
}

export async function syncMileageFromTickets(input: {
  technicians: { profileId: string; fullName: string; branch: string; phone?: string; email?: string; homeAddress?: string }[];
  /** Called after each technician-day finishes recomputing (route lookups
   *  are the slow part — one per day that needs (re)processing, awaited in
   *  sequence below) — lets the caller show live progress instead of one
   *  opaque spinner for however long the whole run takes. `total` is fixed
   *  once known (right before the loop starts); `done` counts up to it. */
  onProgress?: (done: number, total: number) => void;
  /** Checked between technician-days (not mid-day — a day's own route
   *  lookups always finish once started, so a partial/half-saved day never
   *  happens) — when aborted, the loop stops early and returns whatever
   *  was already saved rather than throwing, since every write up to that
   *  point already committed and shouldn't be treated as a failure. */
  signal?: AbortSignal;
}): Promise<MileageSyncResult> {
  const result: MileageSyncResult = { created: 0, skipped: 0, errors: [], unmatchedTechnicians: [], recalculatedDays: 0, stopped: false };
  if (syncInFlight) {
    result.errors.push("Another sync is already running — try again once it finishes.");
    return result;
  }
  syncInFlight = true;
  try {
    return await syncMileageFromTicketsInner(input, result);
  } finally {
    syncInFlight = false;
  }
}

async function syncMileageFromTicketsInner(
  input: {
    technicians: { profileId: string; fullName: string; branch: string; phone?: string; email?: string; homeAddress?: string }[];
    onProgress?: (done: number, total: number) => void;
    signal?: AbortSignal;
  },
  result: MileageSyncResult
): Promise<MileageSyncResult> {
  const techByNormalizedName = new Map(
    input.technicians.filter((t) => t.fullName.trim()).map((t) => [t.fullName.trim().toLowerCase(), t])
  );
  if (techByNormalizedName.size === 0) return result;

  const [{ data: ticketRows, error: ticketsErr }, { data: existingRows, error: existingErr }, { data: rescheduleRows, error: rescheduleErr }, mapProvider] = await Promise.all([
    // Always all-time, no date range — every ticket this company has ever
    // logged. Page through in chunks of 1000 instead of one unbounded select.
    (async () => {
      const all: any[] = [];
      for (let from = 0; ; from += PAGE_SIZE) {
        const { data, error } = await supabase
          .from("tickets")
          .select("id, ticket_no, technician, status, schedule_date, time_slot, created_at, onsite_arrived_at, location, account, customer:customers ( address, address2, city, state, zip, phone, email )")
          .not("technician", "is", null)
          .range(from, from + PAGE_SIZE - 1);
        if (error) return { data: null, error };
        all.push(...(data ?? []));
        if (!data || data.length < PAGE_SIZE) break;
      }
      return { data: all, error: null };
    })(),
    // Unbounded before this fix — Supabase's default 1000-row cap silently
    // truncated it once source=auto rows passed that count (confirmed live:
    // 1,603 of 2,603 real rows missing). Every ticket whose real row fell
    // past the cap then looked "not yet synced" to the code below, which
    // re-attempted an INSERT that collided with the row that was there all
    // along — a 409 per ticket, not a rare race. Paginated the same way the
    // tickets fetch above already is.
    (async () => {
      const all: any[] = [];
      for (let from = 0; ; from += PAGE_SIZE) {
        const { data, error } = await supabase
          .from("mileage_entries")
          .select("id, ticket_id, total_mileage, leg_mileage, google_map_link, work_date, profile_id, technician_name, deleted_at, route_order, home_leg_mileage")
          .eq("source", "auto")
          .not("ticket_id", "is", null)
          .range(from, from + PAGE_SIZE - 1);
        if (error) return { data: null, error };
        all.push(...(data ?? []));
        if (!data || data.length < PAGE_SIZE) break;
      }
      return { data: all, error: null };
    })(),
    // Every ticket_reschedules row (see migration 0215) — a technician's
    // own "Reschedule" flag from the mobile On-Site Check-In card. Used
    // below to exclude a rescheduled ticket from its day's route entirely
    // (not just hide its own row), so the remaining stops' mileage
    // recalculates as if the drive never happened.
    (async () => {
      const all: any[] = [];
      for (let from = 0; ; from += PAGE_SIZE) {
        const { data, error } = await supabase
          .from("ticket_reschedules")
          .select("ticket_id, work_date, reason, profile_id, created_by_name")
          .range(from, from + PAGE_SIZE - 1);
        if (error) return { data: null, error };
        all.push(...(data ?? []));
        if (!data || data.length < PAGE_SIZE) break;
      }
      return { data: all, error: null };
    })(),
    getCompanyMapProvider(),
  ]);
  if (ticketsErr) {
    result.errors.push(`Failed to load tickets: ${ticketsErr.message}`);
    return result;
  }
  if (existingErr) console.error("syncMileageFromTickets (existing sync check) error:", existingErr.message);
  if (rescheduleErr) console.error("syncMileageFromTickets (reschedule check) error:", rescheduleErr.message);

  // Identity for a technician name: the real profile id when it resolves to
  // a known technician, else the raw ticket text itself (lowercased) — kept
  // symmetric between "current" (from the ticket, below) and "stored" (from
  // an existing row, below) so the two are directly comparable. Comparing by
  // id rather than name for matched technicians also means a later display-
  // name change alone never looks like a reassignment.
  const identityFor = (rawName: string): string => {
    const trimmed = rawName.trim();
    const matched = techByNormalizedName.get(trimmed.toLowerCase());
    return matched ? `id:${matched.profileId}` : `name:${trimmed.toLowerCase()}`;
  };

  const existingByTicketId = new Map(
    (existingRows ?? []).map((r: any) => [
      r.ticket_id as string,
      {
        id: r.id as string,
        totalMileage: Number(r.total_mileage) || 0,
        hasLegMileage: r.leg_mileage != null,
        // A map link generated before the branch-origin fix has no
        // "origin=" param at all — Google Maps then falls back to "Your
        // location." Re-processing once fixes it, same as the leg_mileage
        // backfill below. A null/empty link (no customer address on file)
        // isn't a stale-format problem to fix, so it's treated as fine —
        // only an actual old-format link (present, no origin=) is flagged,
        // or reprocessing would spin forever on an addressless ticket.
        // (Stop-to-stop origins on top of this are computed live in
        // TicketAttendanceTab's Map Link column — no re-sync needed.)
        hasOriginInMapLink: !r.google_map_link || String(r.google_map_link).includes("origin="),
        workDate: r.work_date as string,
        identity: r.profile_id ? `id:${r.profile_id}` : `name:${String(r.technician_name || "").trim().toLowerCase()}`,
        deletedAt: r.deleted_at as string | null,
        routeOrder: r.route_order as number | null,
        homeLegMileage: r.home_leg_mileage != null ? Number(r.home_leg_mileage) : null,
      },
    ])
  );

  // ticket_id + work_date pairs a technician has marked "Reschedule" —
  // excluded from route-building below entirely, not just hidden from
  // display, so the day's route recalculates as if the drive never
  // happened. Keyed on the CURRENT schedule_date, matching how the rest of
  // this function always groups by a ticket's current day.
  const rescheduledByKey = new Map<string, { reason: string; profileId: string; createdByName: string | null }>();
  for (const r of (rescheduleRows ?? []) as any[]) {
    rescheduledByKey.set(`${r.ticket_id}|${r.work_date}`, {
      reason: r.reason,
      profileId: r.profile_id,
      createdByName: r.created_by_name ?? null,
    });
  }

  // A ticket just rescheduled that already had a real (non-deleted)
  // mileage_entries row from before the reschedule — that row is now
  // stale (it still shows the real drive distance) and would keep
  // counting toward payroll/display even though the trip never happened.
  // Soft-delete it the same way a human would from the Mileage tab
  // (softDeleteMileageEntry), attributing it to whichever technician
  // actually rescheduled the ticket rather than whoever triggered this
  // sync. Only ever touches THIS ticket's own row — never the route math
  // for the rest of that day's stops, which is handled entirely by
  // allAssignedTickets excluding it below.
  for (const [key, reschedule] of rescheduledByKey) {
    const [ticketId] = key.split("|");
    const existing = existingByTicketId.get(ticketId);
    if (!existing || existing.deletedAt) continue;
    await softDeleteMileageEntry(existing.id, reschedule.reason, reschedule.profileId, reschedule.createdByName);
  }

  // A ticket whose scheduled day has already fully passed with no real
  // on-site Arrived stamp at all (see TicketAttendanceTab's identical
  // dayHasPassed/didNotGo condition) — the tech never actually went, so
  // (unlike an open/cancelled ticket still ahead of or on its scheduled
  // day, which stays a normal route waypoint below) this involved NO real
  // drive and must not become one either. Previously every assigned ticket
  // was treated as a real stop regardless of status, which let a
  // permanently-missed ticket get chained into that day's route — wrongly
  // contributing its own leg distance (or, worse, absorbing the day's
  // drive-home leg if it happened to land last) even though nobody ever
  // drove there. Confirmed live: A'Dejaun Tyson's 2026-09-09 route.
  const todayISO = new Date().toISOString().slice(0, 10);
  const isPermanentlyMissed = (t: any): boolean => !t.onsite_arrived_at && t.schedule_date && t.schedule_date < todayISO;

  // Every ticket with a technician assigned and an actual date to log the
  // drive under — status doesn't matter otherwise, an open/cancelled ticket
  // still involved a real drive. Rescheduled and permanently-missed tickets
  // are dropped here, before any grouping/route math, so neither ever
  // becomes a route waypoint.
  const allAssignedTickets = (ticketRows ?? []).filter(
    (t: any) =>
      String(t.technician || "").trim() &&
      t.schedule_date &&
      !rescheduledByKey.has(`${t.id}|${t.schedule_date}`) &&
      !isPermanentlyMissed(t)
  );

  // A permanently-missed ticket that already has a real (non-deleted)
  // mileage_entries row from before this exclusion existed is now stale for
  // the same reason a just-rescheduled ticket's row is (see the reschedule
  // loop above) — soft-delete it too, attributed to whoever's system-wide
  // "Auto-sync" already creates these rather than a specific person (there's
  // no human action to attribute this one to).
  for (const t of (ticketRows ?? []) as any[]) {
    if (!isPermanentlyMissed(t)) continue;
    const existing = existingByTicketId.get(t.id);
    if (!existing || existing.deletedAt) continue;
    await softDeleteMileageEntry(existing.id, "Never checked in — scheduled day passed with no on-site arrival.", null, "Auto-sync");
  }

  // Anyone whose tickets carry a technician name that isn't a known
  // technician, even after trim/lowercase — still synced below (as an
  // unlinked, profile_id: null entry), just surfaced separately so a real
  // name mismatch is visible and fixable rather than looking like any other
  // synced entry.
  const unmatchedCounts = new Map<string, number>();
  for (const t of allAssignedTickets as any[]) {
    const name = String(t.technician).trim();
    if (!techByNormalizedName.has(name.toLowerCase())) {
      unmatchedCounts.set(name, (unmatchedCounts.get(name) ?? 0) + 1);
    }
  }
  result.unmatchedTechnicians = Array.from(unmatchedCounts.entries())
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count);

  // Group EVERY assigned ticket (already-synced AND pending) by its CURRENT
  // (technician identity, work date) — a day's route depends on ALL of that
  // day's stops, not just the ones that happen to be new, so an
  // already-partially-synced day still needs its full stop list to
  // recompute correctly once a new ticket joins it. Using CURRENT values
  // means a rescheduled or reassigned ticket lands in its NEW day/
  // technician's group here, not its old one.
  const groups = new Map<string, any[]>();
  for (const t of allAssignedTickets as any[]) {
    const key = `${identityFor(String(t.technician))}|${t.schedule_date}`;
    const list = groups.get(key) ?? [];
    list.push(t);
    groups.set(key, list);
  }

  // A group needs (re)processing if a ticket is new (no row yet) or just
  // moved IN (its existing row is still stored under a different day/
  // technician). Separately, a group can also need processing purely
  // because it lost a ticket that moved OUT — its remaining tickets are all
  // otherwise unchanged, so neither of the above catches it; detected by
  // comparing, per stored (identity, date) key, the ticket ids an existing
  // row claims against the ticket ids that key's CURRENT group actually has.
  const currentTicketIdsByKey = new Map<string, Set<string>>();
  for (const [key, tickets] of groups) currentTicketIdsByKey.set(key, new Set(tickets.map((t) => t.id)));
  const keysThatLostATicket = new Set<string>();
  for (const [ticketId, existing] of existingByTicketId) {
    const storedKey = `${existing.identity}|${existing.workDate}`;
    if (!(currentTicketIdsByKey.get(storedKey)?.has(ticketId) ?? false)) keysThatLostATicket.add(storedKey);
  }

  const groupsToProcess = Array.from(groups.entries())
    .filter(([key, tickets]) => {
      const hasNewOrMovedInTicket = tickets.some((t) => {
        const existing = existingByTicketId.get(t.id);
        if (!existing) return true;
        return `${existing.identity}|${existing.workDate}` !== key;
      });
      // Backfill: a day fully synced before leg_mileage existed (migration
      // 0210) has every row's total_mileage already correct, so neither
      // check above would ever re-touch it — without this it would stay
      // stuck showing "—" in the Mileage tab's This Stop column forever,
      // since nothing about the day's tickets ever actually changes.
      const hasMissingLegMileage = tickets.some((t) => !existingByTicketId.get(t.id)?.hasLegMileage);
      const hasStaleMapLink = tickets.some((t) => !existingByTicketId.get(t.id)?.hasOriginInMapLink);
      // One-time self-heal for the pre-arrival-order mileage bug (see
      // sortStopsByHeuristic's header comment): a day with AT LEAST ONE real
      // on-site Arrived stamp to sort by, whose stored rows were never
      // confirmed against arrival data at all (route_order still null —
      // either never synced with any arrival data available, or synced back
      // when the old created_at/time-slot heuristic was the only option).
      // Deliberately `.some`, not `.every` — a single never-visited ticket
      // mixed into an otherwise fully-checked-in day (cancelled, rescheduled
      // elsewhere, genuinely never gone to) must not block fixing the rest
      // of that day's real, wrong-chained mileage.
      const hasUnconfirmedArrivalOrder =
        tickets.some((t: any) => t.onsite_arrived_at) &&
        tickets.some((t) => (existingByTicketId.get(t.id)?.routeOrder ?? null) == null);
      // One-time backfill for migration 0237 (home_leg_mileage): a day
      // that's already order-confirmed (so hasUnconfirmedArrivalOrder above
      // won't catch it again) but has never had its drive-home distance
      // split out of leg_mileage — every existing row's home_leg_mileage is
      // still null. Reprocessing sets it on the day's actual last stop,
      // which then satisfies this check going forward (a day with no
      // resolvable home/branch address at all would keep matching here
      // forever, but that's the same rare edge case hasStaleMapLink already
      // accepts for a similar reason).
      const hasMissingHomeLeg =
        tickets.some((t) => (existingByTicketId.get(t.id)?.routeOrder ?? null) != null) &&
        !tickets.some((t) => (existingByTicketId.get(t.id)?.homeLegMileage ?? null) != null);
      return hasNewOrMovedInTicket || keysThatLostATicket.has(key) || hasMissingLegMileage || hasStaleMapLink || hasUnconfirmedArrivalOrder || hasMissingHomeLeg;
    })
    .map(([, tickets]) => tickets);
  const untouchedTicketCount = allAssignedTickets.length - groupsToProcess.reduce((s, g) => s + g.length, 0);
  result.skipped = untouchedTicketCount;
  result.recalculatedDays = groupsToProcess.length;

  input.onProgress?.(0, groupsToProcess.length);
  for (let groupIdx = 0; groupIdx < groupsToProcess.length; groupIdx++) {
    if (input.signal?.aborted) {
      result.stopped = true;
      result.recalculatedDays = groupIdx; // only what actually got processed before stopping
      break;
    }
    // finally, not just an end-of-body call — an early return inside
    // processMileageDayGroup (route lookup failed/threw) still needs to
    // advance the progress count, or it visibly stalls instead of just
    // moving past a skipped day.
    try {
      await processMileageDayGroup(groupsToProcess[groupIdx], existingByTicketId, techByNormalizedName, mapProvider, result, "Auto-sync");
    } finally {
      input.onProgress?.(groupIdx + 1, groupsToProcess.length);
    }
  }

  return result;
}

/**
 * The actual per-technician-per-day route computation + mileage_entries
 * write, shared by both the full-company batch scan above
 * (syncMileageFromTicketsInner) and the event-driven single-day recompute
 * below (syncMileageForTicketDay) — one place computes the route and
 * writes it, however the recompute got triggered. `existingByTicketId` only
 * needs each ticket's existing row id (untyped/`any` here since the batch
 * caller's map carries several other fields this function never reads).
 */
async function processMileageDayGroup(
  groupTickets: any[],
  existingByTicketId: Map<string, any>,
  techByNormalizedName: Map<string, { profileId: string; fullName: string; branch: string; phone?: string; email?: string; homeAddress?: string }>,
  mapProvider: Awaited<ReturnType<typeof getCompanyMapProvider>>,
  result: MileageSyncResult,
  createdByLabel: string
): Promise<void> {
  const orderedTickets = sortStopsByHeuristic(groupTickets);

  const rawName = String(orderedTickets[0].technician).trim();
  const technician = techByNormalizedName.get(rawName.toLowerCase()) ?? null;
  const branch = orderedTickets[0].location || technician?.branch || "Unassigned";
  const routeStops: MileageTicketInput[] = orderedTickets.map((t) => {
    const customer = t.customer ?? {};
    return { location: t.location, city: customer.city, address: customer.address, state: customer.state, zip: customer.zip, account: t.account };
  });

  let routeResult: DailyRouteMilesResult | null = null;
  try {
    routeResult = await computeDailyRouteMiles(branch, routeStops[0], routeStops, technician?.homeAddress, mapProvider);
  } catch (err) {
    result.errors.push(`${orderedTickets[0].schedule_date} (${rawName}): ${err instanceof Error ? err.message : "route lookup failed"}`);
    return;
  }
  if (routeResult === null) {
    result.errors.push(`${orderedTickets[0].schedule_date} (${rawName}): no route found — skipped.`);
    return;
  }
  const roundedMiles = Math.round(routeResult.totalMiles * 10) / 10;
  // legMiles is index-aligned with orderedTickets/routeStops — ONLY this
  // ticket's own leg (previous stop -> this stop), null if it couldn't be
  // geocoded. The day's final drive-home distance is kept separate (see
  // homeLegMileage below, migration 0237) rather than folded into
  // whichever stop happens to be last. Purely a display breakdown;
  // roundedMiles (the day total) is still what payroll reads, unaffected
  // by either of these.
  const legMileageAt = (idx: number): number | null => {
    const m = routeResult!.legMiles[idx];
    return m != null ? Math.round(m * 10) / 10 : null;
  };
  // Only the day's actual LAST stop carries the drive-home distance, on
  // its own column — every earlier stop's home_leg_mileage stays null.
  const homeLegMileageAt = (idx: number): number | null => {
    if (idx !== orderedTickets.length - 1) return null;
    const m = routeResult!.homeLegMiles;
    return m != null ? Math.round(m * 10) / 10 : null;
  };
  // At least one stop in this group has a real Arrived stamp, so
  // orderedTickets used it (sortStopsByHeuristic prefers a real stamp
  // whenever one exists) rather than relying purely on the time-slot/
  // created_at guess — persist it as route_order so it reads as settled
  // (same as a human's manual sequencing) and this day's
  // hasUnconfirmedArrivalOrder check above never re-flags it. Matches that
  // check's own `.some`, not `.every`: a day with one permanently
  // never-visited stop mixed in (cancelled, rescheduled elsewhere) would
  // otherwise never lock in and get needlessly recomputed on every future
  // sync forever. A day with NO arrival data at all yet keeps writing
  // route_order: null, unchanged, so it stays free to reorder itself once
  // real stamps start coming in.
  const confirmedByArrival = orderedTickets.some((t: any) => t.onsite_arrived_at);

  // Refresh every already-synced ticket in this group — a new stop
  // joined, so the whole day's route (and therefore every existing
  // row's total) is potentially stale, even if this particular round
  // happens to land on the same number as before. work_date/profile_id/
  // technician_name/branch are re-set to this group's own values too —
  // a no-op for a ticket that was already here, but for one that just
  // got rescheduled or reassigned, this is what actually MOVES its row
  // onto the new day/new technician rather than leaving it stale under
  // the old ones.
  for (let idx = 0; idx < orderedTickets.length; idx++) {
    const t = orderedTickets[idx];
    const existing = existingByTicketId.get(t.id);
    if (existing) {
      const prevStopAddress = idx > 0 ? ticketSiteAddress(orderedTickets[idx - 1]) : null;
      const { error: updateErr } = await supabase
        .from("mileage_entries")
        .update({
          total_mileage: roundedMiles,
          leg_mileage: legMileageAt(idx),
          home_leg_mileage: homeLegMileageAt(idx),
          route_order: confirmedByArrival ? idx : null,
          route_return_to: null,
          work_date: t.schedule_date,
          profile_id: technician?.profileId ?? null,
          technician_name: technician ? null : rawName,
          branch,
          google_map_link: buildGoogleMapLink(branch, t, prevStopAddress) || null,
        })
        .eq("id", existing.id);
      if (updateErr) result.errors.push(`Ticket ${t.ticket_no}: failed to refresh mileage — ${updateErr.message}`);
    }
  }

  const newTickets = orderedTickets.filter((t) => !existingByTicketId.has(t.id));
  for (const ticket of newTickets) {
    const stopIdx = orderedTickets.indexOf(ticket);
    const prevStopAddress = stopIdx > 0 ? ticketSiteAddress(orderedTickets[stopIdx - 1]) : null;
    const googleMapLink = buildGoogleMapLink(branch, ticket, prevStopAddress);

    const { error: insertErr } = await supabase.from("mileage_entries").insert({
      profile_id: technician?.profileId ?? null,
      technician_name: technician ? null : rawName,
      branch,
      work_date: ticket.schedule_date,
      // The technician's OWN contact info, not the customer's — Address/
      // Contact Number/Email here answer "who drove and how do we reach
      // them," which the customer's job-site details never were. Google
      // Map Link below still points at the customer's site (for driving
      // directions there), unaffected by this.
      address: technician?.homeAddress || "(no address on file)",
      contact_number: technician?.phone || null,
      email: technician?.email || null,
      total_mileage: roundedMiles,
      leg_mileage: legMileageAt(orderedTickets.indexOf(ticket)),
      home_leg_mileage: homeLegMileageAt(orderedTickets.indexOf(ticket)),
      route_order: confirmedByArrival ? orderedTickets.indexOf(ticket) : null,
      google_map_link: googleMapLink || null,
      created_by_name: createdByLabel,
      ticket_id: ticket.id,
      ticket_no: ticket.ticket_no,
      ticket_status: ticket.status,
      source: "auto",
    });
    if (insertErr) {
      // Unique-violation on ticket_id means another sync run already logged
      // it a moment ago (race) — treat as skipped, not a real failure.
      if (insertErr.code === "23505") result.skipped++;
      else result.errors.push(`Ticket ${ticket.ticket_no}: ${insertErr.message}`);
      continue;
    }
    result.created++;
  }
}

/**
 * Event-driven counterpart to syncMileageFromTickets — recomputes ONE
 * technician's ONE day (every ticket they're assigned to on that date, not
 * the whole company's entire history) right after a real On-Site Check-In
 * event. Wired into tickets.ts's setTicketOnsiteCheckIn (both "arrived" and
 * "done", and the Ticket Time Dispute approval path via
 * resetMileageRouteConfirmation), so mileage/route order reflects a
 * check-in immediately instead of waiting for someone to open the Mileage
 * tab and run — and wait out — a full all-technician/all-time scan.
 *
 * Deliberately silent on failure (logs, never throws): a failed live
 * recompute must not block or surface an error on the check-in write it's
 * riding along with. The next manual "Sync from Tickets" run (kept as a
 * safety net, no longer auto-triggered on tab open — see
 * AccountingDashboard.tsx) still catches anything this misses.
 *
 * Does not take the module-level `syncInFlight` lock — this call is small
 * (one technician, one day) and shouldn't have to wait behind a full
 * company scan. If both happen to touch the same day at once, the results
 * converge to the same computed numbers either way, and a colliding INSERT
 * is already handled as a skip (23505) above.
 */
export async function syncMileageForTicketDay(rawTechnicianName: string, scheduleDate: string): Promise<void> {
  try {
    const trimmedName = rawTechnicianName.trim();
    if (!trimmedName || !scheduleDate) return;

    const [{ data: dayTickets, error: ticketsErr }, { data: rescheduleRows, error: rescheduleErr }, mapProvider] = await Promise.all([
      supabase
        .from("tickets")
        .select("id, ticket_no, technician, status, schedule_date, time_slot, created_at, onsite_arrived_at, location, account, customer:customers ( address, address2, city, state, zip, phone, email )")
        .eq("schedule_date", scheduleDate)
        .not("technician", "is", null),
      supabase.from("ticket_reschedules").select("ticket_id").eq("work_date", scheduleDate),
      getCompanyMapProvider(),
    ]);
    if (ticketsErr) {
      console.error("syncMileageForTicketDay: failed to load tickets:", ticketsErr.message);
      return;
    }
    if (rescheduleErr) console.error("syncMileageForTicketDay: failed to load reschedules:", rescheduleErr.message);

    const rescheduledTicketIds = new Set((rescheduleRows ?? []).map((r: any) => r.ticket_id as string));
    // Same permanently-missed exclusion as the batch scan (see
    // syncMileageFromTicketsInner) — a sibling ticket in this technician's
    // day that never got a real Arrived stamp and whose scheduled day has
    // already passed involved no real drive, so it must not become a route
    // waypoint here either. The ticket that actually triggered this call
    // always has a fresh onsite_arrived_at (it just got checked into), so
    // it's never excluded by this.
    const todayISO = new Date().toISOString().slice(0, 10);
    const isPermanentlyMissed = (t: any): boolean => !t.onsite_arrived_at && t.schedule_date && t.schedule_date < todayISO;
    const groupTickets = (dayTickets ?? []).filter(
      (t: any) =>
        String(t.technician || "").trim().toLowerCase() === trimmedName.toLowerCase() &&
        !rescheduledTicketIds.has(t.id) &&
        !isPermanentlyMissed(t)
    );
    if (groupTickets.length === 0) return;

    const { data: existingRows, error: existingErr } = await supabase
      .from("mileage_entries")
      .select("id, ticket_id")
      .eq("source", "auto")
      .in(
        "ticket_id",
        groupTickets.map((t: any) => t.id)
      );
    if (existingErr) {
      console.error("syncMileageForTicketDay: failed to load existing entries:", existingErr.message);
      return;
    }
    const existingByTicketId = new Map((existingRows ?? []).map((r: any) => [r.ticket_id as string, { id: r.id as string }]));

    // Clean up any stale row left over from before this exclusion existed —
    // same reasoning as the batch scan's equivalent soft-delete.
    for (const t of (dayTickets ?? []) as any[]) {
      if (String(t.technician || "").trim().toLowerCase() !== trimmedName.toLowerCase() || !isPermanentlyMissed(t)) continue;
      const { data: staleRow } = await supabase
        .from("mileage_entries")
        .select("id")
        .eq("source", "auto")
        .eq("ticket_id", t.id)
        .is("deleted_at", null)
        .maybeSingle();
      if (staleRow) {
        await softDeleteMileageEntry(staleRow.id, "Never checked in — scheduled day passed with no on-site arrival.", null, "Auto-sync").catch((err) =>
          console.error("syncMileageForTicketDay: failed to soft-delete stale entry:", err)
        );
      }
    }

    // Matches AccountingDashboard's own full_name fallback chain
    // (display_name || username || id) so this resolves to the same
    // technician a full sync would have.
    const { data: profileRows, error: profileErr } = await supabase
      .from("profiles")
      .select("id, display_name, username, assigned_branch, phone_number, email, employee_info")
      .eq("is_active", true);
    if (profileErr) console.error("syncMileageForTicketDay: failed to load profiles:", profileErr.message);
    const techByNormalizedName = new Map<string, { profileId: string; fullName: string; branch: string; phone?: string; email?: string; homeAddress?: string }>();
    for (const p of (profileRows ?? []) as any[]) {
      const fullName = String(p.display_name || p.username || p.id);
      if (!fullName.trim()) continue;
      const info = (p.employee_info && typeof p.employee_info === "object" ? p.employee_info : {}) as Record<string, any>;
      const homeAddress = [info.address1, info.address2, [info.city, info.state].filter(Boolean).join(", "), info.zipCode]
        .filter((part) => part && String(part).trim())
        .join(", ");
      techByNormalizedName.set(fullName.trim().toLowerCase(), {
        profileId: p.id,
        fullName,
        branch: p.assigned_branch || "Unassigned",
        phone: p.phone_number || undefined,
        email: p.email || undefined,
        homeAddress: homeAddress || undefined,
      });
    }

    const result: MileageSyncResult = { created: 0, skipped: 0, errors: [], unmatchedTechnicians: [], recalculatedDays: 0, stopped: false };
    await processMileageDayGroup(groupTickets, existingByTicketId, techByNormalizedName, mapProvider, result, "Auto-sync (check-in)");
    if (result.errors.length > 0) console.error("syncMileageForTicketDay:", result.errors.join("; "));
  } catch (err) {
    console.error("syncMileageForTicketDay failed:", err instanceof Error ? err.message : err);
  }
}

/**
 * Recomputes one technician's one day of driving with a HUMAN-CHOSEN stop
 * order (the Day Route view's drag/reorder controls) instead of the
 * automatic time-slot heuristic, and saves both the new total and each
 * row's route_order (its index in orderedTicketIds) so the order sticks
 * until either a human changes it again or a new ticket joins that day
 * (which resets it — see syncMileageFromTickets). Throws rather than
 * returning null on failure so the UI can show a real error instead of
 * silently leaving the old total in place.
 */
export async function recalculateMileageDayRoute(input: {
  /** This day's existing mileage_entries rows — id + the ticket each one is for. */
  entries: { id: string; ticketId: string }[];
  /** The new visit order, by ticket id — must cover every ticket in entries. */
  orderedTicketIds: string[];
  branch: string;
  homeAddress?: string;
  /** "home" routes the final leg to homeAddress (falls back to branch
   *  anyway if that's blank); "branch" forces a branch-return route even
   *  when a home address exists. Saved as route_return_to on every row. */
  returnTo: "home" | "branch";
}): Promise<number> {
  const { data: ticketRows, error: ticketsErr } = await supabase
    .from("tickets")
    .select("id, location, account, customer:customers ( address, city, state, zip )")
    .in("id", input.orderedTicketIds);
  if (ticketsErr) throw new Error(ticketsErr.message);
  const ticketById = new Map((ticketRows ?? []).map((t: any) => [t.id, t]));

  const orderedStops: MileageTicketInput[] = input.orderedTicketIds.map((id) => {
    const t = ticketById.get(id);
    const customer = t?.customer ?? {};
    return { location: t?.location, city: customer.city, address: customer.address, state: customer.state, zip: customer.zip, account: t?.account };
  });
  if (orderedStops.length === 0) throw new Error("No stops to route.");

  const mapProvider = await getCompanyMapProvider();
  const effectiveHomeAddress = input.returnTo === "home" ? input.homeAddress : undefined;
  const routeResult = await computeDailyRouteMiles(input.branch, orderedStops[0], orderedStops, effectiveHomeAddress, mapProvider);
  if (routeResult === null) throw new Error("No route found for this stop order.");
  const roundedMiles = Math.round(routeResult.totalMiles * 10) / 10;

  const lastIdx = input.orderedTicketIds.length - 1;
  const orderIndexByTicketId = new Map(input.orderedTicketIds.map((id, idx) => [id, idx]));
  for (const entry of input.entries) {
    const idx = orderIndexByTicketId.get(entry.ticketId);
    const legMiles = idx != null ? routeResult.legMiles[idx] : null;
    // Only the day's actual last stop carries the drive-home distance, on
    // its own column — see homeLegMiles (migration 0237). Never folded into
    // leg_mileage, here or anywhere else it's computed.
    const homeLegMiles = idx === lastIdx ? routeResult.homeLegMiles : null;
    const { error } = await supabase
      .from("mileage_entries")
      .update({
        total_mileage: roundedMiles,
        leg_mileage: legMiles != null ? Math.round(legMiles * 10) / 10 : null,
        home_leg_mileage: homeLegMiles != null ? Math.round(homeLegMiles * 10) / 10 : null,
        route_order: idx ?? null,
        route_return_to: input.returnTo,
      })
      .eq("id", entry.id);
    if (error) throw new Error(`Failed to save ticket order: ${error.message}`);
  }
  return roundedMiles;
}

/**
 * Sets (or clears, when both override and adjustment are null) Finance's
 * manual correction to a day's mileage total — see mileageEffectiveTotal.
 * Applied identically across every row of the (technician, work_date)
 * group, same as total_mileage itself is shared, so the effective total
 * reads the same no matter which of that day's tickets you're looking at.
 */
export async function setMileageDayAdjustment(input: {
  entryIds: string[];
  override: number | null;
  adjustment: number | null;
  note: string | null;
  byProfileId: string | null;
  byName: string | null;
}): Promise<void> {
  const hasAdjustment = input.override != null || input.adjustment != null;
  const { error } = await supabase
    .from("mileage_entries")
    .update({
      mileage_override: input.override,
      mileage_adjustment: input.adjustment,
      adjustment_note: input.note,
      adjusted_by: hasAdjustment ? input.byProfileId : null,
      adjusted_by_name: hasAdjustment ? input.byName : null,
      adjusted_at: hasAdjustment ? new Date().toISOString() : null,
    })
    .in("id", input.entryIds);
  if (error) throw new Error(error.message);
}
