/**
 * Technician mileage log (migration 0138) — a manual entry log, PLUS
 * (migration 0141) an optional auto-sync path that derives entries from
 * every ticket assigned to a technician, regardless of status. Manual
 * entries are typed in directly;
 * auto-synced ones (source: "auto") are generated by syncMileageFromTickets
 * below, reusing the same office-to-customer distance calculator already
 * used on the ticket detail page (mapEngine.ts's computeOfficeDistanceMiles)
 * rather than any new mileage math. Edited on Accounting Dashboard's
 * Mileage tab.
 */

import { supabase } from "./client";
import { getCompanyMapProvider } from "./companySettings";
import { computeDailyRouteMiles, type MileageTicketInput, type DailyRouteMilesResult } from "@/lib/mapEngine";

export interface MileageEntry {
  id: string;
  /** Null when this entry was auto-synced for a technician name that
   *  matched no real profile — see technicianName and migration 0142. */
  profileId: string | null;
  /** Raw ticket technician text, set only when profileId is null — the
   *  display fallback for an unmatched auto-synced entry. Manual entries
   *  (which always require picking a real profile) never set this. */
  technicianName: string | null;
  branch: string;
  workDate: string;
  address: string;
  contactNumber: string | null;
  email: string | null;
  totalMileage: number;
  googleMapLink: string | null;
  createdByName: string | null;
  createdAt: string;
  ticketId: string | null;
  /** Human-readable ticket number, set only on auto-synced entries — see migration 0143. */
  ticketNo: string | null;
  /** The ticket's status AT SYNC TIME — a snapshot, not live; see migration 0147. */
  ticketStatus: string | null;
  source: "manual" | "auto";
  /** Payroll override set via the On Hold action — see migration 0148 and
   *  setMileageEntryPayrollExcluded. While true, this ticket never counts
   *  toward the technician's "Completed Tickets" pay, even if its status
   *  later becomes completed. Reversible — toggling it back off restores
   *  normal pay counting. */
  payrollExcluded: boolean;
  payrollExcludedAt: string | null;
  payrollExcludedByName: string | null;
  /** "manual" (Mileage tab's On Hold button) or "no_photos" (automatic — see
   *  reconcileMileageNoPhotoHolds). Null when not excluded. Lets the
   *  automatic rule know never to touch a human's manual hold, and lets a
   *  human's "take it off hold" always win even with no photo. Migration 0177. */
  payrollHoldReason: "manual" | "no_photos" | null;
  /** This day's manually-set stop sequence (0-based, shared meaning across
   *  every entry in the same technician+work_date group) — see
   *  recalculateMileageDayRoute. Null means "use the automatic time-slot/
   *  created-at heuristic in syncMileageFromTickets" — including after a
   *  fresh ticket joins an already-manually-ordered day, which resets the
   *  whole group back to null/heuristic rather than guessing where the new
   *  stop belongs. Migration 0182. */
  routeOrder: number | null;
  /** Whether this day's route ends at the technician's home address or
   *  loops back to the branch — see recalculateMileageDayRoute. Null means
   *  "automatic default" (home if one's on file, branch otherwise — the
   *  same fallback computeDailyRouteMiles already applied before this
   *  field existed). Resets to null under the same new-ticket-joins-the-day
   *  rule as routeOrder. Migration 0183. */
  routeReturnTo: "home" | "branch" | null;
  /** Full replacement for this day's total, if Finance has set one — see
   *  mileageEffectiveTotal and setMileageDayAdjustment. Takes precedence
   *  over mileageAdjustment when both are set. Migration 0182. */
  mileageOverride: number | null;
  /** A +/- delta added to totalMileage (ignored when mileageOverride is
   *  set) — see mileageEffectiveTotal. Migration 0182. */
  mileageAdjustment: number | null;
  adjustmentNote: string | null;
  adjustedByName: string | null;
  adjustedAt: string | null;
  /** When payrollExcluded last flipped true -> false — the opposite of
   *  payrollExcludedAt, which release always nulls out. Lets the mobile "On
   *  Hold Tickets" screen's Updated sub-tab show what recently cleared,
   *  since payrollExcludedAt/payrollHoldReason no longer carry that once a
   *  hold is released. Cleared again if the entry is ever re-held.
   *  Migration 0186. */
  payrollReleasedAt: string | null;
  /** Soft-delete (migration 0209) — for a stop the technician never
   *  actually made (customer cancelled, couldn't get there, etc.), so it
   *  needs to come OUT of the day's route and mileage total entirely.
   *  Different from payrollExcluded ("On Hold"), which is for a stop the
   *  technician DID drive to but that shouldn't count for payroll yet —
   *  On Hold stays in the route; deletedAt removes it. The row itself
   *  stays in place either way (still visible in the Mileage tab table,
   *  its Payroll status reads "Deleted"). See softDeleteMileageEntry.
   *  Reversible via restoreMileageEntry. */
  deletedAt: string | null;
  deletedByName: string | null;
  deleteReason: string | null;
  /** This ticket's OWN leg of the day's route — distance from the previous
   *  stop (or the branch, for the day's first stop) to this one, with the
   *  final "way home" leg folded into the day's LAST stop. Purely a display
   *  breakdown of totalMileage/mileageEffectiveTotal (which stays the
   *  shared day total payroll reads, unaffected by this) — summing every
   *  entry's legMileage for one day reconstructs that same day total. Null
   *  for manual entries (no route/stop-order concept), a stop that failed
   *  to geocode, or a row not yet recalculated since migration 0210.
   *  Computed in syncMileageFromTickets/recalculateMileageDayRoute via
   *  computeDailyRouteMiles's legMiles (mapEngine.ts). */
  legMileage: number | null;
}

/**
 * The number that actually counts for display and payroll — a manual
 * override replaces the calculated total_mileage outright; a manual
 * adjustment adds/subtracts from it; with neither set, it's just the
 * calculated total. EVERY read of a day's mileage figure (the Mileage
 * table, the technician detail modal, getTechAutoMileageTotals) must go
 * through this rather than entry.totalMileage directly, or a Finance
 * correction silently won't take effect.
 */
export function mileageEffectiveTotal(entry: Pick<MileageEntry, "totalMileage" | "mileageOverride" | "mileageAdjustment">): number {
  if (entry.mileageOverride != null) return entry.mileageOverride;
  return entry.totalMileage + (entry.mileageAdjustment ?? 0);
}

function mapRow(r: any): MileageEntry {
  return {
    id: r.id,
    profileId: r.profile_id ?? null,
    technicianName: r.technician_name ?? null,
    branch: r.branch,
    workDate: r.work_date,
    address: r.address,
    contactNumber: r.contact_number ?? null,
    email: r.email ?? null,
    totalMileage: Number(r.total_mileage) || 0,
    googleMapLink: r.google_map_link ?? null,
    createdByName: r.created_by_name ?? null,
    createdAt: r.created_at,
    ticketId: r.ticket_id ?? null,
    ticketNo: r.ticket_no ?? null,
    ticketStatus: r.ticket_status ?? null,
    source: r.source === "auto" ? "auto" : "manual",
    payrollExcluded: !!r.payroll_excluded,
    payrollExcludedAt: r.payroll_excluded_at ?? null,
    payrollExcludedByName: r.payroll_excluded_by_name ?? null,
    payrollHoldReason: r.payroll_hold_reason === "manual" || r.payroll_hold_reason === "no_photos" ? r.payroll_hold_reason : null,
    routeOrder: r.route_order ?? null,
    routeReturnTo: r.route_return_to === "home" || r.route_return_to === "branch" ? r.route_return_to : null,
    mileageOverride: r.mileage_override != null ? Number(r.mileage_override) : null,
    mileageAdjustment: r.mileage_adjustment != null ? Number(r.mileage_adjustment) : null,
    adjustmentNote: r.adjustment_note ?? null,
    adjustedByName: r.adjusted_by_name ?? null,
    adjustedAt: r.adjusted_at ?? null,
    payrollReleasedAt: r.payroll_released_at ?? null,
    deletedAt: r.deleted_at ?? null,
    deletedByName: r.deleted_by_name ?? null,
    deleteReason: r.delete_reason ?? null,
    legMileage: r.leg_mileage != null ? Number(r.leg_mileage) : null,
  };
}

const ENTRY_COLUMNS =
  "id, profile_id, technician_name, branch, work_date, address, contact_number, email, total_mileage, google_map_link, created_by_name, created_at, ticket_id, ticket_no, ticket_status, source, payroll_excluded, payroll_excluded_at, payroll_excluded_by_name, payroll_hold_reason, route_order, route_return_to, mileage_override, mileage_adjustment, adjustment_note, adjusted_by_name, adjusted_at, payroll_released_at, deleted_at, deleted_by_name, delete_reason, leg_mileage";

// Supabase caps an unbounded select at 1000 rows — mileage_entries is
// queried all-time, no date range. Page through in chunks of 1000 instead.
const PAGE_SIZE = 1000;

/** All mileage entries for the caller's company (RLS-scoped), newest first. */
export async function getMileageEntries(): Promise<MileageEntry[]> {
  const all: MileageEntry[] = [];
  for (let from = 0; ; from += PAGE_SIZE) {
    const { data, error } = await supabase
      .from("mileage_entries")
      .select(ENTRY_COLUMNS)
      .order("work_date", { ascending: false })
      .range(from, from + PAGE_SIZE - 1);
    if (error) {
      console.error("getMileageEntries error:", error.message);
      return all;
    }
    all.push(...(data ?? []).map(mapRow));
    if (!data || data.length < PAGE_SIZE) break;
  }
  return all;
}

/**
 * Toggles the "don't pay for this ticket while on hold" override — see
 * MileageEntry.payrollExcluded. Reversible: un-excluding just clears the
 * flag; it doesn't need to restore anything else, since the exclusion is
 * checked live by getTechCompletedRepairCounts, not baked into a stored pay
 * amount anywhere.
 */
export async function setMileageEntryPayrollExcluded(
  id: string,
  excluded: boolean,
  excludedByProfileId: string | null,
  excludedByName: string | null
): Promise<void> {
  const { error } = await supabase
    .from("mileage_entries")
    .update({
      payroll_excluded: excluded,
      payroll_excluded_at: excluded ? new Date().toISOString() : null,
      payroll_excluded_by: excluded ? excludedByProfileId : null,
      payroll_excluded_by_name: excluded ? excludedByName : null,
      // Manual always wins — a human explicitly deciding "off" should never
      // get silently re-held by the automatic no-photos rule afterward.
      payroll_hold_reason: excluded ? "manual" : null,
      // Opposite of payroll_excluded_at — stamped on release, cleared on
      // re-hold (see MileageEntry.payrollReleasedAt).
      payroll_released_at: excluded ? null : new Date().toISOString(),
    })
    .eq("id", id);
  if (error) throw new Error(error.message);
}

/**
 * Applies the "no photos uploaded yet → hold this ticket's pay" rule —
 * called from Accounting Dashboard's Mileage tab once its batch photo
 * check (hasTicketPhotos, storage.ts) resolves for a set of entries.
 * Never touches a row whose payroll_hold_reason is "manual" — that's a
 * human's call, not this rule's to make or unmake. Silent (no
 * notifications) since this can fire many times as photos trickle in;
 * the manual toggle's own notification flow stays exactly as it was.
 * Returns how many rows actually changed, for a status message.
 */
export async function reconcileMileageNoPhotoHolds(
  entries: { id: string; payrollExcluded: boolean; payrollHoldReason: "manual" | "no_photos" | null }[],
  hasPhotosByEntryId: Map<string, boolean>
): Promise<number> {
  let changed = 0;
  for (const entry of entries) {
    if (entry.payrollHoldReason === "manual") continue;
    const hasPhotos = hasPhotosByEntryId.get(entry.id);
    if (hasPhotos === undefined) continue;
    const shouldHold = !hasPhotos;
    const isCurrentlyAutoHeld = entry.payrollExcluded && entry.payrollHoldReason === "no_photos";
    if (shouldHold === isCurrentlyAutoHeld) continue;
    const { error } = await supabase
      .from("mileage_entries")
      .update({
        payroll_excluded: shouldHold,
        payroll_excluded_at: shouldHold ? new Date().toISOString() : null,
        payroll_excluded_by: null,
        payroll_excluded_by_name: shouldHold ? "Auto (no photos)" : null,
        payroll_hold_reason: shouldHold ? "no_photos" : null,
        payroll_released_at: shouldHold ? null : new Date().toISOString(),
      })
      .eq("id", entry.id);
    if (error) console.error(`reconcileMileageNoPhotoHolds (${entry.id}):`, error.message);
    else changed++;
  }
  return changed;
}

/**
 * Soft-deletes a mileage entry — see MileageEntry.deletedAt. The row stays
 * in place; getMileageEntries still returns it (so the Mileage tab can
 * keep showing it with a "Deleted" badge and a way to restore it), but
 * mileageDayRoute-style consumers should filter deletedAt out before
 * summing totals or building a route. Requires a reason, shown in the
 * audit trail the same way an adjustment note already is.
 */
export async function softDeleteMileageEntry(
  id: string,
  reason: string,
  deletedByProfileId: string | null,
  deletedByName: string | null
): Promise<void> {
  const { error } = await supabase
    .from("mileage_entries")
    .update({
      deleted_at: new Date().toISOString(),
      deleted_by: deletedByProfileId,
      deleted_by_name: deletedByName,
      delete_reason: reason.trim() || null,
    })
    .eq("id", id);
  if (error) throw new Error(error.message);
}

/** Reverses softDeleteMileageEntry — clears every deletion field, restoring the row to normal. */
export async function restoreMileageEntry(id: string): Promise<void> {
  const { error } = await supabase
    .from("mileage_entries")
    .update({ deleted_at: null, deleted_by: null, deleted_by_name: null, delete_reason: null })
    .eq("id", id);
  if (error) throw new Error(error.message);
}

/**
 * Coarse visit-order heuristic, shared by syncMileageFromTickets (below)
 * and the Day Route view: a time_slot's own leading number as its start
 * hour (e.g. "8-12" -> 8, "1-5" -> 1) — AM/PM isn't recorded, but this is
 * only used for RELATIVE ordering within one technician's one day, not an
 * absolute time, so the ambiguity doesn't matter here. A bare "AM"/"PM"
 * slot (no digits at all — seen in real ticket data alongside the numeric
 * ranges) sorts before/after every numeric range rather than at a specific
 * hour that could tie with (and then get arbitrarily reordered against) a
 * real numeric slot like "12-4". Missing/unparsable slots sort last of all.
 */
export function timeSlotStartHour(slot: unknown): number {
  const raw = String(slot || "").trim().toUpperCase();
  if (!raw) return Number.MAX_SAFE_INTEGER;
  if (raw === "AM") return -1;
  if (raw === "PM") return 13;
  const m = raw.match(/(\d{1,2})/);
  return m ? Number(m[1]) : Number.MAX_SAFE_INTEGER;
}

/** Orders tickets by timeSlotStartHour, breaking ties with created_at. */
export function sortStopsByHeuristic<T extends { time_slot?: unknown; created_at: string }>(tickets: T[]): T[] {
  return [...tickets].sort((a, b) => {
    const slotDiff = timeSlotStartHour(a.time_slot) - timeSlotStartHour(b.time_slot);
    if (slotDiff !== 0) return slotDiff;
    return String(a.created_at).localeCompare(String(b.created_at));
  });
}

/** One stop in a technician's day route — Day Route view's stop list/map. */
export interface MileageDayStop {
  ticketId: string;
  ticketNo: string;
  status: string | null;
  timeSlot: string | null;
  address: string;
  city: string | null;
  state: string | null;
  zip: string | null;
}

/**
 * Fetches this day's stops in visit order — the saved route_order if every
 * entry has one (a human has already sequenced this day), else the same
 * time-slot heuristic syncMileageFromTickets uses. Used to seed the Day
 * Route view's map/list before any reordering happens.
 */
export async function getMileageDayRouteStops(
  entries: { ticketId: string | null; routeOrder: number | null }[]
): Promise<MileageDayStop[]> {
  const ticketIds = entries.map((e) => e.ticketId).filter((id): id is string => !!id);
  if (ticketIds.length === 0) return [];
  const { data, error } = await supabase
    .from("tickets")
    .select("id, ticket_no, status, time_slot, created_at, customer:customers ( address, city, state, zip )")
    .in("id", ticketIds);
  if (error) throw new Error(error.message);
  const rows = (data ?? []) as any[];
  const allHaveOrder = entries.every((e) => e.routeOrder != null);
  const orderIndex = new Map(entries.map((e) => [e.ticketId, e.routeOrder]));
  const ordered = allHaveOrder
    ? [...rows].sort((a, b) => (orderIndex.get(a.id) ?? 0) - (orderIndex.get(b.id) ?? 0))
    : sortStopsByHeuristic(rows);
  return ordered.map((t: any) => {
    const customer = t.customer ?? {};
    return {
      ticketId: t.id,
      ticketNo: t.ticket_no,
      status: t.status ?? null,
      timeSlot: t.time_slot ?? null,
      address: customer.address ?? "",
      city: customer.city ?? null,
      state: customer.state ?? null,
      zip: customer.zip ?? null,
    };
  });
}

export interface MileageSyncResult {
  created: number;
  skipped: number;
  errors: string[];
  /** Tickets whose technician text didn't match ANY technician passed in —
   *  even after trim/lowercase. These still get synced (as profile_id:
   *  null, technician_name: the raw ticket text — see migration 0142),
   *  just surfaced separately so a real name mismatch is visible and
   *  fixable (e.g. fix that person's Display Name, or their role, so a
   *  future sync links their tickets to a real profile) instead of
   *  looking identical to any other synced entry. */
  unmatchedTechnicians: { name: string; count: number }[];
  /** How many technician-days actually got (re)processed this run — new
   *  tickets, moved tickets, AND days recalculated purely to backfill
   *  leg_mileage (see the hasMissingLegMileage check above). A run that
   *  only backfills existing days has `created === 0` but this is still
   *  > 0 — callers should refetch/refresh on this, not just on `created`. */
  recalculatedDays: number;
  /** True if `signal` was aborted before every day finished — everything
   *  counted above still genuinely happened/saved, this just means the run
   *  didn't reach the end of groupsToProcess. Re-running later (or clicking
   *  Sync again) picks up exactly where it left off — an unprocessed day
   *  still looks unprocessed, nothing was left half-written. */
  stopped: boolean;
}

/**
 * Auto-generates mileage entries from EVERY ticket assigned to a
 * technician — not just completed ones, since a drive happened regardless
 * of whether the job finished, is still open, or got cancelled after the
 * tech arrived. Still one row per ticket (so each ticket keeps its own
 * Photos/Hold/Send-message/link), but the total_mileage VALUE on every
 * ticket a technician had on a given day is the SAME number: that day's
 * full driving route — branch -> stop 1 -> stop 2 -> ... -> stop N -> home
 * address (or back to the branch if none on file) — not each ticket's own
 * independent distance from the branch. Stops within a day are ordered by
 * time_slot (then ticket creation time as a tiebreaker) since there's no
 * exact visit-sequence data to do better than that. See
 * computeDailyRouteMiles (mapEngine.ts) for the actual route math.
 *
 * Always all-time, no date range — every ticket this company has ever
 * logged. Safe to re-run: a day whose every ticket already has a row is
 * skipped entirely (no new API calls). A day where a NEW ticket joins
 * an already-partially-synced day gets its whole route recomputed and
 * EVERY ticket that day (new and pre-existing) is updated to the fresh
 * total — the route changed, so the old number on the earlier tickets is
 * now stale. Tickets with no schedule_date are skipped too
 * (mileage_entries.work_date is required — there's no date to log the
 * drive under).
 *
 * Matches tickets to technicians by NAME, case/whitespace-insensitive — same
 * convention as every other free-text technician match in this app (e.g.
 * AccountingDashboard.tsx's own Tech Payroll employeeByName resolution,
 * resolveTeamLeadOrManager's manager_name match). A ticket whose technician
 * text matches no known technician (wrong/legacy Display Name, or no User
 * Management account at all) still gets synced — profile_id: null,
 * technician_name: the raw ticket text (migration 0142) — rather than
 * silently dropped, so mileage isn't lost just because nobody's fixed that
 * person's profile yet. It's surfaced via unmatchedTechnicians either way.
 * Each unmatched name's tickets are still grouped/routed by day the same
 * way a matched technician's are — just keyed by their raw ticket text
 * instead of a profileId.
 */
export async function syncMileageFromTickets(input: {
  technicians: { profileId: string; fullName: string; branch: string; phone?: string; email?: string; homeAddress?: string }[];
  /** Called after each technician-day finishes recomputing (route lookups
   *  are the slow part — one per day that needs (re)processing, awaited in
   *  sequence below) — lets the caller show live progress instead of one
   *  opaque spinner for however long the whole run takes. `total` is fixed
   *  once known (right before the loop starts); `done` counts up to it. */
  onProgress?: (done: number, total: number) => void;
  /** Checked between technician-days (not mid-day — a day's own route
   *  lookups always finish once started, so a partial/half-saved day never
   *  happens) — when aborted, the loop stops early and returns whatever
   *  was already saved rather than throwing, since every write up to that
   *  point already committed and shouldn't be treated as a failure. */
  signal?: AbortSignal;
}): Promise<MileageSyncResult> {
  const result: MileageSyncResult = { created: 0, skipped: 0, errors: [], unmatchedTechnicians: [], recalculatedDays: 0, stopped: false };
  const techByNormalizedName = new Map(
    input.technicians.filter((t) => t.fullName.trim()).map((t) => [t.fullName.trim().toLowerCase(), t])
  );
  if (techByNormalizedName.size === 0) return result;

  const [{ data: ticketRows, error: ticketsErr }, { data: existingRows, error: existingErr }, mapProvider] = await Promise.all([
    // Always all-time, no date range — every ticket this company has ever
    // logged. Page through in chunks of 1000 instead of one unbounded select.
    (async () => {
      const all: any[] = [];
      for (let from = 0; ; from += PAGE_SIZE) {
        const { data, error } = await supabase
          .from("tickets")
          .select("id, ticket_no, technician, status, schedule_date, time_slot, created_at, location, account, customer:customers ( address, address2, city, state, zip, phone, email )")
          .not("technician", "is", null)
          .range(from, from + PAGE_SIZE - 1);
        if (error) return { data: null, error };
        all.push(...(data ?? []));
        if (!data || data.length < PAGE_SIZE) break;
      }
      return { data: all, error: null };
    })(),
    supabase
      .from("mileage_entries")
      .select("id, ticket_id, total_mileage, leg_mileage, work_date, profile_id, technician_name")
      .eq("source", "auto")
      .not("ticket_id", "is", null),
    getCompanyMapProvider(),
  ]);
  if (ticketsErr) {
    result.errors.push(`Failed to load tickets: ${ticketsErr.message}`);
    return result;
  }
  if (existingErr) console.error("syncMileageFromTickets (existing sync check) error:", existingErr.message);

  // Identity for a technician name: the real profile id when it resolves to
  // a known technician, else the raw ticket text itself (lowercased) — kept
  // symmetric between "current" (from the ticket, below) and "stored" (from
  // an existing row, below) so the two are directly comparable. Comparing by
  // id rather than name for matched technicians also means a later display-
  // name change alone never looks like a reassignment.
  const identityFor = (rawName: string): string => {
    const trimmed = rawName.trim();
    const matched = techByNormalizedName.get(trimmed.toLowerCase());
    return matched ? `id:${matched.profileId}` : `name:${trimmed.toLowerCase()}`;
  };

  const existingByTicketId = new Map(
    (existingRows ?? []).map((r: any) => [
      r.ticket_id as string,
      {
        id: r.id as string,
        totalMileage: Number(r.total_mileage) || 0,
        hasLegMileage: r.leg_mileage != null,
        workDate: r.work_date as string,
        identity: r.profile_id ? `id:${r.profile_id}` : `name:${String(r.technician_name || "").trim().toLowerCase()}`,
      },
    ])
  );

  // Every ticket with a technician assigned and an actual date to log the
  // drive under — status doesn't matter, an open/cancelled ticket still
  // involved a real drive.
  const allAssignedTickets = (ticketRows ?? []).filter(
    (t: any) => String(t.technician || "").trim() && t.schedule_date
  );

  // Anyone whose tickets carry a technician name that isn't a known
  // technician, even after trim/lowercase — still synced below (as an
  // unlinked, profile_id: null entry), just surfaced separately so a real
  // name mismatch is visible and fixable rather than looking like any other
  // synced entry.
  const unmatchedCounts = new Map<string, number>();
  for (const t of allAssignedTickets as any[]) {
    const name = String(t.technician).trim();
    if (!techByNormalizedName.has(name.toLowerCase())) {
      unmatchedCounts.set(name, (unmatchedCounts.get(name) ?? 0) + 1);
    }
  }
  result.unmatchedTechnicians = Array.from(unmatchedCounts.entries())
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count);

  // Group EVERY assigned ticket (already-synced AND pending) by its CURRENT
  // (technician identity, work date) — a day's route depends on ALL of that
  // day's stops, not just the ones that happen to be new, so an
  // already-partially-synced day still needs its full stop list to
  // recompute correctly once a new ticket joins it. Using CURRENT values
  // means a rescheduled or reassigned ticket lands in its NEW day/
  // technician's group here, not its old one.
  const groups = new Map<string, any[]>();
  for (const t of allAssignedTickets as any[]) {
    const key = `${identityFor(String(t.technician))}|${t.schedule_date}`;
    const list = groups.get(key) ?? [];
    list.push(t);
    groups.set(key, list);
  }

  // A group needs (re)processing if a ticket is new (no row yet) or just
  // moved IN (its existing row is still stored under a different day/
  // technician). Separately, a group can also need processing purely
  // because it lost a ticket that moved OUT — its remaining tickets are all
  // otherwise unchanged, so neither of the above catches it; detected by
  // comparing, per stored (identity, date) key, the ticket ids an existing
  // row claims against the ticket ids that key's CURRENT group actually has.
  const currentTicketIdsByKey = new Map<string, Set<string>>();
  for (const [key, tickets] of groups) currentTicketIdsByKey.set(key, new Set(tickets.map((t) => t.id)));
  const keysThatLostATicket = new Set<string>();
  for (const [ticketId, existing] of existingByTicketId) {
    const storedKey = `${existing.identity}|${existing.workDate}`;
    if (!(currentTicketIdsByKey.get(storedKey)?.has(ticketId) ?? false)) keysThatLostATicket.add(storedKey);
  }

  const groupsToProcess = Array.from(groups.entries())
    .filter(([key, tickets]) => {
      const hasNewOrMovedInTicket = tickets.some((t) => {
        const existing = existingByTicketId.get(t.id);
        if (!existing) return true;
        return `${existing.identity}|${existing.workDate}` !== key;
      });
      // Backfill: a day fully synced before leg_mileage existed (migration
      // 0210) has every row's total_mileage already correct, so neither
      // check above would ever re-touch it — without this it would stay
      // stuck showing "—" in the Mileage tab's This Stop column forever,
      // since nothing about the day's tickets ever actually changes.
      const hasMissingLegMileage = tickets.some((t) => !existingByTicketId.get(t.id)?.hasLegMileage);
      return hasNewOrMovedInTicket || keysThatLostATicket.has(key) || hasMissingLegMileage;
    })
    .map(([, tickets]) => tickets);
  const untouchedTicketCount = allAssignedTickets.length - groupsToProcess.reduce((s, g) => s + g.length, 0);
  result.skipped = untouchedTicketCount;
  result.recalculatedDays = groupsToProcess.length;

  input.onProgress?.(0, groupsToProcess.length);
  for (let groupIdx = 0; groupIdx < groupsToProcess.length; groupIdx++) {
    if (input.signal?.aborted) {
      result.stopped = true;
      result.recalculatedDays = groupIdx; // only what actually got processed before stopping
      break;
    }
    // finally, not just an end-of-body call — every early `continue` below
    // (route lookup failed/threw) still needs to advance the progress
    // count, or it visibly stalls instead of just moving past a skipped day.
    try {
    const groupTickets = groupsToProcess[groupIdx];
    const orderedTickets = sortStopsByHeuristic(groupTickets);

    const rawName = String(orderedTickets[0].technician).trim();
    const technician = techByNormalizedName.get(rawName.toLowerCase()) ?? null;
    const branch = orderedTickets[0].location || technician?.branch || "Unassigned";
    const routeStops: MileageTicketInput[] = orderedTickets.map((t) => {
      const customer = t.customer ?? {};
      return { location: t.location, city: customer.city, address: customer.address, state: customer.state, zip: customer.zip, account: t.account };
    });

    let routeResult: DailyRouteMilesResult | null = null;
    try {
      routeResult = await computeDailyRouteMiles(branch, routeStops[0], routeStops, technician?.homeAddress, mapProvider);
    } catch (err) {
      result.errors.push(`${orderedTickets[0].schedule_date} (${rawName}): ${err instanceof Error ? err.message : "route lookup failed"}`);
      continue;
    }
    if (routeResult === null) {
      result.errors.push(`${orderedTickets[0].schedule_date} (${rawName}): no route found — skipped.`);
      continue;
    }
    const roundedMiles = Math.round(routeResult.totalMiles * 10) / 10;
    // legMiles is index-aligned with orderedTickets/routeStops — this
    // ticket's own leg (previous stop -> this stop, home leg folded into
    // the day's last stop), null if it couldn't be geocoded. Purely a
    // display breakdown; roundedMiles (the day total) is still what
    // payroll reads, unaffected by this.
    const legMileageAt = (idx: number): number | null => {
      const m = routeResult!.legMiles[idx];
      return m != null ? Math.round(m * 10) / 10 : null;
    };

    // Refresh every already-synced ticket in this group — a new stop
    // joined, so the whole day's route (and therefore every existing
    // row's total) is potentially stale, even if this particular round
    // happens to land on the same number as before. Also clears
    // route_order: a human-set stop order no longer describes this day
    // now that its stop list has changed, so it resets to the automatic
    // heuristic (used above) rather than silently keeping a sequence that
    // doesn't include the new stop. work_date/profile_id/technician_name/
    // branch are re-set to this group's own values too — a no-op for a
    // ticket that was already here, but for one that just got rescheduled
    // or reassigned, this is what actually MOVES its row onto the new day
    // / new technician rather than leaving it stale under the old ones.
    for (let idx = 0; idx < orderedTickets.length; idx++) {
      const t = orderedTickets[idx];
      const existing = existingByTicketId.get(t.id);
      if (existing) {
        const { error: updateErr } = await supabase
          .from("mileage_entries")
          .update({
            total_mileage: roundedMiles,
            leg_mileage: legMileageAt(idx),
            route_order: null,
            route_return_to: null,
            work_date: t.schedule_date,
            profile_id: technician?.profileId ?? null,
            technician_name: technician ? null : rawName,
            branch,
          })
          .eq("id", existing.id);
        if (updateErr) result.errors.push(`Ticket ${t.ticket_no}: failed to refresh mileage — ${updateErr.message}`);
      }
    }

    const newTickets = orderedTickets.filter((t) => !existingByTicketId.has(t.id));
    for (const ticket of newTickets) {
      const customer = ticket.customer ?? {};
      const fullAddress = [customer.address, customer.address2, [customer.city, customer.state].filter(Boolean).join(", "), customer.zip]
        .filter((part: unknown) => typeof part === "string" && part.trim())
        .join(", ");
      const googleMapLink = fullAddress
        ? `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(fullAddress)}`
        : "";

      const { error: insertErr } = await supabase.from("mileage_entries").insert({
        profile_id: technician?.profileId ?? null,
        technician_name: technician ? null : rawName,
        branch,
        work_date: ticket.schedule_date,
        // The technician's OWN contact info, not the customer's — Address/
        // Contact Number/Email here answer "who drove and how do we reach
        // them," which the customer's job-site details never were. Google
        // Map Link below still points at the customer's site (for driving
        // directions there), unaffected by this.
        address: technician?.homeAddress || "(no address on file)",
        contact_number: technician?.phone || null,
        email: technician?.email || null,
        total_mileage: roundedMiles,
        leg_mileage: legMileageAt(orderedTickets.indexOf(ticket)),
        google_map_link: googleMapLink || null,
        created_by_name: "Auto-sync",
        ticket_id: ticket.id,
        ticket_no: ticket.ticket_no,
        ticket_status: ticket.status,
        source: "auto",
      });
      if (insertErr) {
        // Unique-violation on ticket_id means another sync run already logged
        // it a moment ago (race) — treat as skipped, not a real failure.
        if (insertErr.code === "23505") result.skipped++;
        else result.errors.push(`Ticket ${ticket.ticket_no}: ${insertErr.message}`);
        continue;
      }
      result.created++;
    }
    } finally {
      input.onProgress?.(groupIdx + 1, groupsToProcess.length);
    }
  }

  return result;
}

/**
 * Recomputes one technician's one day of driving with a HUMAN-CHOSEN stop
 * order (the Day Route view's drag/reorder controls) instead of the
 * automatic time-slot heuristic, and saves both the new total and each
 * row's route_order (its index in orderedTicketIds) so the order sticks
 * until either a human changes it again or a new ticket joins that day
 * (which resets it — see syncMileageFromTickets). Throws rather than
 * returning null on failure so the UI can show a real error instead of
 * silently leaving the old total in place.
 */
export async function recalculateMileageDayRoute(input: {
  /** This day's existing mileage_entries rows — id + the ticket each one is for. */
  entries: { id: string; ticketId: string }[];
  /** The new visit order, by ticket id — must cover every ticket in entries. */
  orderedTicketIds: string[];
  branch: string;
  homeAddress?: string;
  /** "home" routes the final leg to homeAddress (falls back to branch
   *  anyway if that's blank); "branch" forces a branch-return route even
   *  when a home address exists. Saved as route_return_to on every row. */
  returnTo: "home" | "branch";
}): Promise<number> {
  const { data: ticketRows, error: ticketsErr } = await supabase
    .from("tickets")
    .select("id, location, account, customer:customers ( address, city, state, zip )")
    .in("id", input.orderedTicketIds);
  if (ticketsErr) throw new Error(ticketsErr.message);
  const ticketById = new Map((ticketRows ?? []).map((t: any) => [t.id, t]));

  const orderedStops: MileageTicketInput[] = input.orderedTicketIds.map((id) => {
    const t = ticketById.get(id);
    const customer = t?.customer ?? {};
    return { location: t?.location, city: customer.city, address: customer.address, state: customer.state, zip: customer.zip, account: t?.account };
  });
  if (orderedStops.length === 0) throw new Error("No stops to route.");

  const mapProvider = await getCompanyMapProvider();
  const effectiveHomeAddress = input.returnTo === "home" ? input.homeAddress : undefined;
  const routeResult = await computeDailyRouteMiles(input.branch, orderedStops[0], orderedStops, effectiveHomeAddress, mapProvider);
  if (routeResult === null) throw new Error("No route found for this stop order.");
  const roundedMiles = Math.round(routeResult.totalMiles * 10) / 10;

  const orderIndexByTicketId = new Map(input.orderedTicketIds.map((id, idx) => [id, idx]));
  for (const entry of input.entries) {
    const idx = orderIndexByTicketId.get(entry.ticketId);
    const legMiles = idx != null ? routeResult.legMiles[idx] : null;
    const { error } = await supabase
      .from("mileage_entries")
      .update({
        total_mileage: roundedMiles,
        leg_mileage: legMiles != null ? Math.round(legMiles * 10) / 10 : null,
        route_order: idx ?? null,
        route_return_to: input.returnTo,
      })
      .eq("id", entry.id);
    if (error) throw new Error(`Failed to save ticket order: ${error.message}`);
  }
  return roundedMiles;
}

/**
 * Sets (or clears, when both override and adjustment are null) Finance's
 * manual correction to a day's mileage total — see mileageEffectiveTotal.
 * Applied identically across every row of the (technician, work_date)
 * group, same as total_mileage itself is shared, so the effective total
 * reads the same no matter which of that day's tickets you're looking at.
 */
export async function setMileageDayAdjustment(input: {
  entryIds: string[];
  override: number | null;
  adjustment: number | null;
  note: string | null;
  byProfileId: string | null;
  byName: string | null;
}): Promise<void> {
  const hasAdjustment = input.override != null || input.adjustment != null;
  const { error } = await supabase
    .from("mileage_entries")
    .update({
      mileage_override: input.override,
      mileage_adjustment: input.adjustment,
      adjustment_note: input.note,
      adjusted_by: hasAdjustment ? input.byProfileId : null,
      adjusted_by_name: hasAdjustment ? input.byName : null,
      adjusted_at: hasAdjustment ? new Date().toISOString() : null,
    })
    .in("id", input.entryIds);
  if (error) throw new Error(error.message);
}
