/**
 * Employee Self-Service tour (Guides → Self-Service Guide, and the Tour
 * button on the page). Selectors point at data-tour labels on
 * src/components/EmployeeSelfServicePage.tsx and the header clock
 * (TimeClockMenu). Tabs: dashboard | payroll | attendance | requests.
 */
import type { TourDef } from "./runTour";

/** Where queueTour() hands this tour to the page. */
export const SELF_SERVICE_TOUR_TARGET = "page:employee-self-service";

export const SELF_SERVICE_TOUR: TourDef = {
  id: "employee-self-service",
  title: "Employee Self-Service",
  summary: "Your clock, payslips and attendance, how to request PTO, sick leave, a time correction or unpaid leave, and where to track them.",
  steps: [
    {
      selector: '[data-tour="time-clock"]',
      title: "Your time clock",
      text: "Time In, Meal In / Meal Out and Time Out, always at the top of the page. Technicians and branch leaders enter today's code from HR to Time In.",
    },
    {
      selector: '[data-tour="ess-tabs"]',
      title: "Four tabs",
      text: "My Dashboard, My Payroll, My Attendance and My Requests.",
    },
    {
      selector: '[data-tour="ess-summary"]',
      title: "At a glance",
      text: "Your latest net pay and your leave balance at a glance.",
      tab: "dashboard",
    },
    {
      selector: '[data-tour="ess-view-payslip"]',
      title: "Your payslip",
      text: "Opens your latest payslip — gross pay, deductions, net pay and overtime. You can download it from there.",
      tab: "payroll",
    },
    {
      selector: '[data-tour="ess-payroll-history"]',
      title: "Earlier payslips",
      text: "Every previous pay period — open any of them.",
      tab: "payroll",
    },
    {
      selector: '[data-tour="ess-att-views"]',
      title: "Your attendance",
      text: "Daily shows your clock in and out for the last 30 days. Login/Logout History shows when you signed in to AHS.",
      tab: "attendance",
    },
    {
      selector: '[data-tour="ess-att-download"]',
      title: "Download",
      text: "Download your attendance list.",
      tab: "attendance",
    },
    {
      selector: '[data-tour="ess-req-summary"]',
      title: "Leave balances and request status",
      text: "PTO and sick leave left this year, and your requests by status. Click a tile to see the list behind it.",
      tab: "requests",
    },
    {
      selector: '[data-tour="ess-req-pto"]',
      title: "PTO Request",
      text: "For paid time off. You need 1 year with the company first — until then it stays greyed out. Here's what the form asks for:",
      tab: "requests",
    },
    {
      selector: '[data-tour="ess-form-leave-type"]',
      title: "PTO: leave type",
      text: "Vacation.",
      tab: "requests",
      panel: "pto",
      side: "left",
    },
    {
      selector: '[data-tour="ess-form-position"]',
      title: "PTO: position and branch",
      text: "Filled in from your profile — check they're right.",
      tab: "requests",
      panel: "pto",
      side: "left",
    },
    {
      selector: '[data-tour="ess-form-dates"]',
      title: "PTO: first and last day",
      text: "Your scheduled rest days in between aren't counted, and you can't ask for more days than you have left.",
      tab: "requests",
      panel: "pto",
      side: "left",
    },
    {
      selector: '[data-tour="ess-form-reason"]',
      title: "PTO: details",
      text: "Anything your manager should know.",
      tab: "requests",
      panel: "pto",
      side: "left",
    },
    {
      selector: '[data-tour="ess-form-submit"]',
      title: "PTO: submit",
      text: "Submit sends it for approval; Cancel closes without sending. (The tour never submits.)",
      tab: "requests",
      panel: "pto",
      side: "left",
    },
    {
      selector: '[data-tour="ess-req-sick"]',
      title: "Sick Leave Request",
      text: "When you're sick. Limited to the sick days you have left this year. Inside the form:",
      tab: "requests",
    },
    {
      selector: '[data-tour="ess-form-dates"]',
      title: "Sick leave: dates",
      text: "First and last sick day. Rest days aren't counted.",
      tab: "requests",
      panel: "sick",
      side: "left",
    },
    {
      selector: '[data-tour="ess-form-issue"]',
      title: "Sick leave: exception type",
      text: "Pick what kind of absence it was.",
      tab: "requests",
      panel: "sick",
      side: "left",
    },
    {
      selector: '[data-tour="ess-form-reason"]',
      title: "Sick leave: reason",
      text: "Describe what happened — this is required.",
      tab: "requests",
      panel: "sick",
      side: "left",
    },
    {
      selector: '[data-tour="ess-form-sign-leave"]',
      title: "Sick leave: sign",
      text: "Sign to confirm it's accurate, then Submit.",
      tab: "requests",
      panel: "sick",
      side: "left",
    },
    {
      selector: '[data-tour="ess-req-correction"]',
      title: "Time Correction",
      text: "For a forgotten or wrong punch. Inside the form:",
      tab: "requests",
    },
    {
      selector: '[data-tour="ess-form-corr-date"]',
      title: "Correction: the day",
      text: "Today or an earlier day — not a future date.",
      tab: "requests",
      panel: "correction",
      side: "left",
    },
    {
      selector: '[data-tour="ess-form-corr-times"]',
      title: "Correction: check in and out",
      text: "Both the correct check in and check out are required.",
      tab: "requests",
      panel: "correction",
      side: "left",
    },
    {
      selector: '[data-tour="ess-form-corr-meal"]',
      title: "Correction: meal break",
      text: "Required when the shift is over 6 hours; optional for shorter shifts.",
      tab: "requests",
      panel: "correction",
      side: "left",
    },
    {
      selector: '[data-tour="ess-form-issue"]',
      title: "Correction: issue",
      text: "What went wrong — e.g. forgot to clock in. For Other, say what it was.",
      tab: "requests",
      panel: "correction",
      side: "left",
    },
    {
      selector: '[data-tour="ess-form-reason"]',
      title: "Correction: reason",
      text: "Explain the correction — required.",
      tab: "requests",
      panel: "correction",
      side: "left",
    },
    {
      selector: '[data-tour="ess-form-sign"]',
      title: "Correction: sign",
      text: "Sign to confirm, then Submit. It goes for approval, and you can follow it in Track Status.",
      tab: "requests",
      panel: "correction",
      side: "left",
    },
    {
      selector: '[data-tour="ess-req-unpaid"]',
      title: "Unpaid Leave Request",
      text: "Time off without pay. Inside the form:",
      tab: "requests",
    },
    {
      selector: '[data-tour="ess-form-dates"]',
      title: "Unpaid leave: dates",
      text: "First and last day off.",
      tab: "requests",
      panel: "unpaidLeave",
      side: "left",
    },
    {
      selector: '[data-tour="ess-form-reason"]',
      title: "Unpaid leave: reason",
      text: "Why you need the time — required.",
      tab: "requests",
      panel: "unpaidLeave",
      side: "left",
    },
    {
      selector: '[data-tour="ess-form-sign-leave"]',
      title: "Unpaid leave: sign",
      text: "Sign to confirm, then Submit.",
      tab: "requests",
      panel: "unpaidLeave",
      side: "left",
    },
    {
      selector: '[data-tour="ess-track-status"]',
      title: "Track your requests",
      text: "Every request you've sent and where it is. Filter by type. If one is rejected, the reason shows here.",
      tab: "requests",
      side: "top",
    },
  ],
};
