-- Run this AFTER staff_list_backfill.sql to see which of the 182
-- active Excel people have no matching profile (so nothing was backfilled
-- for them) — each missing name means either a spelling mismatch against
-- their real display_name, or they don't have a system account yet.
select v.name, v.branch
from (values
  ('Matt Simmons', 'Asheville'),
  ('Jordan Koetsier', 'Asheville'),
  ('Johnathan Wesley Allen', 'Asheville'),
  ('Matt Simmons', 'Atlanta'),
  ('Kevin Khaiphanliane', 'Atlanta'),
  ('Abraham Im', 'Atlanta'),
  ('Joshua Silva', 'Atlanta'),
  ('Gerrell Berg', 'Atlanta'),
  ('Abel Severino', 'Atlanta'),
  ('Nathan Napora', 'Atlanta'),
  ('Erin Williams', 'Atlanta'),
  ('Calvin Nguyen', 'Atlanta'),
  ('Anna Seo', 'Atlanta'),
  ('Naveen Lakhani', 'Atlanta'),
  ('Seth Smith', 'Atlanta'),
  ('danny thornton', 'Birmingham'),
  ('David Sims', 'Birmingham'),
  ('Andy Oh', 'Birmingham'),
  ('Zonate Grant', 'Birmingham'),
  ('Daven Hodge', 'Cape Girardeau'),
  ('Matthew Nichols', 'Cape Girardeau'),
  ('Deprece Harris', 'Cape Girardeau'),
  ('Alaska Grace Olinger', 'Cape Girardeau'),
  ('Triston Mitchell', 'Cape Girardeau'),
  ('Alaska Olinger', 'Cape Girardeau'),
  ('Christian Andrews', 'Chattanooga'),
  ('Jacob Blackburn', 'Chattanooga'),
  ('Austin Ferguson', 'Chattanooga'),
  ('Ashley Cowart', 'Chattanooga'),
  ('matt simmons', 'Columbus'),
  ('A''dejuan Tyson', 'Columbus'),
  ('Percy Smith Jr', 'Columbus'),
  ('Amanda Simmons', 'Columbus'),
  ('Fredrick Jackson', 'Columbus'),
  ('danny thornton', 'Destin'),
  ('Garrett McCarley', 'Destin'),
  ('Lamar Hudson', 'Destin'),
  ('Lashamus Dowell', 'Huntsville'),
  ('Jordan Stanley', 'Huntsville'),
  ('Adam Humphrey', 'Huntsville'),
  ('Kyle Arscott', 'Huntsville'),
  ('Abdul-Rahman Abdullah', 'Huntsville'),
  ('Zackery Ridley', 'Huntsville'),
  ('Nathan Wagner', 'Huntsville'),
  ('Illiana De Leon', 'Huntsville'),
  ('Cashawn Ford', 'Huntsville'),
  ('LaShamus Dowell', 'Jonesboro'),
  ('danny thornton', 'Jonesboro'),
  ('derrick sargent', 'Jonesboro'),
  ('Farris Bruce', 'Jonesboro'),
  ('Isaac Booth', 'Jonesboro'),
  ('Danny Thornton', 'Jackson, MS'),
  ('Danny Thornton', 'Jackson, MS'),
  ('Anthony Cavett', 'Jackson, MS'),
  ('Mikkel Brown', 'Jackson, MS'),
  ('tywon ross', 'Jackson, MS'),
  ('Reginald Stewart', 'Jackson, MS'),
  ('jeremie nichols', 'Jackson, MS'),
  ('mainza houston', 'Jackson, MS'),
  ('Derious Nichols', 'Jackson, MS'),
  ('Terry Davis', 'Jackson, MS'),
  ('LaShamus Dowell', 'Jackson, TN'),
  ('Lashamus Dowell', 'Jackson, TN'),
  ('James Dickerson', 'Jackson, TN'),
  ('Garrison Brown', 'Jackson, TN'),
  ('Martwain Johnston', 'Jackson, TN'),
  ('Cameron Forrest', 'Jackson, TN'),
  ('Matt Simmons', 'Jacksonville'),
  ('Zakarya Moradi', 'Jacksonville'),
  ('Bradley Hollowell', 'Jacksonville'),
  ('Jacob Reed', 'Jacksonville'),
  ('Farahnaz Qasemi', 'Jacksonville'),
  ('Lashamus Dowell', 'Knoxville'),
  ('Alex Myles', 'Knoxville'),
  ('Zac Coisman', 'Knoxville'),
  ('James Dech', 'Knoxville'),
  ('James Houston', 'Knoxville'),
  ('Joshua Rinehart', 'Knoxville'),
  ('Danny Thornton', 'Little Rock'),
  ('Danny Thornton', 'Little Rock'),
  ('andre riddle', 'Little Rock'),
  ('nocona detten', 'Little Rock'),
  ('Blake Shinn', 'Little Rock'),
  ('john boyette', 'Little Rock'),
  ('Danny Thornton', 'Lake Charles'),
  ('Danny Thornton', 'Lake Charles'),
  ('cooper shaffett', 'Lake Charles'),
  ('dylan deeb', 'Lake Charles'),
  ('christian schexnayder', 'Lake Charles'),
  ('Lashamus Dowell', 'Memphis'),
  ('Sean Anthony Smith', 'Memphis'),
  ('Darrin Michael Stewart', 'Memphis'),
  ('Darryel Burdette', 'Memphis'),
  ('Jeffrey Allen Lucas, Jr.', 'Memphis'),
  ('Rico Ali Jah Juan Shaw', 'Memphis'),
  ('Matthew Nichols', 'Memphis'),
  ('Annan Odongo', 'Memphis'),
  ('Arnulfo Jr Pongos Montesclaros', 'Memphis'),
  ('Christian Reynes', 'Memphis'),
  ('Denver Memije', 'Memphis'),
  ('Ian Isidro Montesclaros', 'Memphis'),
  ('Ken Ubay', 'Memphis'),
  ('Marie Frances Javier', 'Memphis'),
  ('Mharlet Linchangco', 'Memphis'),
  ('Lou Marie Kate Basco', 'Memphis'),
  ('Jhennelyn Mae Anne Nato', 'Memphis'),
  ('Robyn Mae Heredia', 'Memphis'),
  ('Shane Marie Rebadomoa', 'Memphis'),
  ('Daniela Mercado', 'Memphis'),
  ('Airiz Teo Diamona', 'Memphis'),
  ('Angelica Dandan', 'Memphis'),
  ('Anne Murray Lorico', 'Memphis'),
  ('Cathrina Sta.Maria', 'Memphis'),
  ('Jo-Ann Lazarte', 'Memphis'),
  ('Louie Bayani', 'Memphis'),
  ('Ma. Czarina Lagumen', 'Memphis'),
  ('Maribeth Gazmen Unciano', 'Memphis'),
  ('Mary Grace Cosio', 'Memphis'),
  ('Patrick Mitchell Tendero', 'Memphis'),
  ('Rochelle Ann Ortiz', 'Memphis'),
  ('Wincel Franz Carusca', 'Memphis'),
  ('landon cogill', 'Memphis'),
  ('danny thornton', 'Mobile'),
  ('Dominic Holman', 'Mobile'),
  ('Ryan Madison', 'Mobile'),
  ('Lauren Andrews', 'Mobile'),
  ('Jacob Samuel Reed', 'Mobile'),
  ('Matt Simmons', 'Montgomery'),
  ('Leon Marsh', 'Montgomery'),
  ('John Godfrey', 'Nashville'),
  ('Justin Robertson', 'Nashville'),
  ('Juliannah Caviness-Ferguson', 'Nashville'),
  ('Leo Sun', 'Nashville'),
  ('Lashamus Dowell', 'New Orleans'),
  ('Joseph Wease', 'New Orleans'),
  ('cole mushinsky', 'New Orleans'),
  ('Charles Fontenot', 'New Orleans'),
  ('caleb french', 'New Orleans'),
  ('shannon thomas', 'New Orleans'),
  ('ryder tourere', 'New Orleans'),
  ('Matt Simmons', 'Norfolk'),
  ('Chris Simpson', 'Norfolk'),
  ('Edward (Aiden) Lindsey', 'Norfolk'),
  ('Brandi Janell Smith', 'Norfolk'),
  ('Matt Simmons', 'Richmond'),
  ('Chris Simpson', 'Richmond'),
  ('Kolby fleck', 'Richmond'),
  ('Matt Simmons', 'Raleigh'),
  ('Alexxis Henry', 'Raleigh'),
  ('Marc James', 'Raleigh'),
  ('Joshua Williamson', 'Raleigh'),
  ('Javier Camel', 'Raleigh'),
  ('Mason Redker', 'Raleigh'),
  ('danny thornton', 'San Antonio'),
  ('Erick Guzman', 'San Antonio'),
  ('Matt Simmons', 'Savannah'),
  ('Lance Jonathon Novak', 'Savannah'),
  ('Chris Kennelley', 'Savannah'),
  ('Christopher Alvarado', 'Savannah'),
  ('Lashamus Dowell', 'St. Louis'),
  ('Derious Nichols', 'St. Louis'),
  ('Jacob Rhodes', 'St. Louis'),
  ('Crystal Dziedzic', 'St. Louis'),
  ('ROY REED', 'St. Louis'),
  ('CALEB BROWN', 'St. Louis'),
  ('TYRELL FOSTER', 'St. Louis'),
  ('JAMESE LOVE', 'St. Louis'),
  ('Daryl Hughes', 'St. Louis'),
  ('Darius Green', 'St. Louis'),
  ('Daryl Hughes', 'St. Louis'),
  ('dannyn thornton', 'Tallahassee'),
  ('Matthew James McCrary', 'Tallahassee'),
  ('Krista Griffiss-Gonatos', 'Tallahassee'),
  ('Matt Simmons', 'Wilmington'),
  ('Brye''Shawn Butler', 'Wilmington'),
  ('Justin Alvarez', 'Wilmington'),
  ('Jordan Davis', 'Wilmington'),
  ('Josh Malloch', 'Wilmington'),
  ('David Lopez', 'Wilmington'),
  ('Malik Kaazim-Johnson', 'Wilmington'),
  ('Javier Hernandez', 'Wilmington'),
  ('Michael Whitley', 'Wilmington')
) as v(name, branch)
where not exists (
  select 1 from profiles where lower(trim(display_name)) = lower(trim(v.name))
);
