/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimecardRouteImport } from './routes/timecard'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicepowerTestRouteImport } from './routes/servicepower-test'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FirebaseSetupRouteImport } from './routes/firebase-setup'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketTicketNoRouteImport } from './routes/ticket.$ticketNo'
import { Route as MModuleRouteImport } from './routes/m.$module'
import { Route as EmployeeEmployeeIdRouteImport } from './routes/employee.$employeeId'
import { Route as ApiServicepowerRouteImport } from './routes/api/servicepower'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as MModuleSubmoduleRouteImport } from './routes/m.$module.$submodule'
import { Route as CsrMistakeEmployeeIdRouteImport } from './routes/csr.mistake.$employeeId'
import { Route as MModuleSubmoduleUserIdRouteImport } from './routes/m.$module.$submodule.$userId'

const TimecardRoute = TimecardRouteImport.update({
  id: '/timecard',
  path: '/timecard',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicepowerTestRoute = ServicepowerTestRouteImport.update({
  id: '/servicepower-test',
  path: '/servicepower-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FirebaseSetupRoute = FirebaseSetupRouteImport.update({
  id: '/firebase-setup',
  path: '/firebase-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketTicketNoRoute = TicketTicketNoRouteImport.update({
  id: '/ticket/$ticketNo',
  path: '/ticket/$ticketNo',
  getParentRoute: () => rootRouteImport,
} as any)
const MModuleRoute = MModuleRouteImport.update({
  id: '/m/$module',
  path: '/m/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeEmployeeIdRoute = EmployeeEmployeeIdRouteImport.update({
  id: '/employee/$employeeId',
  path: '/employee/$employeeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServicepowerRoute = ApiServicepowerRouteImport.update({
  id: '/api/servicepower',
  path: '/api/servicepower',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const MModuleSubmoduleRoute = MModuleSubmoduleRouteImport.update({
  id: '/$submodule',
  path: '/$submodule',
  getParentRoute: () => MModuleRoute,
} as any)
const CsrMistakeEmployeeIdRoute = CsrMistakeEmployeeIdRouteImport.update({
  id: '/csr/mistake/$employeeId',
  path: '/csr/mistake/$employeeId',
  getParentRoute: () => rootRouteImport,
} as any)
const MModuleSubmoduleUserIdRoute = MModuleSubmoduleUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => MModuleSubmoduleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/firebase-setup': typeof FirebaseSetupRoute
  '/home': typeof HomeRoute
  '/landing': typeof LandingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/servicepower-test': typeof ServicepowerTestRoute
  '/settings': typeof SettingsRoute
  '/superadmin': typeof SuperadminRoute
  '/timecard': typeof TimecardRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/servicepower': typeof ApiServicepowerRoute
  '/employee/$employeeId': typeof EmployeeEmployeeIdRoute
  '/m/$module': typeof MModuleRouteWithChildren
  '/ticket/$ticketNo': typeof TicketTicketNoRoute
  '/csr/mistake/$employeeId': typeof CsrMistakeEmployeeIdRoute
  '/m/$module/$submodule': typeof MModuleSubmoduleRouteWithChildren
  '/m/$module/$submodule/$userId': typeof MModuleSubmoduleUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/firebase-setup': typeof FirebaseSetupRoute
  '/home': typeof HomeRoute
  '/landing': typeof LandingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/servicepower-test': typeof ServicepowerTestRoute
  '/settings': typeof SettingsRoute
  '/superadmin': typeof SuperadminRoute
  '/timecard': typeof TimecardRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/servicepower': typeof ApiServicepowerRoute
  '/employee/$employeeId': typeof EmployeeEmployeeIdRoute
  '/m/$module': typeof MModuleRouteWithChildren
  '/ticket/$ticketNo': typeof TicketTicketNoRoute
  '/csr/mistake/$employeeId': typeof CsrMistakeEmployeeIdRoute
  '/m/$module/$submodule': typeof MModuleSubmoduleRouteWithChildren
  '/m/$module/$submodule/$userId': typeof MModuleSubmoduleUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/firebase-setup': typeof FirebaseSetupRoute
  '/home': typeof HomeRoute
  '/landing': typeof LandingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/servicepower-test': typeof ServicepowerTestRoute
  '/settings': typeof SettingsRoute
  '/superadmin': typeof SuperadminRoute
  '/timecard': typeof TimecardRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/servicepower': typeof ApiServicepowerRoute
  '/employee/$employeeId': typeof EmployeeEmployeeIdRoute
  '/m/$module': typeof MModuleRouteWithChildren
  '/ticket/$ticketNo': typeof TicketTicketNoRoute
  '/csr/mistake/$employeeId': typeof CsrMistakeEmployeeIdRoute
  '/m/$module/$submodule': typeof MModuleSubmoduleRouteWithChildren
  '/m/$module/$submodule/$userId': typeof MModuleSubmoduleUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/firebase-setup'
    | '/home'
    | '/landing'
    | '/privacy'
    | '/profile'
    | '/servicepower-test'
    | '/settings'
    | '/superadmin'
    | '/timecard'
    | '/admin/users'
    | '/api/servicepower'
    | '/employee/$employeeId'
    | '/m/$module'
    | '/ticket/$ticketNo'
    | '/csr/mistake/$employeeId'
    | '/m/$module/$submodule'
    | '/m/$module/$submodule/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/firebase-setup'
    | '/home'
    | '/landing'
    | '/privacy'
    | '/profile'
    | '/servicepower-test'
    | '/settings'
    | '/superadmin'
    | '/timecard'
    | '/admin/users'
    | '/api/servicepower'
    | '/employee/$employeeId'
    | '/m/$module'
    | '/ticket/$ticketNo'
    | '/csr/mistake/$employeeId'
    | '/m/$module/$submodule'
    | '/m/$module/$submodule/$userId'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/firebase-setup'
    | '/home'
    | '/landing'
    | '/privacy'
    | '/profile'
    | '/servicepower-test'
    | '/settings'
    | '/superadmin'
    | '/timecard'
    | '/admin/users'
    | '/api/servicepower'
    | '/employee/$employeeId'
    | '/m/$module'
    | '/ticket/$ticketNo'
    | '/csr/mistake/$employeeId'
    | '/m/$module/$submodule'
    | '/m/$module/$submodule/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  FirebaseSetupRoute: typeof FirebaseSetupRoute
  HomeRoute: typeof HomeRoute
  LandingRoute: typeof LandingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ServicepowerTestRoute: typeof ServicepowerTestRoute
  SettingsRoute: typeof SettingsRoute
  SuperadminRoute: typeof SuperadminRoute
  TimecardRoute: typeof TimecardRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiServicepowerRoute: typeof ApiServicepowerRoute
  EmployeeEmployeeIdRoute: typeof EmployeeEmployeeIdRoute
  MModuleRoute: typeof MModuleRouteWithChildren
  TicketTicketNoRoute: typeof TicketTicketNoRoute
  CsrMistakeEmployeeIdRoute: typeof CsrMistakeEmployeeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timecard': {
      id: '/timecard'
      path: '/timecard'
      fullPath: '/timecard'
      preLoaderRoute: typeof TimecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicepower-test': {
      id: '/servicepower-test'
      path: '/servicepower-test'
      fullPath: '/servicepower-test'
      preLoaderRoute: typeof ServicepowerTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firebase-setup': {
      id: '/firebase-setup'
      path: '/firebase-setup'
      fullPath: '/firebase-setup'
      preLoaderRoute: typeof FirebaseSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$ticketNo': {
      id: '/ticket/$ticketNo'
      path: '/ticket/$ticketNo'
      fullPath: '/ticket/$ticketNo'
      preLoaderRoute: typeof TicketTicketNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$module': {
      id: '/m/$module'
      path: '/m/$module'
      fullPath: '/m/$module'
      preLoaderRoute: typeof MModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/$employeeId': {
      id: '/employee/$employeeId'
      path: '/employee/$employeeId'
      fullPath: '/employee/$employeeId'
      preLoaderRoute: typeof EmployeeEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/servicepower': {
      id: '/api/servicepower'
      path: '/api/servicepower'
      fullPath: '/api/servicepower'
      preLoaderRoute: typeof ApiServicepowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$module/$submodule': {
      id: '/m/$module/$submodule'
      path: '/$submodule'
      fullPath: '/m/$module/$submodule'
      preLoaderRoute: typeof MModuleSubmoduleRouteImport
      parentRoute: typeof MModuleRoute
    }
    '/csr/mistake/$employeeId': {
      id: '/csr/mistake/$employeeId'
      path: '/csr/mistake/$employeeId'
      fullPath: '/csr/mistake/$employeeId'
      preLoaderRoute: typeof CsrMistakeEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$module/$submodule/$userId': {
      id: '/m/$module/$submodule/$userId'
      path: '/$userId'
      fullPath: '/m/$module/$submodule/$userId'
      preLoaderRoute: typeof MModuleSubmoduleUserIdRouteImport
      parentRoute: typeof MModuleSubmoduleRoute
    }
  }
}

interface MModuleSubmoduleRouteChildren {
  MModuleSubmoduleUserIdRoute: typeof MModuleSubmoduleUserIdRoute
}

const MModuleSubmoduleRouteChildren: MModuleSubmoduleRouteChildren = {
  MModuleSubmoduleUserIdRoute: MModuleSubmoduleUserIdRoute,
}

const MModuleSubmoduleRouteWithChildren =
  MModuleSubmoduleRoute._addFileChildren(MModuleSubmoduleRouteChildren)

interface MModuleRouteChildren {
  MModuleSubmoduleRoute: typeof MModuleSubmoduleRouteWithChildren
}

const MModuleRouteChildren: MModuleRouteChildren = {
  MModuleSubmoduleRoute: MModuleSubmoduleRouteWithChildren,
}

const MModuleRouteWithChildren =
  MModuleRoute._addFileChildren(MModuleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  FirebaseSetupRoute: FirebaseSetupRoute,
  HomeRoute: HomeRoute,
  LandingRoute: LandingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ServicepowerTestRoute: ServicepowerTestRoute,
  SettingsRoute: SettingsRoute,
  SuperadminRoute: SuperadminRoute,
  TimecardRoute: TimecardRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiServicepowerRoute: ApiServicepowerRoute,
  EmployeeEmployeeIdRoute: EmployeeEmployeeIdRoute,
  MModuleRoute: MModuleRouteWithChildren,
  TicketTicketNoRoute: TicketTicketNoRoute,
  CsrMistakeEmployeeIdRoute: CsrMistakeEmployeeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
