/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimecardRouteImport } from './routes/timecard'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicepowerTestRouteImport } from './routes/servicepower-test'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as HrActivityLogRouteImport } from './routes/hr-activity-log'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FirebaseSetupRouteImport } from './routes/firebase-setup'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketsMapRouteImport } from './routes/tickets.map'
import { Route as TicketTicketNoRouteImport } from './routes/ticket.$ticketNo'
import { Route as SignExternalDocIdRouteImport } from './routes/sign-external.$docId'
import { Route as SignDocumentDocIdRouteImport } from './routes/sign-document.$docId'
import { Route as MModuleRouteImport } from './routes/m.$module'
import { Route as FillW9DocIdRouteImport } from './routes/fill-w9.$docId'
import { Route as FillW8benDocIdRouteImport } from './routes/fill-w8ben.$docId'
import { Route as FillW4DocIdRouteImport } from './routes/fill-w4.$docId'
import { Route as FillFormFormIdRouteImport } from './routes/fill-form.$formId'
import { Route as EmployeeEmployeeIdRouteImport } from './routes/employee.$employeeId'
import { Route as CsrAgentAgentIdRouteImport } from './routes/csr-agent.$agentId'
import { Route as ApplySlugRouteImport } from './routes/apply.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as SuperadminCompanyCompanyIdRouteImport } from './routes/superadmin.company.$companyId'
import { Route as MModuleSubmoduleRouteImport } from './routes/m.$module.$submodule'
import { Route as MModuleSubmoduleUserIdRouteImport } from './routes/m.$module.$submodule.$userId'

const TimecardRoute = TimecardRouteImport.update({
  id: '/timecard',
  path: '/timecard',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicepowerTestRoute = ServicepowerTestRouteImport.update({
  id: '/servicepower-test',
  path: '/servicepower-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const HrActivityLogRoute = HrActivityLogRouteImport.update({
  id: '/hr-activity-log',
  path: '/hr-activity-log',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FirebaseSetupRoute = FirebaseSetupRouteImport.update({
  id: '/firebase-setup',
  path: '/firebase-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsMapRoute = TicketsMapRouteImport.update({
  id: '/tickets/map',
  path: '/tickets/map',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketTicketNoRoute = TicketTicketNoRouteImport.update({
  id: '/ticket/$ticketNo',
  path: '/ticket/$ticketNo',
  getParentRoute: () => rootRouteImport,
} as any)
const SignExternalDocIdRoute = SignExternalDocIdRouteImport.update({
  id: '/sign-external/$docId',
  path: '/sign-external/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignDocumentDocIdRoute = SignDocumentDocIdRouteImport.update({
  id: '/sign-document/$docId',
  path: '/sign-document/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const MModuleRoute = MModuleRouteImport.update({
  id: '/m/$module',
  path: '/m/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const FillW9DocIdRoute = FillW9DocIdRouteImport.update({
  id: '/fill-w9/$docId',
  path: '/fill-w9/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const FillW8benDocIdRoute = FillW8benDocIdRouteImport.update({
  id: '/fill-w8ben/$docId',
  path: '/fill-w8ben/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const FillW4DocIdRoute = FillW4DocIdRouteImport.update({
  id: '/fill-w4/$docId',
  path: '/fill-w4/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const FillFormFormIdRoute = FillFormFormIdRouteImport.update({
  id: '/fill-form/$formId',
  path: '/fill-form/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeEmployeeIdRoute = EmployeeEmployeeIdRouteImport.update({
  id: '/employee/$employeeId',
  path: '/employee/$employeeId',
  getParentRoute: () => rootRouteImport,
} as any)
const CsrAgentAgentIdRoute = CsrAgentAgentIdRouteImport.update({
  id: '/csr-agent/$agentId',
  path: '/csr-agent/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplySlugRoute = ApplySlugRouteImport.update({
  id: '/apply/$slug',
  path: '/apply/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminCompanyCompanyIdRoute =
  SuperadminCompanyCompanyIdRouteImport.update({
    id: '/company/$companyId',
    path: '/company/$companyId',
    getParentRoute: () => SuperadminRoute,
  } as any)
const MModuleSubmoduleRoute = MModuleSubmoduleRouteImport.update({
  id: '/$submodule',
  path: '/$submodule',
  getParentRoute: () => MModuleRoute,
} as any)
const MModuleSubmoduleUserIdRoute = MModuleSubmoduleUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => MModuleSubmoduleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/firebase-setup': typeof FirebaseSetupRoute
  '/home': typeof HomeRoute
  '/hr-activity-log': typeof HrActivityLogRoute
  '/landing': typeof LandingRoute
  '/mobile': typeof MobileRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/servicepower-test': typeof ServicepowerTestRoute
  '/settings': typeof SettingsRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/timecard': typeof TimecardRoute
  '/admin/users': typeof AdminUsersRoute
  '/apply/$slug': typeof ApplySlugRoute
  '/csr-agent/$agentId': typeof CsrAgentAgentIdRoute
  '/employee/$employeeId': typeof EmployeeEmployeeIdRoute
  '/fill-form/$formId': typeof FillFormFormIdRoute
  '/fill-w4/$docId': typeof FillW4DocIdRoute
  '/fill-w8ben/$docId': typeof FillW8benDocIdRoute
  '/fill-w9/$docId': typeof FillW9DocIdRoute
  '/m/$module': typeof MModuleRouteWithChildren
  '/sign-document/$docId': typeof SignDocumentDocIdRoute
  '/sign-external/$docId': typeof SignExternalDocIdRoute
  '/ticket/$ticketNo': typeof TicketTicketNoRoute
  '/tickets/map': typeof TicketsMapRoute
  '/m/$module/$submodule': typeof MModuleSubmoduleRouteWithChildren
  '/superadmin/company/$companyId': typeof SuperadminCompanyCompanyIdRoute
  '/m/$module/$submodule/$userId': typeof MModuleSubmoduleUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/firebase-setup': typeof FirebaseSetupRoute
  '/home': typeof HomeRoute
  '/hr-activity-log': typeof HrActivityLogRoute
  '/landing': typeof LandingRoute
  '/mobile': typeof MobileRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/servicepower-test': typeof ServicepowerTestRoute
  '/settings': typeof SettingsRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/timecard': typeof TimecardRoute
  '/admin/users': typeof AdminUsersRoute
  '/apply/$slug': typeof ApplySlugRoute
  '/csr-agent/$agentId': typeof CsrAgentAgentIdRoute
  '/employee/$employeeId': typeof EmployeeEmployeeIdRoute
  '/fill-form/$formId': typeof FillFormFormIdRoute
  '/fill-w4/$docId': typeof FillW4DocIdRoute
  '/fill-w8ben/$docId': typeof FillW8benDocIdRoute
  '/fill-w9/$docId': typeof FillW9DocIdRoute
  '/m/$module': typeof MModuleRouteWithChildren
  '/sign-document/$docId': typeof SignDocumentDocIdRoute
  '/sign-external/$docId': typeof SignExternalDocIdRoute
  '/ticket/$ticketNo': typeof TicketTicketNoRoute
  '/tickets/map': typeof TicketsMapRoute
  '/m/$module/$submodule': typeof MModuleSubmoduleRouteWithChildren
  '/superadmin/company/$companyId': typeof SuperadminCompanyCompanyIdRoute
  '/m/$module/$submodule/$userId': typeof MModuleSubmoduleUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/firebase-setup': typeof FirebaseSetupRoute
  '/home': typeof HomeRoute
  '/hr-activity-log': typeof HrActivityLogRoute
  '/landing': typeof LandingRoute
  '/mobile': typeof MobileRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/servicepower-test': typeof ServicepowerTestRoute
  '/settings': typeof SettingsRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/timecard': typeof TimecardRoute
  '/admin/users': typeof AdminUsersRoute
  '/apply/$slug': typeof ApplySlugRoute
  '/csr-agent/$agentId': typeof CsrAgentAgentIdRoute
  '/employee/$employeeId': typeof EmployeeEmployeeIdRoute
  '/fill-form/$formId': typeof FillFormFormIdRoute
  '/fill-w4/$docId': typeof FillW4DocIdRoute
  '/fill-w8ben/$docId': typeof FillW8benDocIdRoute
  '/fill-w9/$docId': typeof FillW9DocIdRoute
  '/m/$module': typeof MModuleRouteWithChildren
  '/sign-document/$docId': typeof SignDocumentDocIdRoute
  '/sign-external/$docId': typeof SignExternalDocIdRoute
  '/ticket/$ticketNo': typeof TicketTicketNoRoute
  '/tickets/map': typeof TicketsMapRoute
  '/m/$module/$submodule': typeof MModuleSubmoduleRouteWithChildren
  '/superadmin/company/$companyId': typeof SuperadminCompanyCompanyIdRoute
  '/m/$module/$submodule/$userId': typeof MModuleSubmoduleUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/firebase-setup'
    | '/home'
    | '/hr-activity-log'
    | '/landing'
    | '/mobile'
    | '/privacy'
    | '/profile'
    | '/servicepower-test'
    | '/settings'
    | '/superadmin'
    | '/timecard'
    | '/admin/users'
    | '/apply/$slug'
    | '/csr-agent/$agentId'
    | '/employee/$employeeId'
    | '/fill-form/$formId'
    | '/fill-w4/$docId'
    | '/fill-w8ben/$docId'
    | '/fill-w9/$docId'
    | '/m/$module'
    | '/sign-document/$docId'
    | '/sign-external/$docId'
    | '/ticket/$ticketNo'
    | '/tickets/map'
    | '/m/$module/$submodule'
    | '/superadmin/company/$companyId'
    | '/m/$module/$submodule/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/firebase-setup'
    | '/home'
    | '/hr-activity-log'
    | '/landing'
    | '/mobile'
    | '/privacy'
    | '/profile'
    | '/servicepower-test'
    | '/settings'
    | '/superadmin'
    | '/timecard'
    | '/admin/users'
    | '/apply/$slug'
    | '/csr-agent/$agentId'
    | '/employee/$employeeId'
    | '/fill-form/$formId'
    | '/fill-w4/$docId'
    | '/fill-w8ben/$docId'
    | '/fill-w9/$docId'
    | '/m/$module'
    | '/sign-document/$docId'
    | '/sign-external/$docId'
    | '/ticket/$ticketNo'
    | '/tickets/map'
    | '/m/$module/$submodule'
    | '/superadmin/company/$companyId'
    | '/m/$module/$submodule/$userId'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/firebase-setup'
    | '/home'
    | '/hr-activity-log'
    | '/landing'
    | '/mobile'
    | '/privacy'
    | '/profile'
    | '/servicepower-test'
    | '/settings'
    | '/superadmin'
    | '/timecard'
    | '/admin/users'
    | '/apply/$slug'
    | '/csr-agent/$agentId'
    | '/employee/$employeeId'
    | '/fill-form/$formId'
    | '/fill-w4/$docId'
    | '/fill-w8ben/$docId'
    | '/fill-w9/$docId'
    | '/m/$module'
    | '/sign-document/$docId'
    | '/sign-external/$docId'
    | '/ticket/$ticketNo'
    | '/tickets/map'
    | '/m/$module/$submodule'
    | '/superadmin/company/$companyId'
    | '/m/$module/$submodule/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  FirebaseSetupRoute: typeof FirebaseSetupRoute
  HomeRoute: typeof HomeRoute
  HrActivityLogRoute: typeof HrActivityLogRoute
  LandingRoute: typeof LandingRoute
  MobileRoute: typeof MobileRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ServicepowerTestRoute: typeof ServicepowerTestRoute
  SettingsRoute: typeof SettingsRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
  TimecardRoute: typeof TimecardRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApplySlugRoute: typeof ApplySlugRoute
  CsrAgentAgentIdRoute: typeof CsrAgentAgentIdRoute
  EmployeeEmployeeIdRoute: typeof EmployeeEmployeeIdRoute
  FillFormFormIdRoute: typeof FillFormFormIdRoute
  FillW4DocIdRoute: typeof FillW4DocIdRoute
  FillW8benDocIdRoute: typeof FillW8benDocIdRoute
  FillW9DocIdRoute: typeof FillW9DocIdRoute
  MModuleRoute: typeof MModuleRouteWithChildren
  SignDocumentDocIdRoute: typeof SignDocumentDocIdRoute
  SignExternalDocIdRoute: typeof SignExternalDocIdRoute
  TicketTicketNoRoute: typeof TicketTicketNoRoute
  TicketsMapRoute: typeof TicketsMapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timecard': {
      id: '/timecard'
      path: '/timecard'
      fullPath: '/timecard'
      preLoaderRoute: typeof TimecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicepower-test': {
      id: '/servicepower-test'
      path: '/servicepower-test'
      fullPath: '/servicepower-test'
      preLoaderRoute: typeof ServicepowerTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-activity-log': {
      id: '/hr-activity-log'
      path: '/hr-activity-log'
      fullPath: '/hr-activity-log'
      preLoaderRoute: typeof HrActivityLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firebase-setup': {
      id: '/firebase-setup'
      path: '/firebase-setup'
      fullPath: '/firebase-setup'
      preLoaderRoute: typeof FirebaseSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/map': {
      id: '/tickets/map'
      path: '/tickets/map'
      fullPath: '/tickets/map'
      preLoaderRoute: typeof TicketsMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$ticketNo': {
      id: '/ticket/$ticketNo'
      path: '/ticket/$ticketNo'
      fullPath: '/ticket/$ticketNo'
      preLoaderRoute: typeof TicketTicketNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-external/$docId': {
      id: '/sign-external/$docId'
      path: '/sign-external/$docId'
      fullPath: '/sign-external/$docId'
      preLoaderRoute: typeof SignExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-document/$docId': {
      id: '/sign-document/$docId'
      path: '/sign-document/$docId'
      fullPath: '/sign-document/$docId'
      preLoaderRoute: typeof SignDocumentDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$module': {
      id: '/m/$module'
      path: '/m/$module'
      fullPath: '/m/$module'
      preLoaderRoute: typeof MModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-w9/$docId': {
      id: '/fill-w9/$docId'
      path: '/fill-w9/$docId'
      fullPath: '/fill-w9/$docId'
      preLoaderRoute: typeof FillW9DocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-w8ben/$docId': {
      id: '/fill-w8ben/$docId'
      path: '/fill-w8ben/$docId'
      fullPath: '/fill-w8ben/$docId'
      preLoaderRoute: typeof FillW8benDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-w4/$docId': {
      id: '/fill-w4/$docId'
      path: '/fill-w4/$docId'
      fullPath: '/fill-w4/$docId'
      preLoaderRoute: typeof FillW4DocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-form/$formId': {
      id: '/fill-form/$formId'
      path: '/fill-form/$formId'
      fullPath: '/fill-form/$formId'
      preLoaderRoute: typeof FillFormFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/$employeeId': {
      id: '/employee/$employeeId'
      path: '/employee/$employeeId'
      fullPath: '/employee/$employeeId'
      preLoaderRoute: typeof EmployeeEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csr-agent/$agentId': {
      id: '/csr-agent/$agentId'
      path: '/csr-agent/$agentId'
      fullPath: '/csr-agent/$agentId'
      preLoaderRoute: typeof CsrAgentAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$slug': {
      id: '/apply/$slug'
      path: '/apply/$slug'
      fullPath: '/apply/$slug'
      preLoaderRoute: typeof ApplySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/company/$companyId': {
      id: '/superadmin/company/$companyId'
      path: '/company/$companyId'
      fullPath: '/superadmin/company/$companyId'
      preLoaderRoute: typeof SuperadminCompanyCompanyIdRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/m/$module/$submodule': {
      id: '/m/$module/$submodule'
      path: '/$submodule'
      fullPath: '/m/$module/$submodule'
      preLoaderRoute: typeof MModuleSubmoduleRouteImport
      parentRoute: typeof MModuleRoute
    }
    '/m/$module/$submodule/$userId': {
      id: '/m/$module/$submodule/$userId'
      path: '/$userId'
      fullPath: '/m/$module/$submodule/$userId'
      preLoaderRoute: typeof MModuleSubmoduleUserIdRouteImport
      parentRoute: typeof MModuleSubmoduleRoute
    }
  }
}

interface SuperadminRouteChildren {
  SuperadminCompanyCompanyIdRoute: typeof SuperadminCompanyCompanyIdRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminCompanyCompanyIdRoute: SuperadminCompanyCompanyIdRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

interface MModuleSubmoduleRouteChildren {
  MModuleSubmoduleUserIdRoute: typeof MModuleSubmoduleUserIdRoute
}

const MModuleSubmoduleRouteChildren: MModuleSubmoduleRouteChildren = {
  MModuleSubmoduleUserIdRoute: MModuleSubmoduleUserIdRoute,
}

const MModuleSubmoduleRouteWithChildren =
  MModuleSubmoduleRoute._addFileChildren(MModuleSubmoduleRouteChildren)

interface MModuleRouteChildren {
  MModuleSubmoduleRoute: typeof MModuleSubmoduleRouteWithChildren
}

const MModuleRouteChildren: MModuleRouteChildren = {
  MModuleSubmoduleRoute: MModuleSubmoduleRouteWithChildren,
}

const MModuleRouteWithChildren =
  MModuleRoute._addFileChildren(MModuleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  FirebaseSetupRoute: FirebaseSetupRoute,
  HomeRoute: HomeRoute,
  HrActivityLogRoute: HrActivityLogRoute,
  LandingRoute: LandingRoute,
  MobileRoute: MobileRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ServicepowerTestRoute: ServicepowerTestRoute,
  SettingsRoute: SettingsRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
  TimecardRoute: TimecardRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApplySlugRoute: ApplySlugRoute,
  CsrAgentAgentIdRoute: CsrAgentAgentIdRoute,
  EmployeeEmployeeIdRoute: EmployeeEmployeeIdRoute,
  FillFormFormIdRoute: FillFormFormIdRoute,
  FillW4DocIdRoute: FillW4DocIdRoute,
  FillW8benDocIdRoute: FillW8benDocIdRoute,
  FillW9DocIdRoute: FillW9DocIdRoute,
  MModuleRoute: MModuleRouteWithChildren,
  SignDocumentDocIdRoute: SignDocumentDocIdRoute,
  SignExternalDocIdRoute: SignExternalDocIdRoute,
  TicketTicketNoRoute: TicketTicketNoRoute,
  TicketsMapRoute: TicketsMapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
