/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimecardRouteImport } from './routes/timecard'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as SignBundleExternalRouteImport } from './routes/sign-bundle-external'
import { Route as SignBundleEmployerRouteImport } from './routes/sign-bundle-employer'
import { Route as SignBundleRouteImport } from './routes/sign-bundle'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicepowerTestRouteImport } from './routes/servicepower-test'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ItTicketsRouteImport } from './routes/it-tickets'
import { Route as HrActivityLogRouteImport } from './routes/hr-activity-log'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FirebaseSetupRouteImport } from './routes/firebase-setup'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketsMapRouteImport } from './routes/tickets.map'
import { Route as TicketTicketNoRouteImport } from './routes/ticket.$ticketNo'
import { Route as SignTerminationFormDocIdRouteImport } from './routes/sign-termination-form.$docId'
import { Route as SignTerminationExternalDocIdRouteImport } from './routes/sign-termination-external.$docId'
import { Route as SignPromotionFormDocIdRouteImport } from './routes/sign-promotion-form.$docId'
import { Route as SignPromotionExternalDocIdRouteImport } from './routes/sign-promotion-external.$docId'
import { Route as SignNdaFormDocIdRouteImport } from './routes/sign-nda-form.$docId'
import { Route as SignNdaExternalDocIdRouteImport } from './routes/sign-nda-external.$docId'
import { Route as SignManagerReviewDocIdRouteImport } from './routes/sign-manager-review.$docId'
import { Route as SignExternalDocIdRouteImport } from './routes/sign-external.$docId'
import { Route as SignDocumentDocIdRouteImport } from './routes/sign-document.$docId'
import { Route as SignContractorAddendumDocIdRouteImport } from './routes/sign-contractor-addendum.$docId'
import { Route as SignContractorAddendumExternalDocIdRouteImport } from './routes/sign-contractor-addendum-external.$docId'
import { Route as SignActionPlanFormDocIdRouteImport } from './routes/sign-action-plan-form.$docId'
import { Route as SignActionPlanExternalDocIdRouteImport } from './routes/sign-action-plan-external.$docId'
import { Route as MModuleRouteImport } from './routes/m.$module'
import { Route as FillWageAckDocIdRouteImport } from './routes/fill-wage-ack.$docId'
import { Route as FillWageAckExternalDocIdRouteImport } from './routes/fill-wage-ack-external.$docId'
import { Route as FillW9DocIdRouteImport } from './routes/fill-w9.$docId'
import { Route as FillW9ExternalDocIdRouteImport } from './routes/fill-w9-external.$docId'
import { Route as FillW8benDocIdRouteImport } from './routes/fill-w8ben.$docId'
import { Route as FillW8benExternalDocIdRouteImport } from './routes/fill-w8ben-external.$docId'
import { Route as FillW4rDocIdRouteImport } from './routes/fill-w4r.$docId'
import { Route as FillW4rExternalDocIdRouteImport } from './routes/fill-w4r-external.$docId'
import { Route as FillW4DocIdRouteImport } from './routes/fill-w4.$docId'
import { Route as FillW4ExternalDocIdRouteImport } from './routes/fill-w4-external.$docId'
import { Route as FillVehicleUseAgreementDocIdRouteImport } from './routes/fill-vehicle-use-agreement.$docId'
import { Route as FillVehicleUseAgreementExternalDocIdRouteImport } from './routes/fill-vehicle-use-agreement-external.$docId'
import { Route as FillVehicleAgreementDocIdRouteImport } from './routes/fill-vehicle-agreement.$docId'
import { Route as FillVehicleAgreementExternalDocIdRouteImport } from './routes/fill-vehicle-agreement-external.$docId'
import { Route as FillSubstanceScreeningDocIdRouteImport } from './routes/fill-substance-screening.$docId'
import { Route as FillSubstanceScreeningExternalDocIdRouteImport } from './routes/fill-substance-screening-external.$docId'
import { Route as FillPtoAckDocIdRouteImport } from './routes/fill-pto-ack.$docId'
import { Route as FillPtoAckExternalDocIdRouteImport } from './routes/fill-pto-ack-external.$docId'
import { Route as FillPartsResponsibilityDocIdRouteImport } from './routes/fill-parts-responsibility.$docId'
import { Route as FillPartsResponsibilityExternalDocIdRouteImport } from './routes/fill-parts-responsibility-external.$docId'
import { Route as FillMileageFuelDocIdRouteImport } from './routes/fill-mileage-fuel.$docId'
import { Route as FillMileageFuelExternalDocIdRouteImport } from './routes/fill-mileage-fuel-external.$docId'
import { Route as FillMealRestBreakDocIdRouteImport } from './routes/fill-meal-rest-break.$docId'
import { Route as FillMealRestBreakExternalDocIdRouteImport } from './routes/fill-meal-rest-break-external.$docId'
import { Route as FillMasterW2OfficeAgreementDocIdRouteImport } from './routes/fill-master-w2-office-agreement.$docId'
import { Route as FillMasterW2AgreementDocIdRouteImport } from './routes/fill-master-w2-agreement.$docId'
import { Route as FillMasterPhContractorAgreementDocIdRouteImport } from './routes/fill-master-ph-contractor-agreement.$docId'
import { Route as FillLocationConsentDocIdRouteImport } from './routes/fill-location-consent.$docId'
import { Route as FillLocationConsentExternalDocIdRouteImport } from './routes/fill-location-consent-external.$docId'
import { Route as FillI9DocIdRouteImport } from './routes/fill-i9.$docId'
import { Route as FillI9ExternalDocIdRouteImport } from './routes/fill-i9-external.$docId'
import { Route as FillFormFormIdRouteImport } from './routes/fill-form.$formId'
import { Route as FillFlashTechnicianTravelDocIdRouteImport } from './routes/fill-flash-technician-travel.$docId'
import { Route as FillFlashTechnicianTravelExternalDocIdRouteImport } from './routes/fill-flash-technician-travel-external.$docId'
import { Route as FillEmployeeConfidentialityDocIdRouteImport } from './routes/fill-employee-confidentiality.$docId'
import { Route as FillEmployeeConfidentialityExternalDocIdRouteImport } from './routes/fill-employee-confidentiality-external.$docId'
import { Route as FillDirectDepositDocIdRouteImport } from './routes/fill-direct-deposit.$docId'
import { Route as FillDirectDepositExternalDocIdRouteImport } from './routes/fill-direct-deposit-external.$docId'
import { Route as FillDamageDocIdRouteImport } from './routes/fill-damage.$docId'
import { Route as FillDamageExternalDocIdRouteImport } from './routes/fill-damage-external.$docId'
import { Route as FillContractorDataDocIdRouteImport } from './routes/fill-contractor-data.$docId'
import { Route as FillContractorDataUsDocIdRouteImport } from './routes/fill-contractor-data-us.$docId'
import { Route as FillContractorDataUsExternalDocIdRouteImport } from './routes/fill-contractor-data-us-external.$docId'
import { Route as FillContractorDataExternalDocIdRouteImport } from './routes/fill-contractor-data-external.$docId'
import { Route as FillContractorAddendumDocIdRouteImport } from './routes/fill-contractor-addendum.$docId'
import { Route as FillContractorAddendumExternalDocIdRouteImport } from './routes/fill-contractor-addendum-external.$docId'
import { Route as FillCarIqAgreementDocIdRouteImport } from './routes/fill-car-iq-agreement.$docId'
import { Route as FillCarIqAgreementExternalDocIdRouteImport } from './routes/fill-car-iq-agreement-external.$docId'
import { Route as EmployeeEmployeeIdRouteImport } from './routes/employee.$employeeId'
import { Route as CsrAgentAgentIdRouteImport } from './routes/csr-agent.$agentId'
import { Route as ApplySlugRouteImport } from './routes/apply.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as SuperadminCompanyCompanyIdRouteImport } from './routes/superadmin.company.$companyId'
import { Route as MModuleSubmoduleRouteImport } from './routes/m.$module.$submodule'
import { Route as MModuleSubmoduleUserIdRouteImport } from './routes/m.$module.$submodule.$userId'

const TimecardRoute = TimecardRouteImport.update({
  id: '/timecard',
  path: '/timecard',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignBundleExternalRoute = SignBundleExternalRouteImport.update({
  id: '/sign-bundle-external',
  path: '/sign-bundle-external',
  getParentRoute: () => rootRouteImport,
} as any)
const SignBundleEmployerRoute = SignBundleEmployerRouteImport.update({
  id: '/sign-bundle-employer',
  path: '/sign-bundle-employer',
  getParentRoute: () => rootRouteImport,
} as any)
const SignBundleRoute = SignBundleRouteImport.update({
  id: '/sign-bundle',
  path: '/sign-bundle',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicepowerTestRoute = ServicepowerTestRouteImport.update({
  id: '/servicepower-test',
  path: '/servicepower-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ItTicketsRoute = ItTicketsRouteImport.update({
  id: '/it-tickets',
  path: '/it-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const HrActivityLogRoute = HrActivityLogRouteImport.update({
  id: '/hr-activity-log',
  path: '/hr-activity-log',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FirebaseSetupRoute = FirebaseSetupRouteImport.update({
  id: '/firebase-setup',
  path: '/firebase-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsMapRoute = TicketsMapRouteImport.update({
  id: '/tickets/map',
  path: '/tickets/map',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketTicketNoRoute = TicketTicketNoRouteImport.update({
  id: '/ticket/$ticketNo',
  path: '/ticket/$ticketNo',
  getParentRoute: () => rootRouteImport,
} as any)
const SignTerminationFormDocIdRoute =
  SignTerminationFormDocIdRouteImport.update({
    id: '/sign-termination-form/$docId',
    path: '/sign-termination-form/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SignTerminationExternalDocIdRoute =
  SignTerminationExternalDocIdRouteImport.update({
    id: '/sign-termination-external/$docId',
    path: '/sign-termination-external/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SignPromotionFormDocIdRoute = SignPromotionFormDocIdRouteImport.update({
  id: '/sign-promotion-form/$docId',
  path: '/sign-promotion-form/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignPromotionExternalDocIdRoute =
  SignPromotionExternalDocIdRouteImport.update({
    id: '/sign-promotion-external/$docId',
    path: '/sign-promotion-external/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SignNdaFormDocIdRoute = SignNdaFormDocIdRouteImport.update({
  id: '/sign-nda-form/$docId',
  path: '/sign-nda-form/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignNdaExternalDocIdRoute = SignNdaExternalDocIdRouteImport.update({
  id: '/sign-nda-external/$docId',
  path: '/sign-nda-external/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignManagerReviewDocIdRoute = SignManagerReviewDocIdRouteImport.update({
  id: '/sign-manager-review/$docId',
  path: '/sign-manager-review/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignExternalDocIdRoute = SignExternalDocIdRouteImport.update({
  id: '/sign-external/$docId',
  path: '/sign-external/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignDocumentDocIdRoute = SignDocumentDocIdRouteImport.update({
  id: '/sign-document/$docId',
  path: '/sign-document/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignContractorAddendumDocIdRoute =
  SignContractorAddendumDocIdRouteImport.update({
    id: '/sign-contractor-addendum/$docId',
    path: '/sign-contractor-addendum/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SignContractorAddendumExternalDocIdRoute =
  SignContractorAddendumExternalDocIdRouteImport.update({
    id: '/sign-contractor-addendum-external/$docId',
    path: '/sign-contractor-addendum-external/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SignActionPlanFormDocIdRoute = SignActionPlanFormDocIdRouteImport.update({
  id: '/sign-action-plan-form/$docId',
  path: '/sign-action-plan-form/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignActionPlanExternalDocIdRoute =
  SignActionPlanExternalDocIdRouteImport.update({
    id: '/sign-action-plan-external/$docId',
    path: '/sign-action-plan-external/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MModuleRoute = MModuleRouteImport.update({
  id: '/m/$module',
  path: '/m/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const FillWageAckDocIdRoute = FillWageAckDocIdRouteImport.update({
  id: '/fill-wage-ack/$docId',
  path: '/fill-wage-ack/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const FillWageAckExternalDocIdRoute =
  FillWageAckExternalDocIdRouteImport.update({
    id: '/fill-wage-ack-external/$docId',
    path: '/fill-wage-ack-external/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillW9DocIdRoute = FillW9DocIdRouteImport.update({
  id: '/fill-w9/$docId',
  path: '/fill-w9/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const FillW9ExternalDocIdRoute = FillW9ExternalDocIdRouteImport.update({
  id: '/fill-w9-external/$docId',
  path: '/fill-w9-external/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const FillW8benDocIdRoute = FillW8benDocIdRouteImport.update({
  id: '/fill-w8ben/$docId',
  path: '/fill-w8ben/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const FillW8benExternalDocIdRoute = FillW8benExternalDocIdRouteImport.update({
  id: '/fill-w8ben-external/$docId',
  path: '/fill-w8ben-external/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const FillW4rDocIdRoute = FillW4rDocIdRouteImport.update({
  id: '/fill-w4r/$docId',
  path: '/fill-w4r/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const FillW4rExternalDocIdRoute = FillW4rExternalDocIdRouteImport.update({
  id: '/fill-w4r-external/$docId',
  path: '/fill-w4r-external/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const FillW4DocIdRoute = FillW4DocIdRouteImport.update({
  id: '/fill-w4/$docId',
  path: '/fill-w4/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const FillW4ExternalDocIdRoute = FillW4ExternalDocIdRouteImport.update({
  id: '/fill-w4-external/$docId',
  path: '/fill-w4-external/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const FillVehicleUseAgreementDocIdRoute =
  FillVehicleUseAgreementDocIdRouteImport.update({
    id: '/fill-vehicle-use-agreement/$docId',
    path: '/fill-vehicle-use-agreement/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillVehicleUseAgreementExternalDocIdRoute =
  FillVehicleUseAgreementExternalDocIdRouteImport.update({
    id: '/fill-vehicle-use-agreement-external/$docId',
    path: '/fill-vehicle-use-agreement-external/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillVehicleAgreementDocIdRoute =
  FillVehicleAgreementDocIdRouteImport.update({
    id: '/fill-vehicle-agreement/$docId',
    path: '/fill-vehicle-agreement/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillVehicleAgreementExternalDocIdRoute =
  FillVehicleAgreementExternalDocIdRouteImport.update({
    id: '/fill-vehicle-agreement-external/$docId',
    path: '/fill-vehicle-agreement-external/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillSubstanceScreeningDocIdRoute =
  FillSubstanceScreeningDocIdRouteImport.update({
    id: '/fill-substance-screening/$docId',
    path: '/fill-substance-screening/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillSubstanceScreeningExternalDocIdRoute =
  FillSubstanceScreeningExternalDocIdRouteImport.update({
    id: '/fill-substance-screening-external/$docId',
    path: '/fill-substance-screening-external/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillPtoAckDocIdRoute = FillPtoAckDocIdRouteImport.update({
  id: '/fill-pto-ack/$docId',
  path: '/fill-pto-ack/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const FillPtoAckExternalDocIdRoute = FillPtoAckExternalDocIdRouteImport.update({
  id: '/fill-pto-ack-external/$docId',
  path: '/fill-pto-ack-external/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const FillPartsResponsibilityDocIdRoute =
  FillPartsResponsibilityDocIdRouteImport.update({
    id: '/fill-parts-responsibility/$docId',
    path: '/fill-parts-responsibility/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillPartsResponsibilityExternalDocIdRoute =
  FillPartsResponsibilityExternalDocIdRouteImport.update({
    id: '/fill-parts-responsibility-external/$docId',
    path: '/fill-parts-responsibility-external/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillMileageFuelDocIdRoute = FillMileageFuelDocIdRouteImport.update({
  id: '/fill-mileage-fuel/$docId',
  path: '/fill-mileage-fuel/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const FillMileageFuelExternalDocIdRoute =
  FillMileageFuelExternalDocIdRouteImport.update({
    id: '/fill-mileage-fuel-external/$docId',
    path: '/fill-mileage-fuel-external/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillMealRestBreakDocIdRoute = FillMealRestBreakDocIdRouteImport.update({
  id: '/fill-meal-rest-break/$docId',
  path: '/fill-meal-rest-break/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const FillMealRestBreakExternalDocIdRoute =
  FillMealRestBreakExternalDocIdRouteImport.update({
    id: '/fill-meal-rest-break-external/$docId',
    path: '/fill-meal-rest-break-external/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillMasterW2OfficeAgreementDocIdRoute =
  FillMasterW2OfficeAgreementDocIdRouteImport.update({
    id: '/fill-master-w2-office-agreement/$docId',
    path: '/fill-master-w2-office-agreement/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillMasterW2AgreementDocIdRoute =
  FillMasterW2AgreementDocIdRouteImport.update({
    id: '/fill-master-w2-agreement/$docId',
    path: '/fill-master-w2-agreement/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillMasterPhContractorAgreementDocIdRoute =
  FillMasterPhContractorAgreementDocIdRouteImport.update({
    id: '/fill-master-ph-contractor-agreement/$docId',
    path: '/fill-master-ph-contractor-agreement/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillLocationConsentDocIdRoute =
  FillLocationConsentDocIdRouteImport.update({
    id: '/fill-location-consent/$docId',
    path: '/fill-location-consent/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillLocationConsentExternalDocIdRoute =
  FillLocationConsentExternalDocIdRouteImport.update({
    id: '/fill-location-consent-external/$docId',
    path: '/fill-location-consent-external/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillI9DocIdRoute = FillI9DocIdRouteImport.update({
  id: '/fill-i9/$docId',
  path: '/fill-i9/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const FillI9ExternalDocIdRoute = FillI9ExternalDocIdRouteImport.update({
  id: '/fill-i9-external/$docId',
  path: '/fill-i9-external/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const FillFormFormIdRoute = FillFormFormIdRouteImport.update({
  id: '/fill-form/$formId',
  path: '/fill-form/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const FillFlashTechnicianTravelDocIdRoute =
  FillFlashTechnicianTravelDocIdRouteImport.update({
    id: '/fill-flash-technician-travel/$docId',
    path: '/fill-flash-technician-travel/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillFlashTechnicianTravelExternalDocIdRoute =
  FillFlashTechnicianTravelExternalDocIdRouteImport.update({
    id: '/fill-flash-technician-travel-external/$docId',
    path: '/fill-flash-technician-travel-external/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillEmployeeConfidentialityDocIdRoute =
  FillEmployeeConfidentialityDocIdRouteImport.update({
    id: '/fill-employee-confidentiality/$docId',
    path: '/fill-employee-confidentiality/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillEmployeeConfidentialityExternalDocIdRoute =
  FillEmployeeConfidentialityExternalDocIdRouteImport.update({
    id: '/fill-employee-confidentiality-external/$docId',
    path: '/fill-employee-confidentiality-external/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillDirectDepositDocIdRoute = FillDirectDepositDocIdRouteImport.update({
  id: '/fill-direct-deposit/$docId',
  path: '/fill-direct-deposit/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const FillDirectDepositExternalDocIdRoute =
  FillDirectDepositExternalDocIdRouteImport.update({
    id: '/fill-direct-deposit-external/$docId',
    path: '/fill-direct-deposit-external/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillDamageDocIdRoute = FillDamageDocIdRouteImport.update({
  id: '/fill-damage/$docId',
  path: '/fill-damage/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const FillDamageExternalDocIdRoute = FillDamageExternalDocIdRouteImport.update({
  id: '/fill-damage-external/$docId',
  path: '/fill-damage-external/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const FillContractorDataDocIdRoute = FillContractorDataDocIdRouteImport.update({
  id: '/fill-contractor-data/$docId',
  path: '/fill-contractor-data/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const FillContractorDataUsDocIdRoute =
  FillContractorDataUsDocIdRouteImport.update({
    id: '/fill-contractor-data-us/$docId',
    path: '/fill-contractor-data-us/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillContractorDataUsExternalDocIdRoute =
  FillContractorDataUsExternalDocIdRouteImport.update({
    id: '/fill-contractor-data-us-external/$docId',
    path: '/fill-contractor-data-us-external/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillContractorDataExternalDocIdRoute =
  FillContractorDataExternalDocIdRouteImport.update({
    id: '/fill-contractor-data-external/$docId',
    path: '/fill-contractor-data-external/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillContractorAddendumDocIdRoute =
  FillContractorAddendumDocIdRouteImport.update({
    id: '/fill-contractor-addendum/$docId',
    path: '/fill-contractor-addendum/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillContractorAddendumExternalDocIdRoute =
  FillContractorAddendumExternalDocIdRouteImport.update({
    id: '/fill-contractor-addendum-external/$docId',
    path: '/fill-contractor-addendum-external/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FillCarIqAgreementDocIdRoute = FillCarIqAgreementDocIdRouteImport.update({
  id: '/fill-car-iq-agreement/$docId',
  path: '/fill-car-iq-agreement/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const FillCarIqAgreementExternalDocIdRoute =
  FillCarIqAgreementExternalDocIdRouteImport.update({
    id: '/fill-car-iq-agreement-external/$docId',
    path: '/fill-car-iq-agreement-external/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployeeEmployeeIdRoute = EmployeeEmployeeIdRouteImport.update({
  id: '/employee/$employeeId',
  path: '/employee/$employeeId',
  getParentRoute: () => rootRouteImport,
} as any)
const CsrAgentAgentIdRoute = CsrAgentAgentIdRouteImport.update({
  id: '/csr-agent/$agentId',
  path: '/csr-agent/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplySlugRoute = ApplySlugRouteImport.update({
  id: '/apply/$slug',
  path: '/apply/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminCompanyCompanyIdRoute =
  SuperadminCompanyCompanyIdRouteImport.update({
    id: '/company/$companyId',
    path: '/company/$companyId',
    getParentRoute: () => SuperadminRoute,
  } as any)
const MModuleSubmoduleRoute = MModuleSubmoduleRouteImport.update({
  id: '/$submodule',
  path: '/$submodule',
  getParentRoute: () => MModuleRoute,
} as any)
const MModuleSubmoduleUserIdRoute = MModuleSubmoduleUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => MModuleSubmoduleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/firebase-setup': typeof FirebaseSetupRoute
  '/home': typeof HomeRoute
  '/hr-activity-log': typeof HrActivityLogRoute
  '/it-tickets': typeof ItTicketsRoute
  '/landing': typeof LandingRoute
  '/mobile': typeof MobileRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/servicepower-test': typeof ServicepowerTestRoute
  '/settings': typeof SettingsRoute
  '/sign-bundle': typeof SignBundleRoute
  '/sign-bundle-employer': typeof SignBundleEmployerRoute
  '/sign-bundle-external': typeof SignBundleExternalRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/timecard': typeof TimecardRoute
  '/admin/users': typeof AdminUsersRoute
  '/apply/$slug': typeof ApplySlugRoute
  '/csr-agent/$agentId': typeof CsrAgentAgentIdRoute
  '/employee/$employeeId': typeof EmployeeEmployeeIdRoute
  '/fill-car-iq-agreement-external/$docId': typeof FillCarIqAgreementExternalDocIdRoute
  '/fill-car-iq-agreement/$docId': typeof FillCarIqAgreementDocIdRoute
  '/fill-contractor-addendum-external/$docId': typeof FillContractorAddendumExternalDocIdRoute
  '/fill-contractor-addendum/$docId': typeof FillContractorAddendumDocIdRoute
  '/fill-contractor-data-external/$docId': typeof FillContractorDataExternalDocIdRoute
  '/fill-contractor-data-us-external/$docId': typeof FillContractorDataUsExternalDocIdRoute
  '/fill-contractor-data-us/$docId': typeof FillContractorDataUsDocIdRoute
  '/fill-contractor-data/$docId': typeof FillContractorDataDocIdRoute
  '/fill-damage-external/$docId': typeof FillDamageExternalDocIdRoute
  '/fill-damage/$docId': typeof FillDamageDocIdRoute
  '/fill-direct-deposit-external/$docId': typeof FillDirectDepositExternalDocIdRoute
  '/fill-direct-deposit/$docId': typeof FillDirectDepositDocIdRoute
  '/fill-employee-confidentiality-external/$docId': typeof FillEmployeeConfidentialityExternalDocIdRoute
  '/fill-employee-confidentiality/$docId': typeof FillEmployeeConfidentialityDocIdRoute
  '/fill-flash-technician-travel-external/$docId': typeof FillFlashTechnicianTravelExternalDocIdRoute
  '/fill-flash-technician-travel/$docId': typeof FillFlashTechnicianTravelDocIdRoute
  '/fill-form/$formId': typeof FillFormFormIdRoute
  '/fill-i9-external/$docId': typeof FillI9ExternalDocIdRoute
  '/fill-i9/$docId': typeof FillI9DocIdRoute
  '/fill-location-consent-external/$docId': typeof FillLocationConsentExternalDocIdRoute
  '/fill-location-consent/$docId': typeof FillLocationConsentDocIdRoute
  '/fill-master-ph-contractor-agreement/$docId': typeof FillMasterPhContractorAgreementDocIdRoute
  '/fill-master-w2-agreement/$docId': typeof FillMasterW2AgreementDocIdRoute
  '/fill-master-w2-office-agreement/$docId': typeof FillMasterW2OfficeAgreementDocIdRoute
  '/fill-meal-rest-break-external/$docId': typeof FillMealRestBreakExternalDocIdRoute
  '/fill-meal-rest-break/$docId': typeof FillMealRestBreakDocIdRoute
  '/fill-mileage-fuel-external/$docId': typeof FillMileageFuelExternalDocIdRoute
  '/fill-mileage-fuel/$docId': typeof FillMileageFuelDocIdRoute
  '/fill-parts-responsibility-external/$docId': typeof FillPartsResponsibilityExternalDocIdRoute
  '/fill-parts-responsibility/$docId': typeof FillPartsResponsibilityDocIdRoute
  '/fill-pto-ack-external/$docId': typeof FillPtoAckExternalDocIdRoute
  '/fill-pto-ack/$docId': typeof FillPtoAckDocIdRoute
  '/fill-substance-screening-external/$docId': typeof FillSubstanceScreeningExternalDocIdRoute
  '/fill-substance-screening/$docId': typeof FillSubstanceScreeningDocIdRoute
  '/fill-vehicle-agreement-external/$docId': typeof FillVehicleAgreementExternalDocIdRoute
  '/fill-vehicle-agreement/$docId': typeof FillVehicleAgreementDocIdRoute
  '/fill-vehicle-use-agreement-external/$docId': typeof FillVehicleUseAgreementExternalDocIdRoute
  '/fill-vehicle-use-agreement/$docId': typeof FillVehicleUseAgreementDocIdRoute
  '/fill-w4-external/$docId': typeof FillW4ExternalDocIdRoute
  '/fill-w4/$docId': typeof FillW4DocIdRoute
  '/fill-w4r-external/$docId': typeof FillW4rExternalDocIdRoute
  '/fill-w4r/$docId': typeof FillW4rDocIdRoute
  '/fill-w8ben-external/$docId': typeof FillW8benExternalDocIdRoute
  '/fill-w8ben/$docId': typeof FillW8benDocIdRoute
  '/fill-w9-external/$docId': typeof FillW9ExternalDocIdRoute
  '/fill-w9/$docId': typeof FillW9DocIdRoute
  '/fill-wage-ack-external/$docId': typeof FillWageAckExternalDocIdRoute
  '/fill-wage-ack/$docId': typeof FillWageAckDocIdRoute
  '/m/$module': typeof MModuleRouteWithChildren
  '/sign-action-plan-external/$docId': typeof SignActionPlanExternalDocIdRoute
  '/sign-action-plan-form/$docId': typeof SignActionPlanFormDocIdRoute
  '/sign-contractor-addendum-external/$docId': typeof SignContractorAddendumExternalDocIdRoute
  '/sign-contractor-addendum/$docId': typeof SignContractorAddendumDocIdRoute
  '/sign-document/$docId': typeof SignDocumentDocIdRoute
  '/sign-external/$docId': typeof SignExternalDocIdRoute
  '/sign-manager-review/$docId': typeof SignManagerReviewDocIdRoute
  '/sign-nda-external/$docId': typeof SignNdaExternalDocIdRoute
  '/sign-nda-form/$docId': typeof SignNdaFormDocIdRoute
  '/sign-promotion-external/$docId': typeof SignPromotionExternalDocIdRoute
  '/sign-promotion-form/$docId': typeof SignPromotionFormDocIdRoute
  '/sign-termination-external/$docId': typeof SignTerminationExternalDocIdRoute
  '/sign-termination-form/$docId': typeof SignTerminationFormDocIdRoute
  '/ticket/$ticketNo': typeof TicketTicketNoRoute
  '/tickets/map': typeof TicketsMapRoute
  '/m/$module/$submodule': typeof MModuleSubmoduleRouteWithChildren
  '/superadmin/company/$companyId': typeof SuperadminCompanyCompanyIdRoute
  '/m/$module/$submodule/$userId': typeof MModuleSubmoduleUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/firebase-setup': typeof FirebaseSetupRoute
  '/home': typeof HomeRoute
  '/hr-activity-log': typeof HrActivityLogRoute
  '/it-tickets': typeof ItTicketsRoute
  '/landing': typeof LandingRoute
  '/mobile': typeof MobileRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/servicepower-test': typeof ServicepowerTestRoute
  '/settings': typeof SettingsRoute
  '/sign-bundle': typeof SignBundleRoute
  '/sign-bundle-employer': typeof SignBundleEmployerRoute
  '/sign-bundle-external': typeof SignBundleExternalRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/timecard': typeof TimecardRoute
  '/admin/users': typeof AdminUsersRoute
  '/apply/$slug': typeof ApplySlugRoute
  '/csr-agent/$agentId': typeof CsrAgentAgentIdRoute
  '/employee/$employeeId': typeof EmployeeEmployeeIdRoute
  '/fill-car-iq-agreement-external/$docId': typeof FillCarIqAgreementExternalDocIdRoute
  '/fill-car-iq-agreement/$docId': typeof FillCarIqAgreementDocIdRoute
  '/fill-contractor-addendum-external/$docId': typeof FillContractorAddendumExternalDocIdRoute
  '/fill-contractor-addendum/$docId': typeof FillContractorAddendumDocIdRoute
  '/fill-contractor-data-external/$docId': typeof FillContractorDataExternalDocIdRoute
  '/fill-contractor-data-us-external/$docId': typeof FillContractorDataUsExternalDocIdRoute
  '/fill-contractor-data-us/$docId': typeof FillContractorDataUsDocIdRoute
  '/fill-contractor-data/$docId': typeof FillContractorDataDocIdRoute
  '/fill-damage-external/$docId': typeof FillDamageExternalDocIdRoute
  '/fill-damage/$docId': typeof FillDamageDocIdRoute
  '/fill-direct-deposit-external/$docId': typeof FillDirectDepositExternalDocIdRoute
  '/fill-direct-deposit/$docId': typeof FillDirectDepositDocIdRoute
  '/fill-employee-confidentiality-external/$docId': typeof FillEmployeeConfidentialityExternalDocIdRoute
  '/fill-employee-confidentiality/$docId': typeof FillEmployeeConfidentialityDocIdRoute
  '/fill-flash-technician-travel-external/$docId': typeof FillFlashTechnicianTravelExternalDocIdRoute
  '/fill-flash-technician-travel/$docId': typeof FillFlashTechnicianTravelDocIdRoute
  '/fill-form/$formId': typeof FillFormFormIdRoute
  '/fill-i9-external/$docId': typeof FillI9ExternalDocIdRoute
  '/fill-i9/$docId': typeof FillI9DocIdRoute
  '/fill-location-consent-external/$docId': typeof FillLocationConsentExternalDocIdRoute
  '/fill-location-consent/$docId': typeof FillLocationConsentDocIdRoute
  '/fill-master-ph-contractor-agreement/$docId': typeof FillMasterPhContractorAgreementDocIdRoute
  '/fill-master-w2-agreement/$docId': typeof FillMasterW2AgreementDocIdRoute
  '/fill-master-w2-office-agreement/$docId': typeof FillMasterW2OfficeAgreementDocIdRoute
  '/fill-meal-rest-break-external/$docId': typeof FillMealRestBreakExternalDocIdRoute
  '/fill-meal-rest-break/$docId': typeof FillMealRestBreakDocIdRoute
  '/fill-mileage-fuel-external/$docId': typeof FillMileageFuelExternalDocIdRoute
  '/fill-mileage-fuel/$docId': typeof FillMileageFuelDocIdRoute
  '/fill-parts-responsibility-external/$docId': typeof FillPartsResponsibilityExternalDocIdRoute
  '/fill-parts-responsibility/$docId': typeof FillPartsResponsibilityDocIdRoute
  '/fill-pto-ack-external/$docId': typeof FillPtoAckExternalDocIdRoute
  '/fill-pto-ack/$docId': typeof FillPtoAckDocIdRoute
  '/fill-substance-screening-external/$docId': typeof FillSubstanceScreeningExternalDocIdRoute
  '/fill-substance-screening/$docId': typeof FillSubstanceScreeningDocIdRoute
  '/fill-vehicle-agreement-external/$docId': typeof FillVehicleAgreementExternalDocIdRoute
  '/fill-vehicle-agreement/$docId': typeof FillVehicleAgreementDocIdRoute
  '/fill-vehicle-use-agreement-external/$docId': typeof FillVehicleUseAgreementExternalDocIdRoute
  '/fill-vehicle-use-agreement/$docId': typeof FillVehicleUseAgreementDocIdRoute
  '/fill-w4-external/$docId': typeof FillW4ExternalDocIdRoute
  '/fill-w4/$docId': typeof FillW4DocIdRoute
  '/fill-w4r-external/$docId': typeof FillW4rExternalDocIdRoute
  '/fill-w4r/$docId': typeof FillW4rDocIdRoute
  '/fill-w8ben-external/$docId': typeof FillW8benExternalDocIdRoute
  '/fill-w8ben/$docId': typeof FillW8benDocIdRoute
  '/fill-w9-external/$docId': typeof FillW9ExternalDocIdRoute
  '/fill-w9/$docId': typeof FillW9DocIdRoute
  '/fill-wage-ack-external/$docId': typeof FillWageAckExternalDocIdRoute
  '/fill-wage-ack/$docId': typeof FillWageAckDocIdRoute
  '/m/$module': typeof MModuleRouteWithChildren
  '/sign-action-plan-external/$docId': typeof SignActionPlanExternalDocIdRoute
  '/sign-action-plan-form/$docId': typeof SignActionPlanFormDocIdRoute
  '/sign-contractor-addendum-external/$docId': typeof SignContractorAddendumExternalDocIdRoute
  '/sign-contractor-addendum/$docId': typeof SignContractorAddendumDocIdRoute
  '/sign-document/$docId': typeof SignDocumentDocIdRoute
  '/sign-external/$docId': typeof SignExternalDocIdRoute
  '/sign-manager-review/$docId': typeof SignManagerReviewDocIdRoute
  '/sign-nda-external/$docId': typeof SignNdaExternalDocIdRoute
  '/sign-nda-form/$docId': typeof SignNdaFormDocIdRoute
  '/sign-promotion-external/$docId': typeof SignPromotionExternalDocIdRoute
  '/sign-promotion-form/$docId': typeof SignPromotionFormDocIdRoute
  '/sign-termination-external/$docId': typeof SignTerminationExternalDocIdRoute
  '/sign-termination-form/$docId': typeof SignTerminationFormDocIdRoute
  '/ticket/$ticketNo': typeof TicketTicketNoRoute
  '/tickets/map': typeof TicketsMapRoute
  '/m/$module/$submodule': typeof MModuleSubmoduleRouteWithChildren
  '/superadmin/company/$companyId': typeof SuperadminCompanyCompanyIdRoute
  '/m/$module/$submodule/$userId': typeof MModuleSubmoduleUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/firebase-setup': typeof FirebaseSetupRoute
  '/home': typeof HomeRoute
  '/hr-activity-log': typeof HrActivityLogRoute
  '/it-tickets': typeof ItTicketsRoute
  '/landing': typeof LandingRoute
  '/mobile': typeof MobileRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/servicepower-test': typeof ServicepowerTestRoute
  '/settings': typeof SettingsRoute
  '/sign-bundle': typeof SignBundleRoute
  '/sign-bundle-employer': typeof SignBundleEmployerRoute
  '/sign-bundle-external': typeof SignBundleExternalRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/timecard': typeof TimecardRoute
  '/admin/users': typeof AdminUsersRoute
  '/apply/$slug': typeof ApplySlugRoute
  '/csr-agent/$agentId': typeof CsrAgentAgentIdRoute
  '/employee/$employeeId': typeof EmployeeEmployeeIdRoute
  '/fill-car-iq-agreement-external/$docId': typeof FillCarIqAgreementExternalDocIdRoute
  '/fill-car-iq-agreement/$docId': typeof FillCarIqAgreementDocIdRoute
  '/fill-contractor-addendum-external/$docId': typeof FillContractorAddendumExternalDocIdRoute
  '/fill-contractor-addendum/$docId': typeof FillContractorAddendumDocIdRoute
  '/fill-contractor-data-external/$docId': typeof FillContractorDataExternalDocIdRoute
  '/fill-contractor-data-us-external/$docId': typeof FillContractorDataUsExternalDocIdRoute
  '/fill-contractor-data-us/$docId': typeof FillContractorDataUsDocIdRoute
  '/fill-contractor-data/$docId': typeof FillContractorDataDocIdRoute
  '/fill-damage-external/$docId': typeof FillDamageExternalDocIdRoute
  '/fill-damage/$docId': typeof FillDamageDocIdRoute
  '/fill-direct-deposit-external/$docId': typeof FillDirectDepositExternalDocIdRoute
  '/fill-direct-deposit/$docId': typeof FillDirectDepositDocIdRoute
  '/fill-employee-confidentiality-external/$docId': typeof FillEmployeeConfidentialityExternalDocIdRoute
  '/fill-employee-confidentiality/$docId': typeof FillEmployeeConfidentialityDocIdRoute
  '/fill-flash-technician-travel-external/$docId': typeof FillFlashTechnicianTravelExternalDocIdRoute
  '/fill-flash-technician-travel/$docId': typeof FillFlashTechnicianTravelDocIdRoute
  '/fill-form/$formId': typeof FillFormFormIdRoute
  '/fill-i9-external/$docId': typeof FillI9ExternalDocIdRoute
  '/fill-i9/$docId': typeof FillI9DocIdRoute
  '/fill-location-consent-external/$docId': typeof FillLocationConsentExternalDocIdRoute
  '/fill-location-consent/$docId': typeof FillLocationConsentDocIdRoute
  '/fill-master-ph-contractor-agreement/$docId': typeof FillMasterPhContractorAgreementDocIdRoute
  '/fill-master-w2-agreement/$docId': typeof FillMasterW2AgreementDocIdRoute
  '/fill-master-w2-office-agreement/$docId': typeof FillMasterW2OfficeAgreementDocIdRoute
  '/fill-meal-rest-break-external/$docId': typeof FillMealRestBreakExternalDocIdRoute
  '/fill-meal-rest-break/$docId': typeof FillMealRestBreakDocIdRoute
  '/fill-mileage-fuel-external/$docId': typeof FillMileageFuelExternalDocIdRoute
  '/fill-mileage-fuel/$docId': typeof FillMileageFuelDocIdRoute
  '/fill-parts-responsibility-external/$docId': typeof FillPartsResponsibilityExternalDocIdRoute
  '/fill-parts-responsibility/$docId': typeof FillPartsResponsibilityDocIdRoute
  '/fill-pto-ack-external/$docId': typeof FillPtoAckExternalDocIdRoute
  '/fill-pto-ack/$docId': typeof FillPtoAckDocIdRoute
  '/fill-substance-screening-external/$docId': typeof FillSubstanceScreeningExternalDocIdRoute
  '/fill-substance-screening/$docId': typeof FillSubstanceScreeningDocIdRoute
  '/fill-vehicle-agreement-external/$docId': typeof FillVehicleAgreementExternalDocIdRoute
  '/fill-vehicle-agreement/$docId': typeof FillVehicleAgreementDocIdRoute
  '/fill-vehicle-use-agreement-external/$docId': typeof FillVehicleUseAgreementExternalDocIdRoute
  '/fill-vehicle-use-agreement/$docId': typeof FillVehicleUseAgreementDocIdRoute
  '/fill-w4-external/$docId': typeof FillW4ExternalDocIdRoute
  '/fill-w4/$docId': typeof FillW4DocIdRoute
  '/fill-w4r-external/$docId': typeof FillW4rExternalDocIdRoute
  '/fill-w4r/$docId': typeof FillW4rDocIdRoute
  '/fill-w8ben-external/$docId': typeof FillW8benExternalDocIdRoute
  '/fill-w8ben/$docId': typeof FillW8benDocIdRoute
  '/fill-w9-external/$docId': typeof FillW9ExternalDocIdRoute
  '/fill-w9/$docId': typeof FillW9DocIdRoute
  '/fill-wage-ack-external/$docId': typeof FillWageAckExternalDocIdRoute
  '/fill-wage-ack/$docId': typeof FillWageAckDocIdRoute
  '/m/$module': typeof MModuleRouteWithChildren
  '/sign-action-plan-external/$docId': typeof SignActionPlanExternalDocIdRoute
  '/sign-action-plan-form/$docId': typeof SignActionPlanFormDocIdRoute
  '/sign-contractor-addendum-external/$docId': typeof SignContractorAddendumExternalDocIdRoute
  '/sign-contractor-addendum/$docId': typeof SignContractorAddendumDocIdRoute
  '/sign-document/$docId': typeof SignDocumentDocIdRoute
  '/sign-external/$docId': typeof SignExternalDocIdRoute
  '/sign-manager-review/$docId': typeof SignManagerReviewDocIdRoute
  '/sign-nda-external/$docId': typeof SignNdaExternalDocIdRoute
  '/sign-nda-form/$docId': typeof SignNdaFormDocIdRoute
  '/sign-promotion-external/$docId': typeof SignPromotionExternalDocIdRoute
  '/sign-promotion-form/$docId': typeof SignPromotionFormDocIdRoute
  '/sign-termination-external/$docId': typeof SignTerminationExternalDocIdRoute
  '/sign-termination-form/$docId': typeof SignTerminationFormDocIdRoute
  '/ticket/$ticketNo': typeof TicketTicketNoRoute
  '/tickets/map': typeof TicketsMapRoute
  '/m/$module/$submodule': typeof MModuleSubmoduleRouteWithChildren
  '/superadmin/company/$companyId': typeof SuperadminCompanyCompanyIdRoute
  '/m/$module/$submodule/$userId': typeof MModuleSubmoduleUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/firebase-setup'
    | '/home'
    | '/hr-activity-log'
    | '/it-tickets'
    | '/landing'
    | '/mobile'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/servicepower-test'
    | '/settings'
    | '/sign-bundle'
    | '/sign-bundle-employer'
    | '/sign-bundle-external'
    | '/superadmin'
    | '/timecard'
    | '/admin/users'
    | '/apply/$slug'
    | '/csr-agent/$agentId'
    | '/employee/$employeeId'
    | '/fill-car-iq-agreement-external/$docId'
    | '/fill-car-iq-agreement/$docId'
    | '/fill-contractor-addendum-external/$docId'
    | '/fill-contractor-addendum/$docId'
    | '/fill-contractor-data-external/$docId'
    | '/fill-contractor-data-us-external/$docId'
    | '/fill-contractor-data-us/$docId'
    | '/fill-contractor-data/$docId'
    | '/fill-damage-external/$docId'
    | '/fill-damage/$docId'
    | '/fill-direct-deposit-external/$docId'
    | '/fill-direct-deposit/$docId'
    | '/fill-employee-confidentiality-external/$docId'
    | '/fill-employee-confidentiality/$docId'
    | '/fill-flash-technician-travel-external/$docId'
    | '/fill-flash-technician-travel/$docId'
    | '/fill-form/$formId'
    | '/fill-i9-external/$docId'
    | '/fill-i9/$docId'
    | '/fill-location-consent-external/$docId'
    | '/fill-location-consent/$docId'
    | '/fill-master-ph-contractor-agreement/$docId'
    | '/fill-master-w2-agreement/$docId'
    | '/fill-master-w2-office-agreement/$docId'
    | '/fill-meal-rest-break-external/$docId'
    | '/fill-meal-rest-break/$docId'
    | '/fill-mileage-fuel-external/$docId'
    | '/fill-mileage-fuel/$docId'
    | '/fill-parts-responsibility-external/$docId'
    | '/fill-parts-responsibility/$docId'
    | '/fill-pto-ack-external/$docId'
    | '/fill-pto-ack/$docId'
    | '/fill-substance-screening-external/$docId'
    | '/fill-substance-screening/$docId'
    | '/fill-vehicle-agreement-external/$docId'
    | '/fill-vehicle-agreement/$docId'
    | '/fill-vehicle-use-agreement-external/$docId'
    | '/fill-vehicle-use-agreement/$docId'
    | '/fill-w4-external/$docId'
    | '/fill-w4/$docId'
    | '/fill-w4r-external/$docId'
    | '/fill-w4r/$docId'
    | '/fill-w8ben-external/$docId'
    | '/fill-w8ben/$docId'
    | '/fill-w9-external/$docId'
    | '/fill-w9/$docId'
    | '/fill-wage-ack-external/$docId'
    | '/fill-wage-ack/$docId'
    | '/m/$module'
    | '/sign-action-plan-external/$docId'
    | '/sign-action-plan-form/$docId'
    | '/sign-contractor-addendum-external/$docId'
    | '/sign-contractor-addendum/$docId'
    | '/sign-document/$docId'
    | '/sign-external/$docId'
    | '/sign-manager-review/$docId'
    | '/sign-nda-external/$docId'
    | '/sign-nda-form/$docId'
    | '/sign-promotion-external/$docId'
    | '/sign-promotion-form/$docId'
    | '/sign-termination-external/$docId'
    | '/sign-termination-form/$docId'
    | '/ticket/$ticketNo'
    | '/tickets/map'
    | '/m/$module/$submodule'
    | '/superadmin/company/$companyId'
    | '/m/$module/$submodule/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/firebase-setup'
    | '/home'
    | '/hr-activity-log'
    | '/it-tickets'
    | '/landing'
    | '/mobile'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/servicepower-test'
    | '/settings'
    | '/sign-bundle'
    | '/sign-bundle-employer'
    | '/sign-bundle-external'
    | '/superadmin'
    | '/timecard'
    | '/admin/users'
    | '/apply/$slug'
    | '/csr-agent/$agentId'
    | '/employee/$employeeId'
    | '/fill-car-iq-agreement-external/$docId'
    | '/fill-car-iq-agreement/$docId'
    | '/fill-contractor-addendum-external/$docId'
    | '/fill-contractor-addendum/$docId'
    | '/fill-contractor-data-external/$docId'
    | '/fill-contractor-data-us-external/$docId'
    | '/fill-contractor-data-us/$docId'
    | '/fill-contractor-data/$docId'
    | '/fill-damage-external/$docId'
    | '/fill-damage/$docId'
    | '/fill-direct-deposit-external/$docId'
    | '/fill-direct-deposit/$docId'
    | '/fill-employee-confidentiality-external/$docId'
    | '/fill-employee-confidentiality/$docId'
    | '/fill-flash-technician-travel-external/$docId'
    | '/fill-flash-technician-travel/$docId'
    | '/fill-form/$formId'
    | '/fill-i9-external/$docId'
    | '/fill-i9/$docId'
    | '/fill-location-consent-external/$docId'
    | '/fill-location-consent/$docId'
    | '/fill-master-ph-contractor-agreement/$docId'
    | '/fill-master-w2-agreement/$docId'
    | '/fill-master-w2-office-agreement/$docId'
    | '/fill-meal-rest-break-external/$docId'
    | '/fill-meal-rest-break/$docId'
    | '/fill-mileage-fuel-external/$docId'
    | '/fill-mileage-fuel/$docId'
    | '/fill-parts-responsibility-external/$docId'
    | '/fill-parts-responsibility/$docId'
    | '/fill-pto-ack-external/$docId'
    | '/fill-pto-ack/$docId'
    | '/fill-substance-screening-external/$docId'
    | '/fill-substance-screening/$docId'
    | '/fill-vehicle-agreement-external/$docId'
    | '/fill-vehicle-agreement/$docId'
    | '/fill-vehicle-use-agreement-external/$docId'
    | '/fill-vehicle-use-agreement/$docId'
    | '/fill-w4-external/$docId'
    | '/fill-w4/$docId'
    | '/fill-w4r-external/$docId'
    | '/fill-w4r/$docId'
    | '/fill-w8ben-external/$docId'
    | '/fill-w8ben/$docId'
    | '/fill-w9-external/$docId'
    | '/fill-w9/$docId'
    | '/fill-wage-ack-external/$docId'
    | '/fill-wage-ack/$docId'
    | '/m/$module'
    | '/sign-action-plan-external/$docId'
    | '/sign-action-plan-form/$docId'
    | '/sign-contractor-addendum-external/$docId'
    | '/sign-contractor-addendum/$docId'
    | '/sign-document/$docId'
    | '/sign-external/$docId'
    | '/sign-manager-review/$docId'
    | '/sign-nda-external/$docId'
    | '/sign-nda-form/$docId'
    | '/sign-promotion-external/$docId'
    | '/sign-promotion-form/$docId'
    | '/sign-termination-external/$docId'
    | '/sign-termination-form/$docId'
    | '/ticket/$ticketNo'
    | '/tickets/map'
    | '/m/$module/$submodule'
    | '/superadmin/company/$companyId'
    | '/m/$module/$submodule/$userId'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/firebase-setup'
    | '/home'
    | '/hr-activity-log'
    | '/it-tickets'
    | '/landing'
    | '/mobile'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/servicepower-test'
    | '/settings'
    | '/sign-bundle'
    | '/sign-bundle-employer'
    | '/sign-bundle-external'
    | '/superadmin'
    | '/timecard'
    | '/admin/users'
    | '/apply/$slug'
    | '/csr-agent/$agentId'
    | '/employee/$employeeId'
    | '/fill-car-iq-agreement-external/$docId'
    | '/fill-car-iq-agreement/$docId'
    | '/fill-contractor-addendum-external/$docId'
    | '/fill-contractor-addendum/$docId'
    | '/fill-contractor-data-external/$docId'
    | '/fill-contractor-data-us-external/$docId'
    | '/fill-contractor-data-us/$docId'
    | '/fill-contractor-data/$docId'
    | '/fill-damage-external/$docId'
    | '/fill-damage/$docId'
    | '/fill-direct-deposit-external/$docId'
    | '/fill-direct-deposit/$docId'
    | '/fill-employee-confidentiality-external/$docId'
    | '/fill-employee-confidentiality/$docId'
    | '/fill-flash-technician-travel-external/$docId'
    | '/fill-flash-technician-travel/$docId'
    | '/fill-form/$formId'
    | '/fill-i9-external/$docId'
    | '/fill-i9/$docId'
    | '/fill-location-consent-external/$docId'
    | '/fill-location-consent/$docId'
    | '/fill-master-ph-contractor-agreement/$docId'
    | '/fill-master-w2-agreement/$docId'
    | '/fill-master-w2-office-agreement/$docId'
    | '/fill-meal-rest-break-external/$docId'
    | '/fill-meal-rest-break/$docId'
    | '/fill-mileage-fuel-external/$docId'
    | '/fill-mileage-fuel/$docId'
    | '/fill-parts-responsibility-external/$docId'
    | '/fill-parts-responsibility/$docId'
    | '/fill-pto-ack-external/$docId'
    | '/fill-pto-ack/$docId'
    | '/fill-substance-screening-external/$docId'
    | '/fill-substance-screening/$docId'
    | '/fill-vehicle-agreement-external/$docId'
    | '/fill-vehicle-agreement/$docId'
    | '/fill-vehicle-use-agreement-external/$docId'
    | '/fill-vehicle-use-agreement/$docId'
    | '/fill-w4-external/$docId'
    | '/fill-w4/$docId'
    | '/fill-w4r-external/$docId'
    | '/fill-w4r/$docId'
    | '/fill-w8ben-external/$docId'
    | '/fill-w8ben/$docId'
    | '/fill-w9-external/$docId'
    | '/fill-w9/$docId'
    | '/fill-wage-ack-external/$docId'
    | '/fill-wage-ack/$docId'
    | '/m/$module'
    | '/sign-action-plan-external/$docId'
    | '/sign-action-plan-form/$docId'
    | '/sign-contractor-addendum-external/$docId'
    | '/sign-contractor-addendum/$docId'
    | '/sign-document/$docId'
    | '/sign-external/$docId'
    | '/sign-manager-review/$docId'
    | '/sign-nda-external/$docId'
    | '/sign-nda-form/$docId'
    | '/sign-promotion-external/$docId'
    | '/sign-promotion-form/$docId'
    | '/sign-termination-external/$docId'
    | '/sign-termination-form/$docId'
    | '/ticket/$ticketNo'
    | '/tickets/map'
    | '/m/$module/$submodule'
    | '/superadmin/company/$companyId'
    | '/m/$module/$submodule/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  FirebaseSetupRoute: typeof FirebaseSetupRoute
  HomeRoute: typeof HomeRoute
  HrActivityLogRoute: typeof HrActivityLogRoute
  ItTicketsRoute: typeof ItTicketsRoute
  LandingRoute: typeof LandingRoute
  MobileRoute: typeof MobileRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ServicepowerTestRoute: typeof ServicepowerTestRoute
  SettingsRoute: typeof SettingsRoute
  SignBundleRoute: typeof SignBundleRoute
  SignBundleEmployerRoute: typeof SignBundleEmployerRoute
  SignBundleExternalRoute: typeof SignBundleExternalRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
  TimecardRoute: typeof TimecardRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApplySlugRoute: typeof ApplySlugRoute
  CsrAgentAgentIdRoute: typeof CsrAgentAgentIdRoute
  EmployeeEmployeeIdRoute: typeof EmployeeEmployeeIdRoute
  FillCarIqAgreementExternalDocIdRoute: typeof FillCarIqAgreementExternalDocIdRoute
  FillCarIqAgreementDocIdRoute: typeof FillCarIqAgreementDocIdRoute
  FillContractorAddendumExternalDocIdRoute: typeof FillContractorAddendumExternalDocIdRoute
  FillContractorAddendumDocIdRoute: typeof FillContractorAddendumDocIdRoute
  FillContractorDataExternalDocIdRoute: typeof FillContractorDataExternalDocIdRoute
  FillContractorDataUsExternalDocIdRoute: typeof FillContractorDataUsExternalDocIdRoute
  FillContractorDataUsDocIdRoute: typeof FillContractorDataUsDocIdRoute
  FillContractorDataDocIdRoute: typeof FillContractorDataDocIdRoute
  FillDamageExternalDocIdRoute: typeof FillDamageExternalDocIdRoute
  FillDamageDocIdRoute: typeof FillDamageDocIdRoute
  FillDirectDepositExternalDocIdRoute: typeof FillDirectDepositExternalDocIdRoute
  FillDirectDepositDocIdRoute: typeof FillDirectDepositDocIdRoute
  FillEmployeeConfidentialityExternalDocIdRoute: typeof FillEmployeeConfidentialityExternalDocIdRoute
  FillEmployeeConfidentialityDocIdRoute: typeof FillEmployeeConfidentialityDocIdRoute
  FillFlashTechnicianTravelExternalDocIdRoute: typeof FillFlashTechnicianTravelExternalDocIdRoute
  FillFlashTechnicianTravelDocIdRoute: typeof FillFlashTechnicianTravelDocIdRoute
  FillFormFormIdRoute: typeof FillFormFormIdRoute
  FillI9ExternalDocIdRoute: typeof FillI9ExternalDocIdRoute
  FillI9DocIdRoute: typeof FillI9DocIdRoute
  FillLocationConsentExternalDocIdRoute: typeof FillLocationConsentExternalDocIdRoute
  FillLocationConsentDocIdRoute: typeof FillLocationConsentDocIdRoute
  FillMasterPhContractorAgreementDocIdRoute: typeof FillMasterPhContractorAgreementDocIdRoute
  FillMasterW2AgreementDocIdRoute: typeof FillMasterW2AgreementDocIdRoute
  FillMasterW2OfficeAgreementDocIdRoute: typeof FillMasterW2OfficeAgreementDocIdRoute
  FillMealRestBreakExternalDocIdRoute: typeof FillMealRestBreakExternalDocIdRoute
  FillMealRestBreakDocIdRoute: typeof FillMealRestBreakDocIdRoute
  FillMileageFuelExternalDocIdRoute: typeof FillMileageFuelExternalDocIdRoute
  FillMileageFuelDocIdRoute: typeof FillMileageFuelDocIdRoute
  FillPartsResponsibilityExternalDocIdRoute: typeof FillPartsResponsibilityExternalDocIdRoute
  FillPartsResponsibilityDocIdRoute: typeof FillPartsResponsibilityDocIdRoute
  FillPtoAckExternalDocIdRoute: typeof FillPtoAckExternalDocIdRoute
  FillPtoAckDocIdRoute: typeof FillPtoAckDocIdRoute
  FillSubstanceScreeningExternalDocIdRoute: typeof FillSubstanceScreeningExternalDocIdRoute
  FillSubstanceScreeningDocIdRoute: typeof FillSubstanceScreeningDocIdRoute
  FillVehicleAgreementExternalDocIdRoute: typeof FillVehicleAgreementExternalDocIdRoute
  FillVehicleAgreementDocIdRoute: typeof FillVehicleAgreementDocIdRoute
  FillVehicleUseAgreementExternalDocIdRoute: typeof FillVehicleUseAgreementExternalDocIdRoute
  FillVehicleUseAgreementDocIdRoute: typeof FillVehicleUseAgreementDocIdRoute
  FillW4ExternalDocIdRoute: typeof FillW4ExternalDocIdRoute
  FillW4DocIdRoute: typeof FillW4DocIdRoute
  FillW4rExternalDocIdRoute: typeof FillW4rExternalDocIdRoute
  FillW4rDocIdRoute: typeof FillW4rDocIdRoute
  FillW8benExternalDocIdRoute: typeof FillW8benExternalDocIdRoute
  FillW8benDocIdRoute: typeof FillW8benDocIdRoute
  FillW9ExternalDocIdRoute: typeof FillW9ExternalDocIdRoute
  FillW9DocIdRoute: typeof FillW9DocIdRoute
  FillWageAckExternalDocIdRoute: typeof FillWageAckExternalDocIdRoute
  FillWageAckDocIdRoute: typeof FillWageAckDocIdRoute
  MModuleRoute: typeof MModuleRouteWithChildren
  SignActionPlanExternalDocIdRoute: typeof SignActionPlanExternalDocIdRoute
  SignActionPlanFormDocIdRoute: typeof SignActionPlanFormDocIdRoute
  SignContractorAddendumExternalDocIdRoute: typeof SignContractorAddendumExternalDocIdRoute
  SignContractorAddendumDocIdRoute: typeof SignContractorAddendumDocIdRoute
  SignDocumentDocIdRoute: typeof SignDocumentDocIdRoute
  SignExternalDocIdRoute: typeof SignExternalDocIdRoute
  SignManagerReviewDocIdRoute: typeof SignManagerReviewDocIdRoute
  SignNdaExternalDocIdRoute: typeof SignNdaExternalDocIdRoute
  SignNdaFormDocIdRoute: typeof SignNdaFormDocIdRoute
  SignPromotionExternalDocIdRoute: typeof SignPromotionExternalDocIdRoute
  SignPromotionFormDocIdRoute: typeof SignPromotionFormDocIdRoute
  SignTerminationExternalDocIdRoute: typeof SignTerminationExternalDocIdRoute
  SignTerminationFormDocIdRoute: typeof SignTerminationFormDocIdRoute
  TicketTicketNoRoute: typeof TicketTicketNoRoute
  TicketsMapRoute: typeof TicketsMapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timecard': {
      id: '/timecard'
      path: '/timecard'
      fullPath: '/timecard'
      preLoaderRoute: typeof TimecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-bundle-external': {
      id: '/sign-bundle-external'
      path: '/sign-bundle-external'
      fullPath: '/sign-bundle-external'
      preLoaderRoute: typeof SignBundleExternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-bundle-employer': {
      id: '/sign-bundle-employer'
      path: '/sign-bundle-employer'
      fullPath: '/sign-bundle-employer'
      preLoaderRoute: typeof SignBundleEmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-bundle': {
      id: '/sign-bundle'
      path: '/sign-bundle'
      fullPath: '/sign-bundle'
      preLoaderRoute: typeof SignBundleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicepower-test': {
      id: '/servicepower-test'
      path: '/servicepower-test'
      fullPath: '/servicepower-test'
      preLoaderRoute: typeof ServicepowerTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it-tickets': {
      id: '/it-tickets'
      path: '/it-tickets'
      fullPath: '/it-tickets'
      preLoaderRoute: typeof ItTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-activity-log': {
      id: '/hr-activity-log'
      path: '/hr-activity-log'
      fullPath: '/hr-activity-log'
      preLoaderRoute: typeof HrActivityLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firebase-setup': {
      id: '/firebase-setup'
      path: '/firebase-setup'
      fullPath: '/firebase-setup'
      preLoaderRoute: typeof FirebaseSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/map': {
      id: '/tickets/map'
      path: '/tickets/map'
      fullPath: '/tickets/map'
      preLoaderRoute: typeof TicketsMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$ticketNo': {
      id: '/ticket/$ticketNo'
      path: '/ticket/$ticketNo'
      fullPath: '/ticket/$ticketNo'
      preLoaderRoute: typeof TicketTicketNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-termination-form/$docId': {
      id: '/sign-termination-form/$docId'
      path: '/sign-termination-form/$docId'
      fullPath: '/sign-termination-form/$docId'
      preLoaderRoute: typeof SignTerminationFormDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-termination-external/$docId': {
      id: '/sign-termination-external/$docId'
      path: '/sign-termination-external/$docId'
      fullPath: '/sign-termination-external/$docId'
      preLoaderRoute: typeof SignTerminationExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-promotion-form/$docId': {
      id: '/sign-promotion-form/$docId'
      path: '/sign-promotion-form/$docId'
      fullPath: '/sign-promotion-form/$docId'
      preLoaderRoute: typeof SignPromotionFormDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-promotion-external/$docId': {
      id: '/sign-promotion-external/$docId'
      path: '/sign-promotion-external/$docId'
      fullPath: '/sign-promotion-external/$docId'
      preLoaderRoute: typeof SignPromotionExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-nda-form/$docId': {
      id: '/sign-nda-form/$docId'
      path: '/sign-nda-form/$docId'
      fullPath: '/sign-nda-form/$docId'
      preLoaderRoute: typeof SignNdaFormDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-nda-external/$docId': {
      id: '/sign-nda-external/$docId'
      path: '/sign-nda-external/$docId'
      fullPath: '/sign-nda-external/$docId'
      preLoaderRoute: typeof SignNdaExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-manager-review/$docId': {
      id: '/sign-manager-review/$docId'
      path: '/sign-manager-review/$docId'
      fullPath: '/sign-manager-review/$docId'
      preLoaderRoute: typeof SignManagerReviewDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-external/$docId': {
      id: '/sign-external/$docId'
      path: '/sign-external/$docId'
      fullPath: '/sign-external/$docId'
      preLoaderRoute: typeof SignExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-document/$docId': {
      id: '/sign-document/$docId'
      path: '/sign-document/$docId'
      fullPath: '/sign-document/$docId'
      preLoaderRoute: typeof SignDocumentDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-contractor-addendum/$docId': {
      id: '/sign-contractor-addendum/$docId'
      path: '/sign-contractor-addendum/$docId'
      fullPath: '/sign-contractor-addendum/$docId'
      preLoaderRoute: typeof SignContractorAddendumDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-contractor-addendum-external/$docId': {
      id: '/sign-contractor-addendum-external/$docId'
      path: '/sign-contractor-addendum-external/$docId'
      fullPath: '/sign-contractor-addendum-external/$docId'
      preLoaderRoute: typeof SignContractorAddendumExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-action-plan-form/$docId': {
      id: '/sign-action-plan-form/$docId'
      path: '/sign-action-plan-form/$docId'
      fullPath: '/sign-action-plan-form/$docId'
      preLoaderRoute: typeof SignActionPlanFormDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-action-plan-external/$docId': {
      id: '/sign-action-plan-external/$docId'
      path: '/sign-action-plan-external/$docId'
      fullPath: '/sign-action-plan-external/$docId'
      preLoaderRoute: typeof SignActionPlanExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$module': {
      id: '/m/$module'
      path: '/m/$module'
      fullPath: '/m/$module'
      preLoaderRoute: typeof MModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-wage-ack/$docId': {
      id: '/fill-wage-ack/$docId'
      path: '/fill-wage-ack/$docId'
      fullPath: '/fill-wage-ack/$docId'
      preLoaderRoute: typeof FillWageAckDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-wage-ack-external/$docId': {
      id: '/fill-wage-ack-external/$docId'
      path: '/fill-wage-ack-external/$docId'
      fullPath: '/fill-wage-ack-external/$docId'
      preLoaderRoute: typeof FillWageAckExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-w9/$docId': {
      id: '/fill-w9/$docId'
      path: '/fill-w9/$docId'
      fullPath: '/fill-w9/$docId'
      preLoaderRoute: typeof FillW9DocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-w9-external/$docId': {
      id: '/fill-w9-external/$docId'
      path: '/fill-w9-external/$docId'
      fullPath: '/fill-w9-external/$docId'
      preLoaderRoute: typeof FillW9ExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-w8ben/$docId': {
      id: '/fill-w8ben/$docId'
      path: '/fill-w8ben/$docId'
      fullPath: '/fill-w8ben/$docId'
      preLoaderRoute: typeof FillW8benDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-w8ben-external/$docId': {
      id: '/fill-w8ben-external/$docId'
      path: '/fill-w8ben-external/$docId'
      fullPath: '/fill-w8ben-external/$docId'
      preLoaderRoute: typeof FillW8benExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-w4r/$docId': {
      id: '/fill-w4r/$docId'
      path: '/fill-w4r/$docId'
      fullPath: '/fill-w4r/$docId'
      preLoaderRoute: typeof FillW4rDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-w4r-external/$docId': {
      id: '/fill-w4r-external/$docId'
      path: '/fill-w4r-external/$docId'
      fullPath: '/fill-w4r-external/$docId'
      preLoaderRoute: typeof FillW4rExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-w4/$docId': {
      id: '/fill-w4/$docId'
      path: '/fill-w4/$docId'
      fullPath: '/fill-w4/$docId'
      preLoaderRoute: typeof FillW4DocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-w4-external/$docId': {
      id: '/fill-w4-external/$docId'
      path: '/fill-w4-external/$docId'
      fullPath: '/fill-w4-external/$docId'
      preLoaderRoute: typeof FillW4ExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-vehicle-use-agreement/$docId': {
      id: '/fill-vehicle-use-agreement/$docId'
      path: '/fill-vehicle-use-agreement/$docId'
      fullPath: '/fill-vehicle-use-agreement/$docId'
      preLoaderRoute: typeof FillVehicleUseAgreementDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-vehicle-use-agreement-external/$docId': {
      id: '/fill-vehicle-use-agreement-external/$docId'
      path: '/fill-vehicle-use-agreement-external/$docId'
      fullPath: '/fill-vehicle-use-agreement-external/$docId'
      preLoaderRoute: typeof FillVehicleUseAgreementExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-vehicle-agreement/$docId': {
      id: '/fill-vehicle-agreement/$docId'
      path: '/fill-vehicle-agreement/$docId'
      fullPath: '/fill-vehicle-agreement/$docId'
      preLoaderRoute: typeof FillVehicleAgreementDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-vehicle-agreement-external/$docId': {
      id: '/fill-vehicle-agreement-external/$docId'
      path: '/fill-vehicle-agreement-external/$docId'
      fullPath: '/fill-vehicle-agreement-external/$docId'
      preLoaderRoute: typeof FillVehicleAgreementExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-substance-screening/$docId': {
      id: '/fill-substance-screening/$docId'
      path: '/fill-substance-screening/$docId'
      fullPath: '/fill-substance-screening/$docId'
      preLoaderRoute: typeof FillSubstanceScreeningDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-substance-screening-external/$docId': {
      id: '/fill-substance-screening-external/$docId'
      path: '/fill-substance-screening-external/$docId'
      fullPath: '/fill-substance-screening-external/$docId'
      preLoaderRoute: typeof FillSubstanceScreeningExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-pto-ack/$docId': {
      id: '/fill-pto-ack/$docId'
      path: '/fill-pto-ack/$docId'
      fullPath: '/fill-pto-ack/$docId'
      preLoaderRoute: typeof FillPtoAckDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-pto-ack-external/$docId': {
      id: '/fill-pto-ack-external/$docId'
      path: '/fill-pto-ack-external/$docId'
      fullPath: '/fill-pto-ack-external/$docId'
      preLoaderRoute: typeof FillPtoAckExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-parts-responsibility/$docId': {
      id: '/fill-parts-responsibility/$docId'
      path: '/fill-parts-responsibility/$docId'
      fullPath: '/fill-parts-responsibility/$docId'
      preLoaderRoute: typeof FillPartsResponsibilityDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-parts-responsibility-external/$docId': {
      id: '/fill-parts-responsibility-external/$docId'
      path: '/fill-parts-responsibility-external/$docId'
      fullPath: '/fill-parts-responsibility-external/$docId'
      preLoaderRoute: typeof FillPartsResponsibilityExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-mileage-fuel/$docId': {
      id: '/fill-mileage-fuel/$docId'
      path: '/fill-mileage-fuel/$docId'
      fullPath: '/fill-mileage-fuel/$docId'
      preLoaderRoute: typeof FillMileageFuelDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-mileage-fuel-external/$docId': {
      id: '/fill-mileage-fuel-external/$docId'
      path: '/fill-mileage-fuel-external/$docId'
      fullPath: '/fill-mileage-fuel-external/$docId'
      preLoaderRoute: typeof FillMileageFuelExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-meal-rest-break/$docId': {
      id: '/fill-meal-rest-break/$docId'
      path: '/fill-meal-rest-break/$docId'
      fullPath: '/fill-meal-rest-break/$docId'
      preLoaderRoute: typeof FillMealRestBreakDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-meal-rest-break-external/$docId': {
      id: '/fill-meal-rest-break-external/$docId'
      path: '/fill-meal-rest-break-external/$docId'
      fullPath: '/fill-meal-rest-break-external/$docId'
      preLoaderRoute: typeof FillMealRestBreakExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-master-w2-office-agreement/$docId': {
      id: '/fill-master-w2-office-agreement/$docId'
      path: '/fill-master-w2-office-agreement/$docId'
      fullPath: '/fill-master-w2-office-agreement/$docId'
      preLoaderRoute: typeof FillMasterW2OfficeAgreementDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-master-w2-agreement/$docId': {
      id: '/fill-master-w2-agreement/$docId'
      path: '/fill-master-w2-agreement/$docId'
      fullPath: '/fill-master-w2-agreement/$docId'
      preLoaderRoute: typeof FillMasterW2AgreementDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-master-ph-contractor-agreement/$docId': {
      id: '/fill-master-ph-contractor-agreement/$docId'
      path: '/fill-master-ph-contractor-agreement/$docId'
      fullPath: '/fill-master-ph-contractor-agreement/$docId'
      preLoaderRoute: typeof FillMasterPhContractorAgreementDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-location-consent/$docId': {
      id: '/fill-location-consent/$docId'
      path: '/fill-location-consent/$docId'
      fullPath: '/fill-location-consent/$docId'
      preLoaderRoute: typeof FillLocationConsentDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-location-consent-external/$docId': {
      id: '/fill-location-consent-external/$docId'
      path: '/fill-location-consent-external/$docId'
      fullPath: '/fill-location-consent-external/$docId'
      preLoaderRoute: typeof FillLocationConsentExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-i9/$docId': {
      id: '/fill-i9/$docId'
      path: '/fill-i9/$docId'
      fullPath: '/fill-i9/$docId'
      preLoaderRoute: typeof FillI9DocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-i9-external/$docId': {
      id: '/fill-i9-external/$docId'
      path: '/fill-i9-external/$docId'
      fullPath: '/fill-i9-external/$docId'
      preLoaderRoute: typeof FillI9ExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-form/$formId': {
      id: '/fill-form/$formId'
      path: '/fill-form/$formId'
      fullPath: '/fill-form/$formId'
      preLoaderRoute: typeof FillFormFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-flash-technician-travel/$docId': {
      id: '/fill-flash-technician-travel/$docId'
      path: '/fill-flash-technician-travel/$docId'
      fullPath: '/fill-flash-technician-travel/$docId'
      preLoaderRoute: typeof FillFlashTechnicianTravelDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-flash-technician-travel-external/$docId': {
      id: '/fill-flash-technician-travel-external/$docId'
      path: '/fill-flash-technician-travel-external/$docId'
      fullPath: '/fill-flash-technician-travel-external/$docId'
      preLoaderRoute: typeof FillFlashTechnicianTravelExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-employee-confidentiality/$docId': {
      id: '/fill-employee-confidentiality/$docId'
      path: '/fill-employee-confidentiality/$docId'
      fullPath: '/fill-employee-confidentiality/$docId'
      preLoaderRoute: typeof FillEmployeeConfidentialityDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-employee-confidentiality-external/$docId': {
      id: '/fill-employee-confidentiality-external/$docId'
      path: '/fill-employee-confidentiality-external/$docId'
      fullPath: '/fill-employee-confidentiality-external/$docId'
      preLoaderRoute: typeof FillEmployeeConfidentialityExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-direct-deposit/$docId': {
      id: '/fill-direct-deposit/$docId'
      path: '/fill-direct-deposit/$docId'
      fullPath: '/fill-direct-deposit/$docId'
      preLoaderRoute: typeof FillDirectDepositDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-direct-deposit-external/$docId': {
      id: '/fill-direct-deposit-external/$docId'
      path: '/fill-direct-deposit-external/$docId'
      fullPath: '/fill-direct-deposit-external/$docId'
      preLoaderRoute: typeof FillDirectDepositExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-damage/$docId': {
      id: '/fill-damage/$docId'
      path: '/fill-damage/$docId'
      fullPath: '/fill-damage/$docId'
      preLoaderRoute: typeof FillDamageDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-damage-external/$docId': {
      id: '/fill-damage-external/$docId'
      path: '/fill-damage-external/$docId'
      fullPath: '/fill-damage-external/$docId'
      preLoaderRoute: typeof FillDamageExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-contractor-data/$docId': {
      id: '/fill-contractor-data/$docId'
      path: '/fill-contractor-data/$docId'
      fullPath: '/fill-contractor-data/$docId'
      preLoaderRoute: typeof FillContractorDataDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-contractor-data-us/$docId': {
      id: '/fill-contractor-data-us/$docId'
      path: '/fill-contractor-data-us/$docId'
      fullPath: '/fill-contractor-data-us/$docId'
      preLoaderRoute: typeof FillContractorDataUsDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-contractor-data-us-external/$docId': {
      id: '/fill-contractor-data-us-external/$docId'
      path: '/fill-contractor-data-us-external/$docId'
      fullPath: '/fill-contractor-data-us-external/$docId'
      preLoaderRoute: typeof FillContractorDataUsExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-contractor-data-external/$docId': {
      id: '/fill-contractor-data-external/$docId'
      path: '/fill-contractor-data-external/$docId'
      fullPath: '/fill-contractor-data-external/$docId'
      preLoaderRoute: typeof FillContractorDataExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-contractor-addendum/$docId': {
      id: '/fill-contractor-addendum/$docId'
      path: '/fill-contractor-addendum/$docId'
      fullPath: '/fill-contractor-addendum/$docId'
      preLoaderRoute: typeof FillContractorAddendumDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-contractor-addendum-external/$docId': {
      id: '/fill-contractor-addendum-external/$docId'
      path: '/fill-contractor-addendum-external/$docId'
      fullPath: '/fill-contractor-addendum-external/$docId'
      preLoaderRoute: typeof FillContractorAddendumExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-car-iq-agreement/$docId': {
      id: '/fill-car-iq-agreement/$docId'
      path: '/fill-car-iq-agreement/$docId'
      fullPath: '/fill-car-iq-agreement/$docId'
      preLoaderRoute: typeof FillCarIqAgreementDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-car-iq-agreement-external/$docId': {
      id: '/fill-car-iq-agreement-external/$docId'
      path: '/fill-car-iq-agreement-external/$docId'
      fullPath: '/fill-car-iq-agreement-external/$docId'
      preLoaderRoute: typeof FillCarIqAgreementExternalDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/$employeeId': {
      id: '/employee/$employeeId'
      path: '/employee/$employeeId'
      fullPath: '/employee/$employeeId'
      preLoaderRoute: typeof EmployeeEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csr-agent/$agentId': {
      id: '/csr-agent/$agentId'
      path: '/csr-agent/$agentId'
      fullPath: '/csr-agent/$agentId'
      preLoaderRoute: typeof CsrAgentAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$slug': {
      id: '/apply/$slug'
      path: '/apply/$slug'
      fullPath: '/apply/$slug'
      preLoaderRoute: typeof ApplySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/company/$companyId': {
      id: '/superadmin/company/$companyId'
      path: '/company/$companyId'
      fullPath: '/superadmin/company/$companyId'
      preLoaderRoute: typeof SuperadminCompanyCompanyIdRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/m/$module/$submodule': {
      id: '/m/$module/$submodule'
      path: '/$submodule'
      fullPath: '/m/$module/$submodule'
      preLoaderRoute: typeof MModuleSubmoduleRouteImport
      parentRoute: typeof MModuleRoute
    }
    '/m/$module/$submodule/$userId': {
      id: '/m/$module/$submodule/$userId'
      path: '/$userId'
      fullPath: '/m/$module/$submodule/$userId'
      preLoaderRoute: typeof MModuleSubmoduleUserIdRouteImport
      parentRoute: typeof MModuleSubmoduleRoute
    }
  }
}

interface SuperadminRouteChildren {
  SuperadminCompanyCompanyIdRoute: typeof SuperadminCompanyCompanyIdRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminCompanyCompanyIdRoute: SuperadminCompanyCompanyIdRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

interface MModuleSubmoduleRouteChildren {
  MModuleSubmoduleUserIdRoute: typeof MModuleSubmoduleUserIdRoute
}

const MModuleSubmoduleRouteChildren: MModuleSubmoduleRouteChildren = {
  MModuleSubmoduleUserIdRoute: MModuleSubmoduleUserIdRoute,
}

const MModuleSubmoduleRouteWithChildren =
  MModuleSubmoduleRoute._addFileChildren(MModuleSubmoduleRouteChildren)

interface MModuleRouteChildren {
  MModuleSubmoduleRoute: typeof MModuleSubmoduleRouteWithChildren
}

const MModuleRouteChildren: MModuleRouteChildren = {
  MModuleSubmoduleRoute: MModuleSubmoduleRouteWithChildren,
}

const MModuleRouteWithChildren =
  MModuleRoute._addFileChildren(MModuleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  FirebaseSetupRoute: FirebaseSetupRoute,
  HomeRoute: HomeRoute,
  HrActivityLogRoute: HrActivityLogRoute,
  ItTicketsRoute: ItTicketsRoute,
  LandingRoute: LandingRoute,
  MobileRoute: MobileRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ServicepowerTestRoute: ServicepowerTestRoute,
  SettingsRoute: SettingsRoute,
  SignBundleRoute: SignBundleRoute,
  SignBundleEmployerRoute: SignBundleEmployerRoute,
  SignBundleExternalRoute: SignBundleExternalRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
  TimecardRoute: TimecardRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApplySlugRoute: ApplySlugRoute,
  CsrAgentAgentIdRoute: CsrAgentAgentIdRoute,
  EmployeeEmployeeIdRoute: EmployeeEmployeeIdRoute,
  FillCarIqAgreementExternalDocIdRoute: FillCarIqAgreementExternalDocIdRoute,
  FillCarIqAgreementDocIdRoute: FillCarIqAgreementDocIdRoute,
  FillContractorAddendumExternalDocIdRoute:
    FillContractorAddendumExternalDocIdRoute,
  FillContractorAddendumDocIdRoute: FillContractorAddendumDocIdRoute,
  FillContractorDataExternalDocIdRoute: FillContractorDataExternalDocIdRoute,
  FillContractorDataUsExternalDocIdRoute:
    FillContractorDataUsExternalDocIdRoute,
  FillContractorDataUsDocIdRoute: FillContractorDataUsDocIdRoute,
  FillContractorDataDocIdRoute: FillContractorDataDocIdRoute,
  FillDamageExternalDocIdRoute: FillDamageExternalDocIdRoute,
  FillDamageDocIdRoute: FillDamageDocIdRoute,
  FillDirectDepositExternalDocIdRoute: FillDirectDepositExternalDocIdRoute,
  FillDirectDepositDocIdRoute: FillDirectDepositDocIdRoute,
  FillEmployeeConfidentialityExternalDocIdRoute:
    FillEmployeeConfidentialityExternalDocIdRoute,
  FillEmployeeConfidentialityDocIdRoute: FillEmployeeConfidentialityDocIdRoute,
  FillFlashTechnicianTravelExternalDocIdRoute:
    FillFlashTechnicianTravelExternalDocIdRoute,
  FillFlashTechnicianTravelDocIdRoute: FillFlashTechnicianTravelDocIdRoute,
  FillFormFormIdRoute: FillFormFormIdRoute,
  FillI9ExternalDocIdRoute: FillI9ExternalDocIdRoute,
  FillI9DocIdRoute: FillI9DocIdRoute,
  FillLocationConsentExternalDocIdRoute: FillLocationConsentExternalDocIdRoute,
  FillLocationConsentDocIdRoute: FillLocationConsentDocIdRoute,
  FillMasterPhContractorAgreementDocIdRoute:
    FillMasterPhContractorAgreementDocIdRoute,
  FillMasterW2AgreementDocIdRoute: FillMasterW2AgreementDocIdRoute,
  FillMasterW2OfficeAgreementDocIdRoute: FillMasterW2OfficeAgreementDocIdRoute,
  FillMealRestBreakExternalDocIdRoute: FillMealRestBreakExternalDocIdRoute,
  FillMealRestBreakDocIdRoute: FillMealRestBreakDocIdRoute,
  FillMileageFuelExternalDocIdRoute: FillMileageFuelExternalDocIdRoute,
  FillMileageFuelDocIdRoute: FillMileageFuelDocIdRoute,
  FillPartsResponsibilityExternalDocIdRoute:
    FillPartsResponsibilityExternalDocIdRoute,
  FillPartsResponsibilityDocIdRoute: FillPartsResponsibilityDocIdRoute,
  FillPtoAckExternalDocIdRoute: FillPtoAckExternalDocIdRoute,
  FillPtoAckDocIdRoute: FillPtoAckDocIdRoute,
  FillSubstanceScreeningExternalDocIdRoute:
    FillSubstanceScreeningExternalDocIdRoute,
  FillSubstanceScreeningDocIdRoute: FillSubstanceScreeningDocIdRoute,
  FillVehicleAgreementExternalDocIdRoute:
    FillVehicleAgreementExternalDocIdRoute,
  FillVehicleAgreementDocIdRoute: FillVehicleAgreementDocIdRoute,
  FillVehicleUseAgreementExternalDocIdRoute:
    FillVehicleUseAgreementExternalDocIdRoute,
  FillVehicleUseAgreementDocIdRoute: FillVehicleUseAgreementDocIdRoute,
  FillW4ExternalDocIdRoute: FillW4ExternalDocIdRoute,
  FillW4DocIdRoute: FillW4DocIdRoute,
  FillW4rExternalDocIdRoute: FillW4rExternalDocIdRoute,
  FillW4rDocIdRoute: FillW4rDocIdRoute,
  FillW8benExternalDocIdRoute: FillW8benExternalDocIdRoute,
  FillW8benDocIdRoute: FillW8benDocIdRoute,
  FillW9ExternalDocIdRoute: FillW9ExternalDocIdRoute,
  FillW9DocIdRoute: FillW9DocIdRoute,
  FillWageAckExternalDocIdRoute: FillWageAckExternalDocIdRoute,
  FillWageAckDocIdRoute: FillWageAckDocIdRoute,
  MModuleRoute: MModuleRouteWithChildren,
  SignActionPlanExternalDocIdRoute: SignActionPlanExternalDocIdRoute,
  SignActionPlanFormDocIdRoute: SignActionPlanFormDocIdRoute,
  SignContractorAddendumExternalDocIdRoute:
    SignContractorAddendumExternalDocIdRoute,
  SignContractorAddendumDocIdRoute: SignContractorAddendumDocIdRoute,
  SignDocumentDocIdRoute: SignDocumentDocIdRoute,
  SignExternalDocIdRoute: SignExternalDocIdRoute,
  SignManagerReviewDocIdRoute: SignManagerReviewDocIdRoute,
  SignNdaExternalDocIdRoute: SignNdaExternalDocIdRoute,
  SignNdaFormDocIdRoute: SignNdaFormDocIdRoute,
  SignPromotionExternalDocIdRoute: SignPromotionExternalDocIdRoute,
  SignPromotionFormDocIdRoute: SignPromotionFormDocIdRoute,
  SignTerminationExternalDocIdRoute: SignTerminationExternalDocIdRoute,
  SignTerminationFormDocIdRoute: SignTerminationFormDocIdRoute,
  TicketTicketNoRoute: TicketTicketNoRoute,
  TicketsMapRoute: TicketsMapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
