-- =====================================================================
-- 0141 — Mileage entries: link to source ticket, support auto-sync
--
-- Adds an optional link back to the ticket a mileage entry came from, plus
-- a source flag distinguishing manually-typed entries (the original
-- 0125 design) from ones auto-generated by syncing a technician's
-- completed tickets through the existing office-to-customer distance
-- calculator (mapEngine.ts's computeOfficeDistanceMiles — already used on
-- the ticket detail page, just never persisted before).
--
-- The partial unique index is the dedup guard: re-running a sync for the
-- same technician/date-range can't create a second row for a ticket that
-- already produced one, without needing every caller to remember to check
-- first.
--
-- Run once in the Supabase SQL Editor, after 0140.
-- =====================================================================

alter table mileage_entries add column if not exists ticket_id uuid references tickets(id) on delete set null;
alter table mileage_entries add column if not exists source text not null default 'manual';

create unique index if not exists idx_mileage_entries_ticket_dedup
  on mileage_entries(company_id, ticket_id) where ticket_id is not null;
